### ISSUE TITLE
ERROR 502 - Unknown error

### ISSUE THREAD

**Issue by piejanssens** [spotweb/spotweb#178] opened 2016-07-28 09:05 UTC
Is this just a placeholder image in case the post has no image?
In that case I'd prefer no image at all.

**Comment by Wally73** [comment] 2016-07-28 09:12
no idea what issue this is about as you haven't included that

**Comment by piejanssens** [comment] 2016-07-28 09:17
I thought it was clear from the description that it's about the image/cover of a post, either the image shown in the popup when hovering a post in the list, or the image when looking at a post in detail.
I don't see this error placeholder image on all posts, roughly 50%.

![](https://cdn.pbrd.co/images/1KYjMBSGA.png)

**Comment by Wally73** [comment] 2016-07-28 09:19
ow that happens due mostly the USP you use (propagation issue mostly ) (afaik) 

and no it wasn't clear what the issue was (at least not for me)

**Comment by piejanssens** [comment] 2016-07-28 09:21
I see, do you know of any written explenation/cause about the exact issue so that I can present it to my USP?

**Comment by mesa57** [comment] 2016-07-28 14:46
Is it possible to create a WireShark or Microsoft network monitor log during the opening of such a spot ?
I once send such a log to my provider and they really solved the problem,

**Comment by piejanssens** [comment] 2016-07-28 17:40
Is it for the same reason that occasionally I can't open the spot (as in I receive a popup error message and can not go to the details page)?

**Comment by Sweepr** [comment] 2016-07-28 18:21
If the image/nzb/spotdata isn't "yet" stored locally using cache, spotweb tries to fetch it from the USP, if for some reason all connection's are used it cannot fetch (hence -> error), this could also be caused by rate-limiting by the USP itself altough this is rare.

With "Retrieve full spots" turned On, all data is retrieved and stored in cache upon retrieval, thus not needed to contact the USP everytime a certain spot is opened, but logically this take's longer to finish so we are used to not having "Retrieve full spots" turned on default.

**Comment by Sweepr** [comment] 2016-07-28 18:28
From the Wiki:

What do all the 'Retrieve .... ?' options mean?

Full spots: Per default Spotnet clients only retrieve the usenet headers but these do not contain all of the necessary information to display a full spot. For example to display the full description and picture you need the full spot which is (default) only retrieved when you actually open a spot.

By enabling this setting Spotweb will retrieve the fullspot whenever retrieve.php is run. This makes retrieve.php a lot slower but Spotweb itself faster. Makes using Spotweb faster but both retrieval slower and your database larger.

Prefetch images and Prefetch NZB files: Same as above but for images and NZB files. Will increase the size of your database a lot and retrieving of new spots a lot slower.

**Comment by mesa57** [comment] 2016-07-28 18:51
I do not advise to turn on 'retrieve full spots' as this will take much more time and the database will grow very big,

**Comment by Sweepr** [comment] 2016-07-28 19:07
@mesa57 Me neither, but just to explain how it works.
@piejanssens Do you use that USP for spotweb only or do you use the same account for more than one program?

**Comment by piejanssens** [comment] 2016-07-28 19:08
I'm using XS Usenet for Spotweb only, because my main USP didn't work at all to retrieve spots.

**Comment by Sweepr** [comment] 2016-07-28 19:14
@piejanssens Ok, it could still be you are hitting somekind of rate/connection limit on the USP, are you noticing the same behaviour all day long?

**Comment by Sweepr** [comment] 2016-07-28 19:16
For example some USP's only allow 1 connection per IP, altough the allow multiple threads, spotweb uses only 1 thread, it's not multi-threaded, so when retriever is running spotweb cannot connect to the USP to fetch the data.

**Comment by Sweepr** [comment] 2016-07-28 19:23
@piejanssens how often do you retrieve? and do you notice a difference if retrieve is not running?

**Comment by piejanssens** [comment] 2016-07-28 19:24
No I have it so often that it has to be the same when it's not retrieving. 
Retriever is scheduled every hour.

**Comment by Sweepr** [comment] 2016-07-28 19:26
So even with the retrieve not running you still have the error and the pop-up saying it failed to load the spot?

**Comment by piejanssens** [comment] 2016-07-28 19:27
Yes indeed

**Comment by Sweepr** [comment] 2016-07-28 19:29
Alright, and do you see anything in the log file of the http server?

**Comment by piejanssens** [comment] 2016-07-28 19:31
Apache logs?

**Comment by Sweepr** [comment] 2016-07-28 19:31
Yes and PHP error_log

**Comment by piejanssens** [comment] 2016-07-28 19:32
OK I'll check it later and let you know.

**Comment by mesa57** [comment] 2016-07-29 09:10
The error can also be caused by you;re ssl proxy.

**Comment by piejanssens** [comment] 2016-07-29 09:18
I'm using haproxy (synology). Is there any specific config required for Spotweb?

**Comment by mesa57** [comment] 2016-07-29 09:23
Spotweb has not been tested or certified for certain proxy's.
I do not know of excistance of special settings for proxy's

**Comment by piejanssens** [comment] 2016-07-29 09:25
OK but you do appear to know that certain proxies/settings can cause issues. :smiley: 
I'll check the apache and PHP logs first.

**Comment by mesa57** [comment] 2016-07-29 09:29
More important : check the HaProxy logs.

**Comment by piejanssens** [comment] 2016-07-29 09:56
Apache logs show a lot of these:
```[Thu Jul 28 21:37:45 2016] [error] [client 127.0.0.1] FastCGI: server "/php-fpm-handler" stderr: PHP message: SpotWeb Exception occured: Authentication rejected [response: "Maximum number of connections rea
ched"] [response: ""], referer: https://web.pj.synology.me/spotweb/?page=index&search[tree]=cat0_z1&search[value][]=
[Thu Jul 28 21:37:45 2016] [error] [client 127.0.0.1] FastCGI: server "/php-fpm-handler" stderr: PHP message: SpotWeb Exception occured: Authentication rejected [response: "Maximum number of connections rea
ched"] [response: ""], referer: https://web.pj.synology.me/spotweb/?page=index&search[tree]=cat0_z1&search[value][]=```

**Comment by piejanssens** [comment] 2016-07-29 10:10
Seems to be improved when I disable "Show subcats on mouseover in spots list". How do I change this setting for all users?

**Comment by Sweepr** [comment] 2016-07-29 10:46
In follow up of the log file, what do you see when you run retrieve manually from command?

Do you get the same error's about authentication rejected?

**Comment by Sweepr** [comment] 2016-08-07 15:14
Closing, since no update in 9 day's, re-open if needed

**Closed by Sweepr** 2016-08-07 15:14 UTC
Labels: help wanted
