### ISSUE TITLE
retrieve.php causes fatal error - call to a member function addchild()

### ISSUE THREAD

**Issue by Cromm** [spotweb/spotweb#160] opened 2016-04-23 15:25 UTC
I can't find anything online about this particular problem I'm having and hoping someone has seen it before or can help me to interpret where to look for a solution. 

The retrieve.php process crashes each time it is run, since 14 April and as far as I know nothing has changed at my end (although there is a possibility that Synology DSM has updated itself in that time).

Synology DSM 5.2-5644 Update 8
php memory limit set to 512M.

The retrieve.php process runs for a random amount of time and then each time produces this string of errors:

PHP Warning:  simplexml_load_string(): com/samples/cinematic-tension-sound-effects-download</Website><Image Width='300' in /volume1/web/spotweb/lib/services/Nntp/Services_Nntp_SpotReading.php on line 50
PHP Warning:  simplexml_load_string():                                                                                ^ in /volume1/web/spotweb/lib/services/Nntp/Services_Nntp_SpotReading.php on line 50
PHP Warning:  simplexml_load_string(): Entity: line 1: parser error : Couldn't find end of Start Tag Image line 1 in /volume1/web/spotweb/lib/services/Nntp/Services_Nntp_SpotReading.php on line 50
PHP Warning:  simplexml_load_string(): com/samples/cinematic-tension-sound-effects-download</Website><Image Width='300' in /volume1/web/spotweb/lib/services/Nntp/Services_Nntp_SpotReading.php on line 50
PHP Warning:  simplexml_load_string():                                                                                ^ in /volume1/web/spotweb/lib/services/Nntp/Services_Nntp_SpotReading.php on line 50
PHP Warning:  simplexml_load_string(): Entity: line 1: parser error : Opening and ending tag mismatch: Posting line 1 and Image in /volume1/web/spotweb/lib/services/Nntp/Services_Nntp_SpotReading.php on line 50
PHP Warning:  simplexml_load_string(): idth='300'Height='300'><Segment>zPP7muwILz8LTpfVgBX6a@spot.net</Segment></Image> in /volume1/web/spotweb/lib/services/Nntp/Services_Nntp_SpotReading.php on line 50
PHP Warning:  simplexml_load_string():                                                                                ^ in /volume1/web/spotweb/lib/services/Nntp/Services_Nntp_SpotReading.php on line 50
PHP Warning:  simplexml_load_string(): Entity: line 1: parser error : Opening and ending tag mismatch: Spotnet line 1 and Posting in /volume1/web/spotweb/lib/services/Nntp/Services_Nntp_SpotReading.php on line 50
PHP Warning:  simplexml_load_string(): /Category><NZB><Segment>GQmcWDB6bM4LTpfVgQV08@spot.net</Segment></NZB></Posting> in /volume1/web/spotweb/lib/services/Nntp/Services_Nntp_SpotReading.php on line 50
PHP Warning:  simplexml_load_string():                                                                                ^ in /volume1/web/spotweb/lib/services/Nntp/Services_Nntp_SpotReading.php on line 50
PHP Warning:  simplexml_load_string(): Entity: line 1: parser error : Extra content at the end of the document in /volume1/web/spotweb/lib/services/Nntp/Services_Nntp_SpotReading.php on line 50
PHP Warning:  simplexml_load_string(): /Category><NZB><Segment>GQmcWDB6bM4LTpfVgQV08@spot.net</Segment></NZB></Posting> in /volume1/web/spotweb/lib/services/Nntp/Services_Nntp_SpotReading.php on line 50
PHP Warning:  simplexml_load_string():                                                                                ^ in /volume1/web/spotweb/lib/services/Nntp/Services_Nntp_SpotReading.php on line 50
PHP Fatal error:  Call to a member function addChild() on a non-object in /volume1/web/spotweb/lib/services/Nntp/Services_Nntp_SpotReading.php on line 51

If anyone can help I'd appreciate it!

**Comment by Sweepr** [comment] 2016-04-23 16:51
Yikes, another Synology....

Yes i have seen this before, but since i moved to a dedicated server i stopped looking for the solution.

Could you create a phpinfo.php file with this inside:

**Comment by Cromm** [comment] 2016-04-23 17:43
Thanks for getting back to me. 

here you go:
[php.output.txt](https://github.com/spotweb/spotweb/files/233086/php.output.txt)

**Comment by Sweepr** [comment] 2016-04-23 17:55
Which branch are you running?  media or master?

**Comment by Cromm** [comment] 2016-04-23 18:00
I'm on master currently

**Comment by Sweepr** [comment] 2016-04-23 18:06
And which usenet provider? 

To me it looks like the XML your trying to read is either malformed causing problems in the Services_Nntp_SpotReading.php, this could be caused by temporary problems on your USP's end.

**Comment by Sweepr** [comment] 2016-04-23 18:12
You could try to disable "Retrieve full spots" under Settings -> Retrieve

**Comment by Cromm** [comment] 2016-04-23 18:15
usenetserver.
Thanks for that - I'll try changing setting and report back.

**Comment by mesa57** [comment] 2016-04-23 18:30
Already made a pull request for this  #159
And indeed, setting retrieve full spots to off will help.

**Comment by mesa57** [comment] 2016-04-23 18:50
Just testing the fix now, but need to do a retrieve with fullspots=on. That takes time ...

**Comment by Cromm** [comment] 2016-04-23 22:18
Good news mesa57 :-)

Retrieve.php is still running 4 hours one. Looks like disabling full spot retrieval is overcoming glitch in the meantime. 

Thanks v much for your help!

**Comment by mesa57** [comment] 2016-04-23 23:06
Reopening issue, as it is not resolved by changing code.

**Comment by mesa57** [comment] 2016-04-24 09:51
Ok, tested, fix solves the retrieve issue with spots with invalid XML.
I am going to commit that one.

**Closed** 2016-04-24 10:51 UTC
