### ISSUE TITLE
We can no longer retrieve spots using SSL on spotweb for Synology

### ISSUE THREAD

**Issue by Marcoevich** [spotweb/spotweb#72] opened 2015-06-15 09:31 UTC
Since Synology DSM 5.2 we can no longer retrieve spots using SSL. There are multiple forum topics that blame DSM 5.2 for this:

https://translate.google.nl/translate?sl=nl&tl=en&js=y&prev=_t&hl=nl&ie=UTF-8&u=http%3A%2F%2Fwww.synology-forum.nl%2Fspotweb%2Fspotweb-werkt-niet-meer-na-upgrade-dsm-5-2%2F&edit-text=&act=url

http://www.synology-forum.nl/spotweb/spotweb-i-c-m-taakplanner/55/?wap2

http://gathering.tweakers.net/forum/list_messages/1538893/32

The error I and everyone else gets is this one:

SpotWeb v0.67.28.31 on PHP v5.5.24 crashed

Fatal error occured while connecting to the newsserver:
  (-1) Failed to read from socket...! [response: ""]

Probably Synology has updated PHP in their latest DSM, which also updates the SSL library. Is there anything we can do to make spotweb work with the new SSL, rather than just turning it off?

Thanks for any reply :)

Cheers

**Comment by Sweepr** [comment] 2015-06-15 10:15
Not sure what the changes are in the new SSL library or if this library even is the root cause.

This needs some investigation to find the cause.

**Comment by Marcoevich** [comment] 2015-06-15 10:19
I would be happy to investigate this with you. Is there anything I can test on my end?

**Comment by Sweepr** [comment] 2015-06-15 10:26
We need to actively monitor that port and see if two-way traffic is working. So we need to monitor the SSL port and listen for traffic in /out, if this is the case then see if it's somehow malformed or failing to missing packets (packetloss) or timing out because the streams is wrong encoded/decoded.

Not something thats easy to do.

**Comment by Sweepr** [comment] 2015-06-15 16:35
If you login to your NAS using SSH, login and typ command:

**Comment by Marcoevich** [comment] 2015-06-15 16:43
It returns this: OpenSSL 1.0.1m-fips 19 Mar 2015

**Comment by beta990** [comment] 2015-06-18 12:05
Unfortunately the same issue here:
 $ openssl version
 OpenSSL 1.0.2c 12 Jun 2015

The first crash happen because of the [max_allowed_packet](https://stackoverflow.com/questions/8062496/how-to-change-max-allowed-packet-size) MySQL value was too low.
After increasing this value, the crashes reduced, but still the crashes happen.

**Comment by buurman** [comment] 2015-07-01 06:32
I'v got a Synology NAS with the latest DSM version and have no problems with retreiving spots over SSL.

**Comment by Wally73** [comment] 2015-07-01 07:45
might be handy if you said which version of php and ssl you have then
@buurman

**Comment by buurman** [comment] 2015-07-01 07:51
The version that comes as default with DSM 5.2-5565 update 2:
PHP 5.5.25
OpenSSL 1.0.1m-fips

**Comment by Wally73** [comment] 2015-07-01 07:53
that might help other DSM users ( i don't have one)

**Comment by Marcoevich** [comment] 2015-07-03 20:36
Retrieving spots is still not working for me after 4 weeks now, and even after latest synology update

In addition to the issues mentiond earlier in this thread, I am now getting these errors on running retrieve.php as well:

DiskStation> /usr/bin/php /volume1/web/spotweb/retrieve.php --force
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/modules/mysqli.so' - /usr/lib/php/modules/mysqli.so: undefined symbol: mysqlnd_get_client_info in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/modules/mysql.so' - /usr/lib/php/modules/mysql.so: undefined symbol: _mysqlnd_fetch_lengths in Unknown on line 0

**Comment by arion-rufus** [comment] 2015-08-06 14:20
I have the same issue here running a DS215i.
A temporary workaround is to retrieve without SSL. (go into spotweb - config - settings - newsservers (turn of encryption) and fill in the correct port number for your provider - OK) -> now do retrieve
Because you download via SABNZBd over a SSL connection anyway.
I hope the issue as described above will be resolved never the less :-)

**Comment by mesa57** [comment] 2015-09-01 08:47
Maybe related to issue #65

**Comment by buurman** [comment] 2015-10-14 05:53
I had no problems until yesterday after the upgrade to DSM 6.0 beta.

DSM 6.0-7135
OpenSSL 1.0.2d-fips 9 Jul 2015
PHP 5.6.13

Automatic retrieve/update is also broke, probably related to the new webstation/php integration in DSM which broke my cronjob, they use seperate packages now.

**Comment by avluis** [comment] 2015-10-14 14:59
@buurman 
My Spotweb has issues loading secure content (I load everything in SSL, but Web Station stills throws unsecured content somehow, could be ignoring an .htaccess file) so it doesn't load CSS and JS after installing 6.0 beta1.
Did you come across this issue or similar, however minor (I already went thru the import certificate issue as well).

**Comment by u2hub** [comment] 2015-10-23 18:07
buurman, same here.
Not only the issue of updating, but restoring filters of blacklist is not possible anymore.

Retrieve gives me the following error >>

/volume1/web/spotweb$ php retrieve.php
PHP Fatal error:  Undefined class constant 'MYSQL_ATTR_FOUND_ROWS' in /volume1/web/spotweb/lib/dbeng/dbeng_pdo_mysql.php on line 28

Fatal error: Undefined class constant 'MYSQL_ATTR_FOUND_ROWS' in /volume1/web/spotweb/lib/dbeng/dbeng_pdo_mysql.php on line 28

**Comment by buurman** [comment] 2015-10-23 18:12
The error with retrieve can be fixed by using '**php56** retrieve.php' instead of 'php .. ',

**Comment by u2hub** [comment] 2015-10-23 19:02
Thanks, still getting errors, but it is retrieving.

root@NAS:/volume1/web/spotweb# php56 retrieve.php --retro
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php56/modules/simplexml.so' - /usr/local/lib/php56/modules/simplexml.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php56/modules/xml.so' - /usr/local/lib/php56/modules/xml.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php56/modules/xmlreader.so' - /usr/local/lib/php56/modules/xmlreader.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php56/modules/xmlwriter.so' - /usr/local/lib/php56/modules/xmlwriter.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php56/modules/ctype.so' - /usr/local/lib/php56/modules/ctype.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php56/modules/dom.so' - /usr/local/lib/php56/modules/dom.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php56/modules/json.so' - /usr/local/lib/php56/modules/json.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php56/modules/mbstring.so' - /usr/local/lib/php56/modules/mbstring.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php56/modules/pdo.so' - /usr/local/lib/php56/modules/pdo.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php56/modules/session.so' - /usr/local/lib/php56/modules/session.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php56/modules/tokenizer.so' - /usr/local/lib/php56/modules/tokenizer.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php56/modules/fileinfo.so' - /usr/local/lib/php56/modules/fileinfo.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php56/modules/zlib.so' - /usr/local/lib/php56/modules/zlib.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Notice:  Undefined offset: 0 in /volume1/web/spotweb/lib/dbeng/dbeng_pdo.php on line 129
PHP Notice:  Undefined offset: 0 in /volume1/web/spotweb/lib/dbeng/dbeng_pdo.php on line 129

**Comment by buurman** [comment] 2015-10-23 19:06
Oh forget about that, had the same thing. After uninstalling webstation/php56, reboot, install webstation/php56, the errors vanished :-)

**Comment by Sweepr** [comment] 2015-10-23 19:06
Path to your *.so does not exist or is incorrect.. '/usr/local/lib/php56/modules'  check where your *.so's are located and change accordingly in your php.ini

**Comment by bakman2** [comment] 2015-11-23 16:10
I can't seem to retrieve anything (new install on synology)
```
NAS002> uname -a
Linux NAS002 2.6.32.12 #5644 Thu Nov 12 17:17:36 CST 2015 armv5tel GNU/Linux synology_88f6282_211+
NAS002> /usr/bin/php retrieve.php --force
Last retrieve at Thu 01 Jan 1970 01:00:00 AM CET
Retrieving new Spots from server news.newshosting.com...
Appr. Message count: 	2713124
First message number:	2
Last message number:	2713126
Current article number:	2

Retrieving 2 till 5003 (parsed: 5001, in DB: 0, signed: 0, invalid: 5001, rtntn.skip: 0, mod: 0, full: 0, total: 5001) in 5.48 seconds
Retrieving 5003 till 10004 (parsed: 5001, in DB: 0, signed: 0, invalid: 5001, rtntn.skip: 0, mod: 0, full: 0, total: 5001) in 5.12 seconds
Retrieving 10004 till 15005 (parsed: 5001, in DB: 0, signed: 0, invalid: 5001, rtntn.skip: 0, mod: 0, full: 0, total: 5001) in 5.39 seconds
Retrieving 15005 till 20006 (parsed: 5001, in DB: 0, signed: 0, invalid: 5001, rtntn.skip: 0, mod: 0, full: 0, total: 5001) in 6.35 seconds
Retrieving 20006 till 25007 (parsed: 5001, in DB: 0, signed: 0, invalid: 5001, rtntn.skip: 0, mod: 0, full: 0, total: 5001) in 5.37 seconds
Retrieving 25007 till 30008 (parsed: 5001, in DB: 0, signed: 0, invalid: 5001, rtntn.skip: 0, mod: 0, full: 0, total: 5001) in 6.21 seconds
Retrieving 30008 till 35009 (parsed: 5001, in DB: 0, signed: 0, invalid: 5001, rtntn.skip: 0, mod: 0, full: 0, total: 5001) in 5.74 seconds
Retrieving 35009 till 40010...etc
```
Everything ends up with either invalid or rtntn.skip (whatever that means). 
No SSL on port 119.

**Comment by Sweepr** [comment] 2015-11-23 16:14
Did you try your usenet server on a different machine ? like spotnet?

**Comment by Sweepr** [comment] 2015-11-23 16:14
Why are you forcing retrieve by the way?

**Comment by bakman2** [comment] 2015-11-23 16:15
force was done because spotweb stated that it was already running (which it was not).
i tried a different server, same result.

**Comment by Sweepr** [comment] 2015-11-23 16:20
Invalid or retention skip means that the article is either not found on the server or beyond server retention.

What happens is you increase this date in the settings? 

Thu 01 Jan 1970 01:00:00

**Comment by Sweepr** [comment] 2015-11-23 16:21
Maybe increase to 22 nov 2015 .. You can always do a backfill

**Comment by bakman2** [comment] 2015-11-23 16:22
I have set the date to 1 Nov 2015, dont know why it starts at 1970 (is it ignored?)

**Comment by Sweepr** [comment] 2015-11-23 16:31
Are you 100% sure the retriever is not running twice on your system?

**Comment by Sweepr** [comment] 2015-11-23 16:31
--force is not a good option to use as it can cause alot of trouble

**Comment by Sweepr** [comment] 2015-11-23 16:39
I will check this using the master branch, i'll get back in few.

**Comment by bakman2** [comment] 2015-11-23 16:41
Yes 100% sure. Rebooted and it still states that it is running. I see in the database too. 

But basically this is the first retrieve. I do see that there were a bunch of CVE's fixed in the DSM, not sure if that has anything to do with it, as I wouldn't be the only one.

**Comment by Sweepr** [comment] 2015-11-23 17:09
Not sure how to explain this but what you are seeing is normal behaviour for a fresh install.
A fresh install needs to "catch-up" on the USP's article count, in order to do so it has to count untill the time you set for it to retrieve because the Spotweb server does not know.

So i suggest letting in "catch-up" and you will see that eventually the spots will start to fill the DB.

Be aware that whenever you catch up on a usenetserver, stick to that one and never change inbetween because this can give problems with messed up article counts.

**Comment by bakman2** [comment] 2015-11-23 17:29
ok thanks, I will let it run.

**Comment by bakman2** [comment] 2015-11-23 20:26
Indeed, the spots are now starting to show up. Good to know that full retrieve is required the first time.

**Comment by mesa57** [comment] 2015-11-23 21:32
@Sweepr You're statement is of cause correct, I experienced it myself several time. 
But it would be nice if spotweb would locate the first article within the retention period by means of a binary search. That would tak much less time.

**Comment by Sweepr** [comment] 2015-11-23 22:13
@mesa7 That would probably mean a complete re-write of the existing code. 

Looking at the remark in spotweb/lib/services/Retriever/Services_Retriever_Base.php

We can read:

"If our database is empty, we just assume
 we have to start from zero. Else we do a lookup from
 the messageid to find the correct articlenumber.

 We cannot just use the articlenumber because the NNTP
 spec allows a server to renumber of course."

**Comment by Sweepr** [comment] 2015-11-23 22:24
@bakman2 

No problem, the first article on this page https://github.com/spotweb/spotweb/wiki/Frequently-asked-questions reads: 

"I only see two year old posts

Spotweb retrieves the oldest Spots' first. Just let retrieve.php running and after a while (depending on your internet connection speed, your usenet provider speed and your database speed) it will catchup and start showing recent spots."

Ofcourse when setting the "Retrieve spots after..." to the date of today it would take quite some time before you would actually see spots being stored in the DB, which you experienced.

**Comment by mesa57** [comment] 2015-11-24 11:04
@Sweepr Look like a challenge to me :)

**Comment by roeiegans** [comment] 2015-12-08 18:05
I have the same issue on my Synology as avluis from 14th of october. Any update on this issue?

"My Spotweb has issues loading secure content (I load everything in SSL, but Web Station stills throws unsecured content somehow, could be ignoring an .htaccess file) so it doesn't load CSS and JS after installing 6.0 beta1"

**Comment by avluis** [comment] 2016-01-21 16:47
@roeiegans As a quick update to my last comment, after updating DSM to 6.0 beta 2, we now get an option to pick the backend server - mine was set to Apache by default (DSM 6.0 beta 1 used ngix) and Spotweb is functional once again.

**Comment by Sweepr** [comment] 2016-01-21 16:56
So it looks like it's something with NginX that's causing these issue's?

**Comment by avluis** [comment] 2016-01-21 19:19
@Sweepr It's a combination of that and a forced browser setting on DSM 6.0 beta 1 that forced all content to be served securely, but doesn't redirect/proxy said content if requested unsecured.
That's what caused CSS and JS to not load on my install.

**Comment by thaLama** [comment] 2016-03-24 14:22
Hi guys, might be just something stupid but i am just to much of an idiot to sort this out...
Just updated to DSM 6.0-7321 (but issue was the same on the previous DSM 6 ver (RC)

spotweb itself works, i can login and see i got the latest posts (initial update) but for some reason updates are not working, i thought it was the cronjob but it is something else. When i check the spotweb log i got the following

:/volume1/web/spotweb# php retrieve.php
PHP Fatal error:  Undefined class constant 'MYSQL_ATTR_FOUND_ROWS' in /volume1/web/spotweb/lib/dbeng/dbeng_pdo_mysql.php on line 28


This a part of the dbeng_pdo_mysql.php 
24			try {
25				$this->_conn = new PDO('mysql:' . $db_conn . ';dbname=' . $db . ';charset=utf8',
26                                        $user,
27                                        $pass,
28                                        array(PDO::MYSQL_ATTR_FOUND_ROWS => true));
29			} catch (PDOException $e) {
30				throw new DatabaseConnectionException($e->getMessage(), -1);
31			}

I already mentioned i have no idea what i am doing, but i would like it to get it work :)
Can somebody maybe point me in the right direction? 

hardware DS416j
Web Station is set to Apache HTTP Server 2.2 / PHP 5.6 (tried Nginx also, but got the same issue)
php ver 5.6 (updated today, with the new DSM release)
MariaDB v 5.5.47-0064
spotweb v 20160320-1

Not sure if this is related in any way
git 2.7.4-8  (updated today, with the new DSM release)
Phyton 2.7.11-16
Phyton Module 
Phyton3 

If i need to post any further info please let me know, for some reason it seems like something easy to fix.

**Comment by thaLama** [comment] 2016-03-24 14:38
always after you finally post something you find something usefull...
just went through Retrieve broken DSM6 (RC) Synology #135 ,  and it is about the exact same issue

"mesa57 commented 11 days ago
I think you're mysql pdo extension for php needs updating."

now i understand what mesa57 is saying, but i have no idea what it means. Does it mean we need to wait for an update on the synology php package, or is there something we can do ourselves?

**Comment by mesa57** [comment] 2016-03-24 14:53
You can also try the tip posted here
http://www.spot-net.nl/forums/viewtopic.php?f=33&t=6479

**Comment by thaLama** [comment] 2016-03-24 15:34
Thanks! 
i tried that already. (all 3 options, and tried both of the below before and after a reinstall of web station)

The repair/optimize doesn't work because (but i tried this via phpMyAdmin also)
the command line option doesn't work as there is no mysql folder (/usr/syno/mysql)
/usr/syno/mysql/bin/mysqlcheck -u root -p --auto-repair --check --optimize spotweb
 
And trying any .php file i always get this same error (in the spotweb directory)
PHP Fatal error:  Undefined class constant 'MYSQL_ATTR_FOUND_ROWS' in /volume1/web/spotweb/lib/dbeng/dbeng_pdo_mysql.php on line 28

**Comment by avluis** [comment] 2016-03-24 18:46
@thaLama Can you run your retrieve.php with this: `/usr/local/bin/php56`
Would like to know what output you get there.

**Comment by Wally73** [comment] 2016-03-24 18:54
still is is a Synology issue not a spotweb issue IMO

**Comment by thaLama** [comment] 2016-03-24 19:08
@avluis, it exactly doesn't do anything 
Logged via ssh (root) and did as you asked, but there is no feedback/response at all

And yes, I think it's synology also, but just exactly sure where it goes wrong

**Comment by Sweepr** [comment] 2016-03-24 19:55
@thaLama 

Just a question, did you shutdown and restarted the NAS after the update?

**Comment by mesa57** [comment] 2016-03-24 21:49
Two issues are mixed up here. This one is about retrieve failing due to ssl #72 and thaLama is refering to issue #135 which is a php error.

**Comment by avluis** [comment] 2016-03-25 05:36
@mesa57 Yep - As a Syno user on DSM 6.0 (final); Spotweb is working with SSL (the SSL libraries were updated by Synology a while back) and I am not receiving the error @thaLama is getting either - my install is working wonders after switching the HTTP Backend Server setting in the Web Station app back to Apache (Nginx is the default here).

**Comment by thaLama** [comment] 2016-03-25 09:35
i tried everything i can think of, it must be something stupid i am sure.
also did the repair/check optimize but all looked ok, and in the end still the same issue.

should i raise a ticked with Synology to check maybe?
is there i way to force an update/check for the PDO extensions somehow?

So far a big thanks already for your support, really appreciated
cheers

**Comment by buurman** [comment] 2016-03-25 09:36
You just could try to reinstall webstation and php, if you allready haven't tried.

**Comment by thaLama** [comment] 2016-03-25 09:55
I did, but I can try that again this evening including spotweb and MariaDB also. As my NAS is pretty much still empty, it us just the initial posts retrieval that takes some waiting...... But when I do I just want to be sure there is a reasonable good change in fixing it. 
Avluis got it working, and I do not see any other threads appearing with my issue. 

@avluis, what model do you have it installed on? 
As my 416j has a Marvell Armada 388, and I couldn't use synocomunity for a while as the packages needed to be updated for this processor, maybe this is the case with other packages also (but no idea if this could anyway be related to my little issue)

**Comment by avluis** [comment] 2016-03-25 11:10
@thaLama I have a 1513+, but honestly that should not be what's causing your issue.
As you mentioned not having anything on your NAS, I would recommend forcing a full DSM re-install and see if that gets you anywhere closer to your end goal - I would take this as a step before giving up and asking Synology for help.
Use this [guide](https://www.synology.com/en-us/knowledgebase/DSM/tutorial/General/How_to_reset_your_Synology_NAS#t3) if you are unsure.

**Comment by mesa57** [comment] 2016-04-05 19:16
I am closing this issue, as SSL problemns are clearly related to the PHP version install.
If needed, please comment in https://github.com/spotweb/spotweb/issues/65

**Closed by mesa57** 2016-04-05 19:16 UTC
Labels: question
