### ISSUE TITLE
Spotweb and Sabnzbdplus 1.0.0

### ISSUE THREAD

**Issue by scanno** [spotweb/spotweb#94] opened 2015-09-28 20:53 UTC
With the update of sabnzbdplus to 0.8.0 on my ubuntu server, i cannot send a nzb to the sabnzbdplus download queue.

In the apache error log i see 

[Mon Sep 28 22:47:39.841971 2015] [:error] [pid 3645] [client 192.168.1.110:38441] sabnzbd push failed: http returncode: 200 / , referer: http://192.168.1.100/spotweb/?page=index&search[tree]=cat0_z0_a4,cat0_z0_a6,cat0_z0_a7,cat0_z0_a8,cat0_z0_a9&search[value][]=

Anyone have any idea what to look for? Any help is welcome.
Config has not changed.

**Comment by Sweepr** [comment] 2015-09-28 21:02
Maybe the API key changed? not sure what else can be wrong.

**Comment by scanno** [comment] 2015-09-28 21:05
Nope..  API key was the same. I even created a new API key and replaced the old one in the spotweb config.

**Comment by scanno** [comment] 2015-09-29 04:41
Hmmm request to add a nzb to the queue is received by sabnzbdplus.

2015-09-29 06:35:02,010::DEBUG::[interface:429] API-call from 127.0.0.1 [Mozilla/5.0 (Windows NT 6.2; WOW64; rv:26.0) Gecko/20100101 Firefox/26.0] {'nzbname': u'Formule 1 GP van Singapore Race 2015', 'output': u'text', 'apikey': u'a7f7409cbe8e550e45d60fc9ba151832', 'mode': u'addfile', 'cat': u'movies'}

But should that u be there?
Is thrre a way to get some debug info from spotweb to see the request that is send to sab?

**Comment by klara31** [comment] 2015-10-03 11:53
same issue here, same error message

**Comment by Sweepr** [comment] 2015-10-05 18:04
Wel i have seen the same before.

What i did was toggle between settings, which somehow solved this issue, i have no idea what is causing this.

But try this:

Goto preferences -> NZB handeling.

From the dropdown menu select "Call Sabnzdb trough HTTP by spotweb", click change.

Go back to preferences -> NZB handeling.

From the dropdown menu select "Run Sabnzdb trough HTTP by spotweb", click change.

Now it should be working again.

**Comment by scanno** [comment] 2015-10-05 19:15
@Sweepr 
I downgraded to sabnzbdplus 0.7.16 and the problem was gone. Just out of curiosity i upgraded again to 0.8.0. After the upgrade (and without touching any settings) the problem was back. 
So i tried what you wrote. Did not work.
Downgraded again to 0.7.16 and everything works fine.

So either there is a flaw in 0.8.0 or there is some kind of incompatability between sab and spotweb.

**Comment by Goeny** [comment] 2015-12-18 19:19
I also have a problem with sabnzbdplus 0.8 within spotweb.
When i click the SAB button (top right), the SAB panel opens up and i can see my sab information:
![screen shot 12-18-15 at 08 12 pm](https://cloud.githubusercontent.com/assets/3872395/11904958/d5385006-a5c3-11e5-9e55-02383c73e2f4.PNG)

But when i click the download to sab button, it gives me a red cross..

![screen shot 12-18-15 at 08 13 pm](https://cloud.githubusercontent.com/assets/3872395/11904983/f041d52a-a5c3-11e5-9e77-7f4819e2df23.PNG)

I noticed that sabnzbdplus 0.8 has a new setting where you can set the permissions from the web through the API.
No access - Add NZB files - API (No configuration) - Full API - Full web interface.
I tried to change that to a setting which would let me add NZB's to sab, but no luck.

My guess is there is some change in the sabnzbdplus api which doesnt work with Spotweb anymore.

**Comment by Wally73** [comment] 2015-12-18 19:22
mm no issue here with sabnzb 0.8.0Beta3

**Comment by Goeny** [comment] 2015-12-18 19:27
Can you tell me how you used your settings in both sabnzbdplus and spotweb?

I have sabnzbd set to "Full web interface"
Spotweb : Call sabnzbdplus thought HTTP by Spotweb, using the API key from sabnzb (not the nzb key)

**Comment by aroundmyroom** [comment] 2015-12-18 19:30
Same here working very very very long already here .. 

 

The best way to check why there is an issue is check your webserver’s log . 

 

There must be a reason

 



 

It downloaded this

192.168.1.67 - - [18/Dec/2015:20:22:24 +0100] "GET /spotweb/?page=getnzb&action=push-sabnzbd&messageid=xc4LZ1UNSXAyVV0Vgpb6D@spot.net

 

You call Sabnzbd through httpd by Spotweb

 



Van: Wally73 [mailto:notifications@github.com] 
Verzonden: vrijdag 18 december 2015 20:23
Aan: spotweb/spotweb <spotweb@noreply.github.com>
Onderwerp: Re: [spotweb] Spotweb and Sabnzbdplus 0.8.0 (#94)

 

mm no issue here with sabnzb 0.8.0Beta3

On Fri, Dec 18, 2015 at 8:19 PM, Goeny <notifications@github.com <mailto:notifications@github.com> > wrote:



rectly or view it on GitHub <https://github.com/spotweb/spotweb/issues/94#issuecomment-165875976> .  <https://github.com/notifications/beacon/AAPQ_H0OBFY-fd3oeKoX4DkBNRDUwwsNks5pRFSegaJpZM4GFO-2.gif>

**Comment by Goeny** [comment] 2015-12-25 18:39
Still not working.
When pushing the NZB to sabnzbd through 'the users browser", it does send the nzb correctly. however, with that setting it cannot show the queue in Spotweb itself.

As soon as i set the setting to: "Send nzb through HTTP by spotweb", it does not send the nzb to sabnzb.  It does show the server information from sabnzb.

Only message in the server log is:
[fcgid:warn] [pid 25618] [client 192.168.1.1:60617] mod_fcgid: stderr: sabnzbd push failed: http returncode: 200 / , referer: http://mydomain.org/?page=index&search[tree]=bladiebla.....

I have removed Spotweb completely (except the DB) and reinstalled.
I have removed sabnzbd completely and reinstalled.
I created another account to a server which runs sabnzbd 0.7 (no problems)

**Comment by CptChaos** [comment] 2016-01-12 10:05
From sab's wiki:
Security zones

Access to the API and the web-interface can be limited for systems outside the "safe ranges".
"Safe ranges" are IP ranges that you allow.
Supposing all systems on your local network use IP addresses like 192.168.1.24,
you would specify the safe range as "192.168.1.".
You can add a list of safe ranges.

Source: http://wiki.sabnzbd.org/introducing-0-8-0

**Comment by Goeny** [comment] 2016-01-13 18:31
@CptChaos 
I already had that set correctly.

Strange thing is,... My spotweb DOES connect to sab,. When pressing the sab button (top right in spotweb), the sabpanel opens up and shows sab information.
When i add an NZB manually, i see it in the spotweb sabpanel, I can see the download speed, i can see the freespace, etc.. Only thing not working is the "nzb push to sab".

**Comment by Smiggel** [comment] 2016-03-07 21:25
Same problem here. Workshop fine with 0.7 but fails to work with 0.8. Tried many settings and all above suggestions, but it's simply not working. :-(

**Comment by CptChaos** [comment] 2016-03-07 23:34
@Smiggel, did you try to push the NZB through the browser to Sabnzbd? I reinstalled a laptop of a friend of mine, ever since it only works through the browser, instead of Spotweb sending the NZB directly. A little more on the case would be nice, as Spotweb offers 2 methods to add an NZB to Sabnzbd. :)

**Comment by Smiggel** [comment] 2016-03-08 07:25
@CptChaos I run SABNZB and Spotweb on a NAS. So, can't really test it the way you suggest. Setup is pretty different. :-)

**Comment by Wally73** [comment] 2016-03-08 09:58
https://i.gyazo.com/1909c6f822eedb0fbee719212799b9fd.png

works fine with my sabnzb 1.0.0RC2

**Comment by Smiggel** [comment] 2016-03-08 10:28
@Wally73 Hmmm ok. Not here. Only the old version works. Maybe it's because the version of sabnzb is an older beta (5) version. Waiting for Synocommunity to update to a newer version. Hopefully that will solve the problem.

**Comment by CptChaos** [comment] 2016-03-08 10:36
@Smiggel, why would Spotweb and Sabnzbd from a NAS be any different than on a PC / VM? You can perfectly test both ways I suggest, by entering the internal IP from the NAS. So I don't understand what you mean with 'the setup is pretty different', because for the functionality this issue is about, it doesn't matter how the actual setup is, at all. Spotweb uses the API Sabnzbd provides. In Spotweb you set up the way Spotweb needs to connect to Sabnzbd. ;)

**Comment by Smiggel** [comment] 2016-03-08 10:47
@CptChaos Can't use the option "NZB through the browser to Sabnzbd" because it runs on my nas. Spotweb will not allow me to select that option.

Strange thing is though I can see the status of sabnzb in spotweb. So, the settings and the api key seems to work in spotweb. However can just nog send and NZB to the sabnzb. Same problem as @Goeny

**Comment by mesa57** [comment] 2016-03-08 11:14
Through browser is not possible, because you  do not have a browser.
But through HTTP, which is the normal API interface, should work (but only 0.7.20 is supported).

**Comment by Smiggel** [comment] 2016-03-08 11:29
@mesa57 That's why I set to @CptChaos that my setup is different. I use through http with 0.7. Just hope 0.8 will be supported soon.

**Comment by CptChaos** [comment] 2016-03-08 11:32
Through browser means: Spotweb runs soms AJAX code to send the NZB to the Sabnzbd server, through the client's browser. Not the NAS itself, even the preferences page already states that too. So I guess that's a bug in the NAS' package, I guess.

**Comment by scanno** [comment] 2016-03-08 11:36
No it is not a problem in the NAS package. 
I have this problem since I opened this and still have the problem on Ubuntu server. 

This problem is still there and not solved. Sabnzbdplus and spotweb are running on the server.

**Comment by CptChaos** [comment] 2016-03-08 11:40
I meant that the option to send the NZB through a user's browser being disabled isa bug in the Spotweb package for that NAS / maintainer. Version 0.8 of Sabnzbd is deprecated and it seems to be working again with 1.0.0 RC2, so I think it'll be working too with 1.0.0 RC4 (which is a few days old). Could you try to upgrade to either of one of those versions?

**Comment by Smiggel** [comment] 2016-03-08 11:46
@CptChaos I myself can't upgrade. Have to wait for a new package to be released by Synocommunity.

**Comment by scanno** [comment] 2016-03-08 11:49
@CptChaos I will try tonight to see if I can upgrade to 1.0.x

**Comment by mesa57** [comment] 2016-03-08 12:07
1.0.0 RCx will not be supported in spotweb. Only official final releases will be supported. If it works, than you are lucky. But we won't change spotweb based on a not released version.

**Comment by Smiggel** [comment] 2016-03-08 12:09
@mesa57 Thanks for explaining. Guess I have to be more patient. :)

**Comment by scanno** [comment] 2016-03-08 21:07
@CptChaos @Smiggel Ok installed 1.0.0 RC1 and the direct http is not working. Sending the nzb through the browser is working.

@mesa57 you are saying that as soon as sab releases 1.0.0 spotweb will support a direct API access through http?

**Comment by mesa57** [comment] 2016-03-08 21:17
Thats what you select when you use "Roep SABnzbd aan via HTTP door Spotweb".
You also have to enter an api key there.

**Comment by Smiggel** [comment] 2016-03-08 21:31
@scanno Thanks for the update. For now I guess I will be stuck on 0.7 until 1.0 is officially released.

**Comment by scanno** [comment] 2016-03-08 21:38
@mesa57 yeah "Roep SABnzbd aan via HTTP door Spotweb" is not working in 1.0.0 RC1. So i hope that will work again as soon as 1.0.0 final is released and spotweb supports te changes made in the API.

"Roep SABnzbd aan via de users' browser" is working.

**Comment by aroundmyroom** [comment] 2016-03-09 06:43
ok, no 1.0.0.RC1 for me, if that will break this api function, nothing will work here anymore .. I rely 100% on that setting.

**Comment by mesa57** [comment] 2016-03-09 15:29
Wally reports that 1.0.0 RC2 is working fine with spotweb, so you must do something wrong.

**Comment by Wally73** [comment] 2016-03-09 16:11
works fine too with sabnzb 1.0.0 RC4

**Comment by scanno** [comment] 2016-03-09 16:16
@Wally73  @mesa57 well i am using the same settings as mentioned by wally73, but with rc1 no luck (on ubuntu). Only through the browser it is working (or with 0.7.x).

**Comment by Wally73** [comment] 2016-03-09 20:22
ok i use it on windows but that shouldn't make any difference

**Comment by mesa57** [comment] 2016-03-10 08:24
No, more important are the PHP version which is used.
Also there could be a difference between IIS and the apache webserver.

**Comment by derkens** [comment] 2016-03-18 08:14
Just chiming in here now sabnzbd is official at version 1, having the same issue.
when clicking the green arrow, a red cross appears.
Here's what shows in apache's error_log:
` sabnzbd push failed: http returncode: 200 / , referer: http://htpc/spotweb/`
And this shows in sabnzbd log:
`DEBUG::[interface:458] API-call from 127.0.0.1 [Mozilla/5.0 (Windows NT 6.1; WOW64; rv:8.0) Gecko/20100101 Firefox/8.0] {'nzbname': u'Hap and Leonard S01E03 720p HDTV x264', 'output': u'text', 'apikey': u'***correctapikey***', 'mode': u'addfile', 'cat': u'tv'} 
`
system info:
Linux (archlinux)
Apache 2.4.18
Php 7.0.4

tried all the suggestions above, I can't get an nzb directly from spotweb to sabnzb. other options (watched folder, users browser etc. all working)

**Comment by Sweepr** [comment] 2016-03-18 09:22
Did you try a reboot after the update?

**Comment by scanno** [comment] 2016-03-18 09:40
@Sweepr  the official version is not working here either. Same problem since 0.8.0. Spotweb and sab running on an linux servee.

**Comment by Wally73** [comment] 2016-03-18 09:49
no issue here with spotweb with sabnzb 1.0.0 final

make sure settings are correct and make sure the nzb download rights in
spotweb are good

**Comment by scanno** [comment] 2016-03-18 09:51
@Wally73 checked them 1000 times already since last year

**Comment by Smiggel** [comment] 2016-03-18 09:51
Just upgraded and runs perfectly now. Only had to change the port number (runs on 8089 in the test version) and the api key. I can now manually add items from spotweb. Run my installation on a Synology NAS with DSM 6.

**Comment by scanno** [comment] 2016-03-18 10:05
Don't know what i am doing wrong.
List of local network ranges is set to my internal network range and also localhost is added.
Regenerated the api key
But still cannot get spotweb to access sab directly. 

Using the users browser is working

**Comment by derkens** [comment] 2016-03-18 12:41
In the sabnzbd log you see the api call is getting through, it seems it is just missing a piece?
the nzbfile / filename part?

**Comment by Sweepr** [comment] 2016-03-18 13:36
Can you catch the NZB file from the watch folder of SabNZBd and then compare this file with a manually downloaded NZB ?

**Comment by derkens** [comment] 2016-03-18 14:26
manually download from spotweb? or from another indexer?

**Comment by Sweepr** [comment] 2016-03-18 14:48
Yes from spotweb

**Comment by derkens** [comment] 2016-03-18 14:50
So I went ahead and tried both,
manual download from spotweb and retrieved from watchfolder nzb files are exactly the same. (md5sum)
manual download from nzbindex.nl and retrieved from watchfolder, nzb files are exactly the same, not in md5sum, but in size and i ran a diff on the files.

**Comment by mesa57** [comment] 2016-03-19 11:56
I cannot update to 1.0.0 on my debian install because the package is not available there (stable version). On windows however it works fine.
The message 
```
sabnzbd push failed: http returncode: 200
```
Means that the NZB has succesfully send to sabnzbd. (The word failed is confusing, but code 200 means OK).
However, it looks that spotweb cannot determine the status of sabnzbd (in Ubuntu).
But I am not able to test (debian) and therefore surely not able to fix this.
As of now, this problems is in the state 'not reproducable' for me.

**Comment by dterweij** [comment] 2016-03-22 11:40
Installed 1.0.0 and i have the same problem. spotweb red cross.
CentOS 6/PHP7
Going back to the old version :( :(

**Comment by mesa57** [comment] 2016-03-22 12:55
Can both of you confirm that sabnzbd has indeed received the NZB (but spotweb not knowing of it) ?

**Comment by derkens** [comment] 2016-03-22 13:12
sabnzbd is not receiving the nzb file.

**Comment by Molleke** [comment] 2016-03-22 13:53
I have also the same issue when I updated to Sabnzbd 1.0.0. Also sabnzbd is not receiving the nzb file.

**Comment by mesa57** [comment] 2016-03-22 14:13
As per this date there is still no official release of sabnzbd 1.0.0 for Linux.
So please revert to 7.0.20

**Comment by Wally73** [comment] 2016-03-22 14:21
https://github.com/sabnzbd/sabnzbd/releases/tag/1.0.0

there is you only have to run it from source

**Comment by derkens** [comment] 2016-03-22 19:53
My archlinux aur package is built from an official 1.0.0.tar.gz

**Comment by mesa57** [comment] 2016-03-22 23:30
I spent this evening installing centos 7. I even not have got phpmyadmin to work. Somehow distributions are getting depency's wrong. I am not suprised any more that intergration with sabnzbd does not work in centos (7).

**Comment by scanno** [comment] 2016-03-23 05:46
@mesa58 the Ubuntu repository mentioned here http://wiki.sabnzbd.org/install-ubuntu-repo also has the 1.0.0 release version.

**Comment by dterweij** [comment] 2016-03-23 11:38
CentOS is fine mesa57. Use remi repository to install  more recent and better packages like phpmyadmin/php7 etc etc. sabnzbd runs fine, all my other tools that sends nzb to sabnzbd are fine (like sickbeard). Just spotweb is doing nothing anymore.

**Comment by frits23946** [comment] 2016-03-23 18:14
wens geen mails van jullie te ondvangen.

2016-03-23 12:38 GMT+01:00 Danny Terweij <notifications@github.com>:

**Comment by Smiggel** [comment] 2016-03-23 18:16
@frits23946 moet je je niet hierop abonneren! Kortom uitschrijven voor deze threat.

**Comment by mesa57** [comment] 2016-03-26 16:19
After spending some days getting my debian jessie upgrade working again, I was able to install sabnzbdplus 1.0.0 under debian/jessie.
Spotweb recognizes sabnzbdplus and pushes the nzb correctly.
So we no have a report on spotweb working with sabnzbd together with spotweb in windows as well as in linux / debian and prob. also ubuntu.
Seems to me like a specific Centos issue.

**Comment by scanno** [comment] 2016-03-26 16:23
@mesa57 I am running Ubuntu and have thus problem since I have reported it.

**Comment by Wally73** [comment] 2016-03-26 16:33
if it works on debian it works on ubuntu too
ubuntu repro http://forums.sabnzbd.org/viewtopic.php?f=16&t=387

and for debian its the same repro but you have to change some stuff
http://forums.sabnzbd.org/viewtopic.php?f=16&t=9844

**Comment by mesa57** [comment] 2016-03-26 16:37
I even took it from the Ubunto repo without changing anything.

**Comment by Wally73** [comment] 2016-03-26 16:40
that's nice @mesa57 that is only what i've read i have my sab running on my
win2008R2 but if its needed in can install it tomorrow or so on my debien
Jessie to test :p

**Comment by scanno** [comment] 2016-03-26 16:54
@mesa57 I have been using that repo since day one. Must be some dependency somewhere then

**Comment by mesa57** [comment] 2016-03-26 17:13
Maybe you can determine the http returncode when spotweb pushed the nzb to sabnzbd ?

**Comment by scanno** [comment] 2016-03-26 20:32
In the apache2 error log i see sabnzbd push failed: `http returncode: 200`
In the apache2 access log i see:
`GET /spotweb/?page=getnzb&action=push-sabnzbd&messageid=<removed>@spot.net&apikey=<removed> HTTP/1.1" 200 522 "http://192.168.xxx.yyy/spotweb/?page=index&search[tree]=cat0_z2&search[value][]=" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/48.0.2564.116 Chrome/48.0.2564.116 Safari/537.36"`

In the sabnzbd log i see
`API-call from 192.168.xxx.yyy [Mozilla/5.0 (Windows NT 6.1; WOW64; rv:8.0) Gecko/20100101 Firefox/8.0] {'nzbname': u'Miscellaneous Magazines 01', 'output': u'text', 'apikey': u'<removed>', 'mode': u'addfile', 'cat': u'books'}
`
But the result is a red cross and no file added in sab.

**Comment by mesa57** [comment] 2016-03-26 20:51
My apache2 access log looks the same. 
But sabnzbd reports : 
```
 2016-03-26 21:48:22,281::INFO::[__init__:646] <removed>.nzb
```
I must admit, I don't start sabnzbd as a daemon, but as command (sabnzbdplus) under root.

**Comment by scanno** [comment] 2016-03-26 20:54
I am running sabnzbd as a daemon.

**Comment by scanno** [comment] 2016-03-26 20:59
@mesa57 found the problem.... Switched back to English as userinterface language.....
Now it is working

**Comment by mesa57** [comment] 2016-03-26 21:01
I also saw that search parms where included in the request.
Could you try a request without searching first ?
Because that leads to a red cross with me :smile:

**Comment by scanno** [comment] 2016-03-26 21:07
I cannot reproduce that. In dutch all request fail (red cross). In English all request work.

**Comment by scanno** [comment] 2016-03-26 21:49
@mesa57 if you set the spotweb gui language to dutch, does the sabnabd push also fail on your setup? Can you reproduce the problem ?

**Comment by mesa57** [comment] 2016-03-26 23:44
Got into another issue, it doesn't change the language.

**Comment by mesa57** [comment] 2016-03-27 12:13
Ok, installing locale nl.NL-UTF-8 helpt, I am now able to select 'nederlands'.
The error is reproducable, when Nederlands is selected, a red cross appears.
If I look at the message sabnzbd returns is says : 
```
error: expect one parameter
```
Looks like locale NL-UTF8 confuses sabnzbd.

**Comment by mesa57** [comment] 2016-03-28 10:16
Ok, I have a workaround.
In class Services_NzbHandler_Pushsabnzbd after line 27 add : 
```
	public function processNzb($fullspot, $nzblist)
	{
		setlocale(LC_ALL,'en_US.UTF-8');
```
And spotweb works with sabnzbd 1.0.0 also with language 'nederlands'.

**Comment by mesa57** [comment] 2016-04-17 09:15
Solved in last commit, closing issue.

**Closed by mesa57** 2016-04-17 09:15 UTC
Labels: Deployed, enhancement
