### ISSUE TITLE
Marking every thing as read does not reset the filter counters

### ISSUE THREAD

**Issue by Caton371** [spotweb/spotweb#575] opened 2020-08-01 19:30 UTC
As the subject says, if you click the "Mark everything as read" button, the filter counters are not reset. They still indicate there are new spots but there are non anymore as all spots have been marked read.

**Comment by Sweepr** [comment] 2020-08-01 19:39
@Caton371 I have tried to reproduce this but failed, when clicking the mark all as read button alll new spots gets reset in the filter list and marked as read like designed.

Can you try another PC?
Which branch do you use and which platform?

**Comment by Caton371** [comment] 2020-08-01 19:48
I do not have another PC to try
I used the master branch, downloaded the package this week.
The platform is openSUSE Leap 15.2 with updates
I am using PostgreSQL as a backend.

**Comment by Caton371** [comment] 2020-08-01 19:53
![Screenshot_20200801_215053](https://user-images.githubusercontent.com/23633300/89109434-64f59400-d441-11ea-9b59-78013f15b367.png)

**Comment by Caton371** [comment] 2020-08-01 19:54
Check the screenshot. Books shows a counter of 16 new spots but no spots in the list are in bold because they have been marked read.

**Comment by Caton371** [comment] 2020-08-02 08:38
With MariaDB as the back-end database, the issue is gone.

**Comment by Sweepr** [comment] 2020-08-02 18:24
Ok, so what you say is with PostgreSQL this function does not work properly?

Can you reproduce this again with PostgreSQL?

**Comment by mesa57** [comment] 2020-08-02 20:17
Maybe I can try to reproduce this tomorrow.

**Comment by mesa57** [comment] 2020-08-03 10:44
Works fine with PostgreSQL and php56 : 
![afbeelding](https://user-images.githubusercontent.com/6350469/89174926-fae70700-d586-11ea-9eb8-5b94cc2bfd0d.png)

**Comment by mesa57** [comment] 2020-08-03 10:46
Btw. there is a difference between the indication of new spots in the filterlist and overview.
I thought the overview new spots is session based.

**Comment by Caton371** [comment] 2020-08-03 17:29
Hello,
I did a new install of spotweb, using the master downloaded on 30 July, PostgreSQL 12, PHP 7.4.6
The only configuration change I made was to not download the comments, because that takes hours.
After downloading the spots, reports and black/white list, I hit the "Mark everything as read" button. Filter counters were correctly reset.
Next, I retrieved new spots and, when that was finished, I hit the "Mark everything as read" button. the filter counters were not reset.

**Comment by Caton371** [comment] 2020-08-03 19:21
If  you wait a while, and then mark everything as read the filters are reset properly. Strange behavior.

**Comment by Sweepr** [comment] 2020-08-09 07:44
> 
> 
> **_If you wait a while_**, and then mark everything as read the filters are reset properly. Strange behavior.

How much is a while, maybe this can give a point of reference so we can find the possible root cause.

**Comment by Caton371** [comment] 2020-08-09 10:05
I think that was about an hour later.

**Comment by Sweepr** [comment] 2020-08-17 09:58
Sorry, we cannot reproduce this own our test environments, have to close this issue.

**Closed by Sweepr** 2020-08-17 09:58 UTC
Labels: Not reproducable
