### ISSUE TITLE
API Issues --extra content at the end of the document--

### ISSUE THREAD

**Issue by dbgunsolus** [spotweb/spotweb#93] opened 2015-09-25 20:13 UTC
Everything is working fine except when request with the api. /api?t=c returns successfully. however when I am requesting something else, it is returning this. 
This page contains the following errors
error on line 2 at column 1: Extra content at the end of the document.
Below is a rendering of the page up to the first error.

I am not sure what is causing this.

**Comment by Sweepr** [comment] 2015-09-26 16:45
Not seeing any image's, please check.

**Comment by dbgunsolus** [comment] 2015-09-26 16:49
Would you like a screen shot?

**Comment by Sweepr** [comment] 2015-09-26 16:51
Everything is working fine except when request with the api. /api?t=c returns successfully. however when I am requesting something else, it is returning this.  <- What is it returning?
This page contains the following errors 
error on line 2 at column 1: Extra content at the end of the document.
Below is a rendering of the page up to the first error. <- below is a rendering?

**Comment by dbgunsolus** [comment] 2015-09-26 16:53
It is returning this:

This page contains the following errors
error on line 2 at column 1: Extra content at the end of the document.
Below is a rendering of the page up to the first error.

But there is no image or anything after it

**Comment by mesa57** [comment] 2016-03-16 10:59
Can this issue be closed ?

**Comment by dbgunsolus** [comment] 2016-03-16 11:28
It is still occuring but I switched to another indexer because it was never
resolved.

**Comment by mesa57** [comment] 2016-03-21 21:17
Closing issue.

**Comment by derkens** [comment] 2016-03-23 10:30
sorry to comment on a closed issue,
I have the same problem, In my case this is caused by two php warnings at the start of the page result.
In my case this is `PHP Warning:  strpos(): Empty needle in /srv/http/spotweb/lib/dbeng/dbfts_mysql.php on line 185`
If turn off php warnings, the xml shows without problems.

**Comment by mesa57** [comment] 2016-04-03 14:24
Please report : 
- OS you're running 
- 64/32 bits
- PHP version
- DB system used and version
- The *exact* api string which was used when getting this problem (you may leave out the apikey)

**Comment by derkens** [comment] 2016-04-04 04:44
- archlinux
- 64 bits
- php 7.0.5
- mariadb 10.1.13
- apistring (as cp uses): `/api?imdbid=3659388&apikey=apikey&t=movie&extended=1`

**Comment by mesa57** [comment] 2016-04-04 08:30
Thanks, I will try to reproduce onder debian 8  (64 bits) / mysql 5.6 / php 5.6

**Comment by guyspronck** [comment] 2016-04-04 13:57
I can add to this issue that it seems to be a problem only when using PHP 7+, I was experiencing the exact issue described and switched from php 7 to php 5.5 and the issue disappeared.

So workaround for this issue is: use php 5.5/.6

**Comment by mesa57** [comment] 2016-04-04 14:06
Maybe in the php 7.0.5 installation the show PHP warnings setting is default 'on' ?.

**Comment by derkens** [comment] 2016-04-04 14:20
I've tried setting it off in php.ini and in .htaccess. The only way I could get the warnings not to show up was to comment out lines 2 and 3 in index.php.
`error_reporting(2147483647);`
`ini_set('display_errors', 1);`
Along with the settings in php.ini of course.
Default php.ini from my install says: `error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT`
For testing I've set this to `error_reporting =  E_DEPRECATED`

**Comment by mesa57** [comment] 2016-04-04 14:56
Could you try error_reporting(E_ALL & ~E_WARNING); in index.php ?
Btw. are you using the latest spotweb commit, as imdb access has been changed (and you should not get those empty warnings).

**Comment by derkens** [comment] 2016-04-04 15:03
Git pull is up to date.
With `error_reporting(E_ALL & ~E_WARNING);` everything is fine, it also blocks the warning from getting in the apache error_log, so everything is fixed ;)

**Comment by mesa57** [comment] 2016-04-04 15:06
Not entirely. I could not reproduce you're problem as I get a list of the requested movie.
Was a list returned in you're case ?

**Comment by derkens** [comment] 2016-04-04 15:16
you did see the ;) in my previous post?
I now get a full xml with movie list. Last time I removed the error_reporting, cps downloaded a movie from spotweb. I'm sure it will again.
On the other hand, spotweb will not show any warnings from now on...

**Comment by mesa57** [comment] 2016-04-04 15:40
I will include this change in the next commit as a php 7 compatibilty issue solved.

**Comment by derkens** [comment] 2016-04-04 16:22
Agreed, enough time spent on this.
Optionally, you could remove the error_reporting completely and let it depend on the users system?
Override is then possible through the .htaccess. For the api to work, it has to be edited anyway.

**Comment by mesa57** [comment] 2016-04-04 17:59
I think it is important that errors get reported on this issuelist, specialy with the transition to php 7.

**Comment by derkens** [comment] 2016-04-05 06:10
OK, thanks for your time!

**Comment by mesa57** [comment] 2016-04-05 07:29
I just have a confirmation from somebody on the spot-net forum with the same problem is also using PHP 7.0.5. So it looks like a php version initiated problem.

**Comment by derkens** [comment] 2016-04-05 09:05
Does he get the same warning? (Empty needle...)

**Comment by dsadsdadsadsadsds** [comment] 2016-04-14 19:29
Do we know exactly what search query is generated by the system? It mostly seems invalid as it seems to contain an operator (eg: + or -) and after that a wildcard. eg, it tries to search for +* or something like that which is illegal.

To workaround this, i think an additional check might need to be added just before the strpos() on line 158, eg something like this:

```php
// If the search term only contains an operator which is stripped, lets continue to the next term
if (strlen($strippedTerm) < 1) {
   continue;
}
```

**Comment by mesa57** [comment] 2016-04-14 19:57
Until I get hold of an official php 7 version, I cannot test this.
In php 5.6 no warnings are produced.

**Comment by derkens** [comment] 2016-04-15 06:11
Since I have a reproducible warning, can I help?

**Comment by mesa57** [comment] 2016-04-15 08:02
We always are in search of testers :smile:

**Comment by derkens** [comment] 2016-04-15 09:33
Ok, so this is line 185:
` if (strpos('*', substr($strippedTerm, -1)) !== false) {
                                        $searchMode = 'match-boolean';`
what should I replace it with?
e.g. please hold my hand..... :smile:

**Comment by mesa57** [comment] 2016-04-15 09:48
moment ....

**Comment by mesa57** [comment] 2016-04-15 10:23
Please pull 
index.php 
lib\dbeng\dbfts_mysql.php

from the last commit of my own repository  https://github.com/mesa57/spotweb-master

**Comment by derkens** [comment] 2016-04-15 18:54
Ok, just tried, warnings are gone.

**Comment by mesa57** [comment] 2016-04-15 19:05
Nice, I'll keep the change then as is.

**Comment by mesa57** [comment] 2016-04-17 09:16
Solved in last commit, closing issue.

**Closed by mesa57** 2016-04-17 09:16 UTC
Labels: Deployed, PHP 7 inompatibility

**Comment by Killerman1991** [comment] 2017-09-03 17:18
Hello, 

I have still this problem. I have downloaded the latest spotweb version from mesa57, but when i open the spotweb link with my api key i get the following message:

This page contains the following errors:

error on line 2 at column 1: Document is empty
Below is a rendering of the page up to the first error.

I have added warning to my php.index, and restart my nas server, but this doesn't work.

**Comment by Sweepr** [comment] 2017-09-05 18:22
I don't see any rendering of the page?

Are you 100% sure you have the latest version installed and running?

**Comment by Killerman1991** [comment] 2017-09-05 18:26
What page do you mean?

**Comment by Sweepr** [comment] 2017-09-05 18:29
Because you said: 

error on line 2 at column 1: Document is empty
Below is a rendering of the page up to the first error. <-- but i don't see that

**Comment by Killerman1991** [comment] 2017-09-05 18:50
That is correct i don't see any rendering.

This is what i get:

[IMG]https://www.mupload.nl/img/wndbkd5xa411v.jpg[/img]

**Comment by Sweepr** [comment] 2017-09-05 18:57
So you added this to index.php?

error_reporting(E_ALL & ~E_WARNING);

**Comment by Killerman1991** [comment] 2017-09-05 19:11
I have added warning in this sentence.

error_reporting = E_ALL & ~E_NOTICE & ~E_WARNING & ~E_STRICT & ~E_DEPRECATED 
display_startup_errors = Off

**Comment by Sweepr** [comment] 2017-09-05 19:18
For the index.php the syntax should be:

error_reporting(E_ALL & ~E_WARNING);
ini_set('display_errors', 1);

**Comment by Killerman1991** [comment] 2017-09-05 19:22
display_startup_errors = Off 

Is another sentence. So these are two sentence.
Must i delete the second sentence with the text:
display_startup_errors = Off

**Comment by Sweepr** [comment] 2017-09-05 19:29
Yes, there's a difference in code between index.php and the actuall php.ini.

This: (which you added in the index.php)
error_reporting = E_ALL & ~E_NOTICE & ~E_WARNING & ~E_STRICT & ~E_DEPRECATED
display_startup_errors = Off

Should be:
error_reporting(E_ALL & ~E_WARNING);
ini_set('display_errors', 0);

There a difference between setting in php.ini and index.php

For reference see: 

http://php.net/manual/en/function.error-reporting.php

https://stackoverflow.com/questions/15949304/turn-off-display-error-php-ini

**Comment by Killerman1991** [comment] 2017-09-05 19:47
What i have added was in the php.ini

**Comment by Sweepr** [comment] 2017-09-05 19:55
Please see if adding:

error_reporting(E_ALL & ~E_WARNING);
ini_set('display_errors', 0); 

To the index.php, restart the Apache (or whatever webservice you have running) and see if that fixes the problem.

**Comment by Killerman1991** [comment] 2017-09-05 20:06
This is a synology server and i have searched in WinSCP for the index.php file, and this file don't excist.

**Comment by Sweepr** [comment] 2017-09-05 20:08
https://github.com/spotweb/spotweb

Should be in the root of your spotweb folder.

**Comment by Killerman1991** [comment] 2017-09-05 20:22
That is correct, i have found the file. It is strange that WinSCP can't find the file.
I have change the following text:

error_reporting(2147483647);
ini_set('display_errors', 1);

to:

error_reporting(E_ALL & ~E_WARNING);
ini_set('display_errors', 0);

When i open my link i see the following:

This XML file does not appear to have any style information associated with it. The document tree is shown below.

And then a lot of text. I think this is good.
Thanx for your help. 👍 :)
