### ISSUE TITLE
Fatal error:  Uncaught Error: [] operator not supported for strings in PHP 7.1.0

### ISSUE THREAD

**Issue by dterweij** [spotweb/spotweb#243] opened 2016-12-07 03:06 UTC
Updated my system to PHP 7.1.0 and got this after a git pull to have most recent code:

```
[danny@server03 spotweb]$ php retrieve.php
Removing Spot information which is beyond retention period,, done
Last retrieve at Sun 04 Dec 2016 11:12:16 PM UTC
Retrieving new Spots from server xxxxxxxxxxx...
Appr. Message count:    2969126
First message number:   2
Last message number:    2969128
Current article number: 2968442

Retrieving 2968442 till 2969129PHP Fatal error:  Uncaught Error: [] operator not supported for strings in /home/danny/public_html/spotweb/lib/services/Format/Services_Format_Parsing.php:140
Stack trace:
#0 /home/danny/public_html/spotweb/lib/services/Retriever/Services_Retriever_Spots.php(492): Services_Format_Parsing->parseFull('<Spotnet><Posti...')
#1 /home/danny/public_html/spotweb/lib/services/Retriever/Services_Retriever_Base.php(227): Services_Retriever_Spots->process(Array, '2968442', 2969129, 1481079369.404)
#2 /home/danny/public_html/spotweb/lib/services/Retriever/Services_Retriever_Base.php(319): Services_Retriever_Base->loopTillEnd(2969129, '5000')
#3 /home/danny/public_html/spotweb/retrieve.php(145): Services_Retriever_Base->perform()
#4 {main}
  thrown in /home/danny/public_html/spotweb/lib/services/Format/Services_Format_Parsing.php on line 140
[danny@server03 spotweb]$
```

```
[danny@server03 spotweb]$ php -v
PHP 7.1.0 (cli) (built: Dec  1 2016 08:23:35) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.1.0-dev, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.1.0, Copyright (c) 1999-2016, by Zend Technologies
[danny@server03 spotweb]$

```

**Comment by mesa57** [comment] 2016-12-07 10:10
Do you get this error for every spot ?


________________________________
Van: Danny Terweij <notifications@github.com>
Verzonden: woensdag 7 december 2016 04:06
Aan: spotweb/spotweb
Onderwerp: [spotweb/spotweb] Fatal error: Uncaught Error: [] operator not supported for strings in PHP 7.1.0 (#243)


Updated my system to PHP 7.1.0 and got this after a git pull to have most recent code:

[danny@server03 spotweb]$ php retrieve.php
Removing Spot information which is beyond retention period,, done
Last retrieve at Sun 04 Dec 2016 11:12:16 PM UTC
Retrieving new Spots from server xxxxxxxxxxx...
Appr. Message count:    2969126
First message number:   2
Last message number:    2969128
Current article number: 2968442

Retrieving 2968442 till 2969129PHP Fatal error:  Uncaught Error: [] operator not supported for strings in /home/danny/public_html/spotweb/lib/services/Format/Services_Format_Parsing.php:140
Stack trace:
#0 /home/danny/public_html/spotweb/lib/services/Retriever/Services_Retriever_Spots.php(492): Services_Format_Parsing->parseFull('<Spotnet><Posti...')
#1 /home/danny/public_html/spotweb/lib/services/Retriever/Services_Retriever_Base.php(227): Services_Retriever_Spots->process(Array, '2968442', 2969129, 1481079369.404)
#2 /home/danny/public_html/spotweb/lib/services/Retriever/Services_Retriever_Base.php(319): Services_Retriever_Base->loopTillEnd(2969129, '5000')
#3 /home/danny/public_html/spotweb/retrieve.php(145): Services_Retriever_Base->perform()
#4 {main}
  thrown in /home/danny/public_html/spotweb/lib/services/Format/Services_Format_Parsing.php on line 140
[danny@server03 spotweb]$


[danny@server03 spotweb]$ php -v
PHP 7.1.0 (cli) (built: Dec  1 2016 08:23:35) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.1.0-dev, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.1.0, Copyright (c) 1999-2016, by Zend Technologies
[danny@server03 spotweb]$



-

**Comment by dterweij** [comment] 2016-12-07 14:32
It is PHP Design.
Changed in PHP 7.1.0:
 ```
The empty index operator (e.g. $str[] = $x) is not supported for strings
 anymore, and throws a fatal error instead of silently converting to array.
 ```

So that means that you need to say that it is an array $myString = array(); 
Prior to PHP 7.1.0 , PHP converted a [] to array() silently, and now not anymore.

The GUI is showed in browser without new spots. Dont know if there are more places in the code with this kind of error.

**Comment by mesa57** [comment] 2016-12-07 15:42
Yes, there are numerous places were an [] is used.

**Comment by GeoffreyDijkstra** [comment] 2016-12-08 07:52
@mesa57 It's not an issue with [] we can still use that, but you have to initialize it now. So:
`$var1[] = $x` results in error when not initialized.
`$var1 = []; $var1[] = $x` does not :smile:
It seems they become a little more strict.

**Comment by Sweepr** [comment] 2016-12-08 08:22
Well, sure, but if we change this way, would it be backwards compatible with older versions of PHP?

Nobody ever said spotweb is designed for PHP 7, so i do not understand why everyone is trying to run spotweb on PHP 7, and start complaining about issue's.

This way its almost impossible to mantain a stable version..

**Comment by GeoffreyDijkstra** [comment] 2016-12-08 08:25
@Sweepr Yes this is backwards compatible to 5.4. It's even not nice/good practice to code without initializing. But PHP accepted it and fixed it for you. So now we need to fix it ourselfs :grin:

**Comment by Sweepr** [comment] 2016-12-08 17:52
@GeoffreyDijkstra 

I revised that file, could you or @dterweij check if this is correct?

http://pastebin.com/Hy77Q6Ww

**Comment by GeoffreyDijkstra** [comment] 2016-12-09 08:08
@Sweepr Well, not really :smile: 
I'll make a PR and test it on PHP 7.1.

**Comment by dterweij** [comment] 2016-12-09 12:39
That does not work well :) I don't paste all the errors because its tooo much :)

PHP Warning:  Invalid argument supplied for foreach() in Services_Format_Parsing.php on line 190

A lot of these:
PHP Notice:  A non well formed numeric value encountered
PHP Warning:  Illegal string offset ....

**Comment by GeoffreyDijkstra** [comment] 2016-12-09 12:43
@dterweij I wanted to keep my previous to @Sweepr nice, but yes this introduces new issues :smile: 
Sorry @Sweepr :wink:

**Comment by Sweepr** [comment] 2016-12-09 13:22
Ok, strange, i did just like @GeoffreyDijkstra  suggested,

$var1[] = $x results in error when not initialized.
$var1 = []; $var1[] = $x does not

So i changed the lines containing like:
$var1[] = $x 
into 
$var1 = []; $var1[] = $x

This apperantly does not do the trick.

**Comment by GeoffreyDijkstra** [comment] 2016-12-09 21:11
@Sweepr @dterweij Just dived into the code but it's fine as is... Can run retriever without problems on PHP 5.6, PHP 7.0 and PHP 7.1. So I'm open to suggestions.

**Comment by GeoffreyDijkstra** [comment] 2016-12-09 21:12
I'll see if I can find something weird, but for now it's just doing what it should do.

**Comment by GeoffreyDijkstra** [comment] 2016-12-09 21:19
@dterweij I've cleaned up the file a bit in a [hotfix/php71-support](https://github.com/spotweb/spotweb/tree/hotfix/php71-support) branch. If you can checkout this branch and run your `retriever.php` again, see if it works or crashes. If it crashes, please send another stacktrace.

**Comment by dterweij** [comment] 2016-12-11 03:16
'''danny@server03 spotweb]$ git branch
* hotfix/php71-support
  master
[danny@server03 spotweb]$ php retrieve.php --force
Removing Spot information which is beyond retention period,, done
Last retrieve at Sun 04 Dec 2016 11:12:16 PM UTC
Retrieving new Spots from server Xxxxxxx...
Appr. Message count:    2970389
First message number:   2
Last message number:    2970391
Current article number: 2968442

Retrieving 2968442 till 2970392PHP Fatal error:  Uncaught Error: [] operator not supported for strings in /home/danny/public_html/spotweb/lib/services/Format/Services_Format_Parsing.php:158
Stack trace:
#0 /home/danny/public_html/spotweb/lib/services/Retriever/Services_Retriever_Spots.php(492): Services_Format_Parsing->parseFull('<Spotnet><Posti...')
#1 /home/danny/public_html/spotweb/lib/services/Retriever/Services_Retriever_Base.php(227): Services_Retriever_Spots->process(Array, '2968442', 2970392, 1481425981.5017)
#2 /home/danny/public_html/spotweb/lib/services/Retriever/Services_Retriever_Base.php(319): Services_Retriever_Base->loopTillEnd(2970392, '5000')
#3 /home/danny/public_html/spotweb/retrieve.php(146): Services_Retriever_Base->perform()
#4 {main}
  thrown in /home/danny/public_html/spotweb/lib/services/Format/Services_Format_Parsing.php on line 158
[danny@server03 spotweb]$'''

**Comment by dterweij** [comment] 2016-12-11 21:00
@GeoffreyDijkstra Here the new report (I did stopped it because it looks like running endless)

```
[danny@server03 spotweb]$ php retrieve.php
Removing Spot information which is beyond retention period,, done
Last retrieve at Sun 04 Dec 2016 11:12:16 PM UTC
Retrieving new Spots from server xxxxxxxxx...
Appr. Message count:    2980133
First message number:   2
Last message number:    2980135
Current article number: 2968442

Retrieving 2968442 till 2973443PHP Notice:  A non well formed numeric value encountered in /home/danny/public_html/spotweb/lib/services/Retriever/Services_Retriever_Spots.php on line 103
PHP Warning:  Illegal string offset 'exponent' in /home/danny/public_html/spotweb/lib/services/Nntp/Services_Nntp_SpotReading.php on line 38
PHP Warning:  Illegal string offset 'modulo' in /home/danny/public_html/spotweb/lib/services/Nntp/Services_Nntp_SpotReading.php on line 39
PHP Warning:  Illegal string offset 'modulo' in /home/danny/public_html/spotweb/lib/services/Signing/Services_Signing_Openssl.php on line 25
PHP Warning:  Illegal string offset 'exponent' in /home/danny/public_html/spotweb/lib/services/Signing/Services_Signing_Openssl.php on line 25
PHP Warning:  Illegal string offset 'modulo' in /home/danny/public_html/spotweb/lib/services/Signing/Services_Signing_Openssl.php on line 30
PHP Warning:  Illegal string offset 'exponent' in /home/danny/public_html/spotweb/lib/services/Signing/Services_Signing_Openssl.php on line 31
PHP Warning:  Illegal string offset 'modulo' in /home/danny/public_html/spotweb/lib/services/Signing/Services_Signing_Openssl.php on line 25
PHP Warning:  Illegal string offset 'exponent' in /home/danny/public_html/spotweb/lib/services/Signing/Services_Signing_Openssl.php on line 25
PHP Warning:  Illegal string offset 'modulo' in /home/danny/public_html/spotweb/lib/services/Signing/Services_Signing_Openssl.php on line 30
PHP Warning:  Illegal string offset 'exponent' in /home/danny/public_html/spotweb/lib/services/Signing/Services_Signing_Openssl.php on line 31
```

Seems the array error is solved.

**Comment by GeoffreyDijkstra** [comment] 2016-12-12 07:14
Ok that's good to know, strange you have so many problems. Can you run `php -v` on your command line and send me the output? And please also send me your php.ini file. Maybe then I can locally reproduce.

**Comment by dterweij** [comment] 2016-12-12 15:14
Here the info as requested: 

[](http://pastebin.com/aQATRF0f)

Short summary:  CentOS 6 64 bit - EPEL & REMI repository

**Comment by GeoffreyDijkstra** [comment] 2016-12-12 20:57
@dterweij Thx, no time take a deeper look today. But I already noticed you use extremely high settings for input en execution time. Just out of curiosity whats the reason for that?

**Comment by dterweij** [comment] 2016-12-12 23:06
The reason is running a minecraft pocketmine server (that is PHP based, search for it at github) and I dont like standard limits :) I realy hate when I get a limit on shared hosting platforms.
For example, uploading 500 photo's to a gallery at a Wordpress site sucks :)
I am running my own Dell R300 19inch 1U rackserver at home. Running linux since RedHat 1.0 came out :)

**Comment by Sweepr** [comment] 2016-12-13 05:45
@dterweij Yikes, but that's around 5 hours of input and exec time, let alone the memory limit of 1024?

That's insane,.

**Comment by dterweij** [comment] 2016-12-13 20:06
The pocketmine server uses that much (every github clone).. But lets stay on topic :) Lets chat somewhere else about the high settings 🎱 :-)

Want to know if someone else also tried PHP7.1 and got such or other errors, or am I the first and only one yet :)

**Comment by GeoffreyDijkstra** [comment] 2016-12-13 20:19
@dterweij Well I'm running it specially for you and it works out of the box, no errors at all... Before that I ran PHP 7.0 which also worked fine, so that's why I said that it is kinda weird you got so many errors because I got none...

I'm running Ubuntu 16.04 with PHP 7.1 from the Ondrej Sury Repository. Maybe try Ubuntu? 😁

**Comment by dterweij** [comment] 2016-12-14 16:14
Ok then compare some versions if there is a difference:

```
php-kolab-net-ldap3-1.0.3-1.el6.remi.noarch
php-gmp-7.1.0-1.el6.remi.x86_64
php-recode-7.1.0-1.el6.remi.x86_64
php-pear-DB-1.9.2-1.el6.remi.noarch
php-pdo-7.1.0-1.el6.remi.x86_64
php-snmp-7.1.0-1.el6.remi.x86_64
php-symfony-yaml-2.8.15-1.el6.remi.noarch
php-process-7.1.0-1.el6.remi.x86_64
php-soap-7.1.0-1.el6.remi.x86_64
php-pear-Net-Socket-1.0.14-1.el6.remi.noarch
php-pear-crypt-gpg-1.4.3-1.el6.remi.noarch
php-pspell-7.1.0-1.el6.remi.x86_64
php-pecl-weakref-0.3.3-1.el6.remi.7.1.x86_64
php-wikimedia-avro-1.7.7-1.el6.remi.noarch
php-fpm-7.1.0-1.el6.remi.x86_64
php-pear-Net-LDAP2-2.2.0-1.el6.remi.noarch
php-pear-Net-Sieve-1.3.4-4.el6.remi.noarch
php-intl-7.1.0-1.el6.remi.x86_64
php-json-7.1.0-1.el6.remi.x86_64
php-fedora-autoloader-0.2.1-2.el6.remi.noarch
php-pear-Mail-Mime-1.10.0-1.el6.remi.noarch
php-pecl-zip-1.13.5-2.el6.remi.7.1.x86_64
php-symfony-common-2.8.15-1.el6.remi.noarch
php-cli-7.1.0-1.el6.remi.x86_64
php-tcpdf-6.2.12-1.el6.remi.noarch
php-php-gettext-1.0.12-1.el6.remi.noarch
php-pear-Auth-SASL-1.0.6-1.el6.remi.noarch
php-udan11-sql-parser-3.4.14-1.el6.remi.noarch
php-pecl-yaml-2.0.0-2.el6.remi.7.1.x86_64
php-phpseclib-2.0.4-1.el6.remi.noarch
php-opcache-7.1.0-1.el6.remi.x86_64
php-bcmath-7.1.0-1.el6.remi.x86_64
php-pear-Net-SMTP-1.7.2-1.el6.remi.noarch
php-imap-7.1.0-1.el6.remi.x86_64
php-pecl-pthreads-3.1.7-0.4.20161111git959ab0f.el6.remi.7.1.x86_64
php-pear-1.10.1-8.el6.remi.noarch
php-common-7.1.0-1.el6.remi.x86_64
php-tidy-7.1.0-1.el6.remi.x86_64
php-pear-Net-IDNA2-0.1.1-6.el6.remi.noarch
php-symfony-class-loader-2.8.15-1.el6.remi.noarch
php-xml-7.1.0-1.el6.remi.x86_64
php-gd-7.1.0-1.el6.remi.x86_64
php-7.1.0-1.el6.remi.x86_64
php-mysqlnd-7.1.0-1.el6.remi.x86_64
php-ldap-7.1.0-1.el6.remi.x86_64
php-mcrypt-7.1.0-1.el6.remi.x86_64
php-pear-Console-CommandLine-1.2.2-1.el6.remi.noarch
php-pecl-geoip-1.1.1-3.el6.remi.7.1.x86_64
php-mbstring-7.1.0-1.el6.remi.x86_64
php-devel-7.1.0-1.el6.remi.x86_64
php-tcpdf-dejavu-sans-fonts-6.2.12-1.el6.remi.noarch
```

**Comment by dterweij** [comment] 2016-12-14 16:18
Or check how it is build:

https://github.com/remicollet/remirepo/tree/master/php/php71

**Comment by dterweij** [comment] 2016-12-14 16:29
As alternative, just for this, I can alllow ssh access (with your pubkey) for you so you can check arround?

**Comment by GeoffreyDijkstra** [comment] 2016-12-14 18:36
That would make debugging a lot easier 😄
But in that case I suggest you sign up to spotweb2.slack.com and we can continue or live chats from there.
(and if that doesn't work, to send me your email so I can add you)

**Comment by GeoffreyDijkstra** [comment] 2016-12-14 18:47
Next time please use the following code for extension version output, because it's more readable:
```
<?php

$extensions = get_loaded_extensions();
foreach ($extensions as $extension) {
    echo str_pad($extension, 20, ' ', STR_PAD_RIGHT) . phpversion($extension) .                                                                                                                                                              "\n";
}
```

My output:
```
Core                7.1.0-3+deb.sury.org~xenial+1
date                7.1.0-3+deb.sury.org~xenial+1
libxml              7.1.0-3+deb.sury.org~xenial+1
openssl             7.1.0-3+deb.sury.org~xenial+1
pcre                7.1.0-3+deb.sury.org~xenial+1
zlib                7.1.0-3+deb.sury.org~xenial+1
filter              7.1.0-3+deb.sury.org~xenial+1
hash                1.0
pcntl               7.1.0-3+deb.sury.org~xenial+1
Reflection          7.1.0-3+deb.sury.org~xenial+1
SPL                 7.1.0-3+deb.sury.org~xenial+1
session             7.1.0-3+deb.sury.org~xenial+1
standard            7.1.0-3+deb.sury.org~xenial+1
mysqlnd             mysqlnd 5.0.12-dev - 20150407 - $Id: d8daadaf41e3cd81d7c6ae9                                                                                                                                                             6c6091fd15b2c9382 $
PDO                 7.1.0-3+deb.sury.org~xenial+1
xml                 7.1.0-3+deb.sury.org~xenial+1
calendar            7.1.0-3+deb.sury.org~xenial+1
ctype               7.1.0-3+deb.sury.org~xenial+1
curl                7.1.0-3+deb.sury.org~xenial+1
dom                 20031129
mbstring            7.1.0-3+deb.sury.org~xenial+1
fileinfo            1.0.5
ftp                 7.1.0-3+deb.sury.org~xenial+1
gd                  7.1.0-3+deb.sury.org~xenial+1
gettext             7.1.0-3+deb.sury.org~xenial+1
iconv               7.1.0-3+deb.sury.org~xenial+1
igbinary            1.2.2-dev
imagick             3.4.3RC1
json                1.5.0
exif                1.4 $Id: 8bdc0c8f27c2c9dd1f7551f1f9fe3ab57a06a4b1 $
mcrypt              7.1.0-3+deb.sury.org~xenial+1
mongodb             1.2.0
mysqli              7.1.0-3+deb.sury.org~xenial+1
pdo_mysql           7.1.0-3+deb.sury.org~xenial+1
Phar                2.0.2
posix               7.1.0-3+deb.sury.org~xenial+1
readline            7.1.0-3+deb.sury.org~xenial+1
redis               3.0.0
shmop               7.1.0-3+deb.sury.org~xenial+1
SimpleXML           7.1.0-3+deb.sury.org~xenial+1
sockets             7.1.0-3+deb.sury.org~xenial+1
sysvmsg             7.1.0-3+deb.sury.org~xenial+1
sysvsem             7.1.0-3+deb.sury.org~xenial+1
sysvshm             7.1.0-3+deb.sury.org~xenial+1
tokenizer           7.1.0-3+deb.sury.org~xenial+1
wddx                7.1.0-3+deb.sury.org~xenial+1
xmlreader           7.1.0-3+deb.sury.org~xenial+1
xmlwriter           7.1.0-3+deb.sury.org~xenial+1
xsl                 7.1.0-3+deb.sury.org~xenial+1
zip                 1.13.5
Zend OPcache        7.1.0-3+deb.sury.org~xenial+1
xdebug              2.5.0
```

**Comment by dterweij** [comment] 2016-12-14 21:05
@GeoffreyDijkstra  Funny, I do miss some PM function at Github :) 
Use danny-at-terweij-dot-nl for the slack. Could not find a "register" thing :)

**Comment by GeoffreyDijkstra** [comment] 2016-12-14 21:17
@dterweij For anti spam I removed your message.
Github did have a PM function but they removed it, but if you really want to find out an email just look in commits 😁

**Comment by GeoffreyDijkstra** [comment] 2016-12-19 07:29
@mesa57 @Sweepr I looked into this, and as far as I can see now it's related to the openssl version installed on @dterweij his machine. However the array thing is a real error, but the fix is already in the hotfix branch. So this will be merged and this issue will be closed.

**Closed by GeoffreyDijkstra** 2016-12-19 07:29 UTC
Labels: bug, In progress, not reproducable

**Comment by GeoffreyDijkstra** [comment] 2016-12-19 12:37
#246 It seems that there are more people with the openssl related errors in PHP 7.1, the only thing I now wonder, did this happen to him after adding the array fix into master or did he had it before...

**Comment by calvodioni** [comment] 2020-05-24 22:20
This is the solution to the error of no supported string or wrong element in php. if can not see the answer just click on preview. so you will see the answer.



<
<img width="960" alt="2020-05-24" src="https://user-images.githubusercontent.com/59261378/82766210-14334080-9deb-11ea-8b8c-ae30a543882b.png">
