### ISSUE TITLE
dbeng_pdo.php error trying to access array offset on value of type bool

### ISSUE THREAD

**Issue by WorkaholicGoT** [spotweb/spotweb#467] opened 2020-03-03 12:41 UTC
Seeing this error on spot pages (opening a spot) on top of the image

![spotweberror](https://user-images.githubusercontent.com/672575/75776602-93692900-5d54-11ea-847e-de89fd273ef9.png)

Running PHP 7.4, Debian 10, Mysql 5.7. 

Any idea's?

**Comment by Sweepr** [comment] 2020-03-03 12:53
Not sure if we support 7.4 yet.

Based on the documentation:

The problem

While code which relies on this undocumented behaviour of PHP returning null when attempting to array access a null/bool/int/float/resource, will continue to work as expected, each and every instance of this will now throw a PHP E_WARNING.

The solution

When using array access on the outcome of functions with mixed return values, i.e. array|false and the likes, more type checking needs to be done before attempting to access the return value as if it were an array to prevent this warning.

You can turn off notices for now and ignore untill 7.4 is fully tested and supported.

**Comment by Sweepr** [comment] 2020-03-03 13:02
Can you change line 129.

return $row[0];

into:  

return $row[0]; ?? 'default value';

See if that fixes it?

**Comment by WorkaholicGoT** [comment] 2020-03-03 13:03
Where do I change this exactly?

**Comment by Sweepr** [comment] 2020-03-03 13:05
In https://github.com/spotweb/spotweb/blob/develop/lib/dbeng/dbeng_pdo.php

**Comment by Sweepr** [comment] 2020-03-03 13:06
https://github.com/spotweb/spotweb/blob/95498d56c7c039f9bbae6076b92226ab5cfa03f4/lib/dbeng/dbeng_pdo.php#L129

**Comment by WorkaholicGoT** [comment] 2020-03-03 13:15
Changed! No more error. So I think it's fixed :) THanks!!

**Comment by Sweepr** [comment] 2020-03-03 13:23
Nice, keep an eye on things, if you see anything strange please re-open this so we can have a look.

I will close this for now and test on PHP 7.4 myself whenever i have time, please keep in mind 7.4 is not supported yet,.

**Closed by Sweepr** 2020-03-03 13:23 UTC

**Comment by Sweepr** [comment] 2020-03-05 16:18
I've done some more testing using PHP7.4 on a fresh install, and i forgot to mention that `'default value';` should be `NULL` as that is the default SQL-response.
Using `'default value';` in this case results in issue's during the user creation, so i recommend changing line 129 from `return $row[0] ?? 'default value';` into `return $row[0] ?? NULL;`

I also noticed a few more when running retrieve.php:

Warning: A non-numeric value encountered in C:\wamp64\www\develop\lib\services\Format\Services_Format_Parsing.php on line 288

Notice: Trying to access array offset on value of type bool in C:\wamp64\www\develop\lib\services\Providers\Services_Providers_Http.php on line 398

When i have more time i will see if i can sort those out.

**Comment by mesa57** [comment] 2020-03-05 19:47
Warnings during retrieve are mostly caused by bogus messages coming in.
But of course spotweb should be resilient to that (as much as possible).

**Comment by Sweepr** [comment] 2020-03-06 06:04
Yes, i've noticed these 2 error's to appear the first time of retrieval, so with an empty DB, do you think we can safely ignore those two error's then?

Either way we should silence them i.m.o.

**Comment by mesa57** [comment] 2020-03-06 10:33
Those can be silenced in my opinion.

**Comment by Sweepr** [comment] 2020-03-06 16:02
Not sure if should should stay compatible with PHP5.6 but `??` operator is not compatible with older version's PHP:

![image](https://user-images.githubusercontent.com/2857865/76099936-2cee4000-5fcc-11ea-8e6e-8822738507be.png)

So i've reverted that change and used this instead:

```
if ($row)
{
	return $row[0];
} else {
	return NULL;
} 
```

**Comment by mesa57** [comment] 2020-03-07 13:20
PHP 5.6 is still used on some nas devices. Good change.
