### ISSUE TITLE
Spotweb Windows 

### ISSUE THREAD

**Issue by sojab0on** [spotweb/spotweb#347] opened 2017-12-06 17:26 UTC
Every time i download spotweb the zip from here, i get 
Parse error: syntax error, unexpected '[' in C:\NAS-Softs\xampp\htdocs\spotweb\install.php on line 53 when i try to load http://localhost/spotweb/install.php 
Have tried Xampp newst version fiddle with the line out qouting and deliting the line but then it gives back errors in 
Parse error: syntax error, unexpected '[' in C:\NAS-Softs\xampp\htdocs\spotweb\lib\SpotInstall.php on line 48

What can i do to fix it and install spotweb

**Comment by Sweepr** [comment] 2017-12-07 17:34
Which version of PHP do you use?

Depending on the Version of PHP you are using: [ ] may or may not work.

**Comment by sojab0on** [comment] 2017-12-08 09:53
it is the latatest version of XAMPP witch as far as i can find out uses php 7.1.11

**Comment by mesa57** [comment] 2017-12-08 10:34
Goto the command line and type php -v

**Comment by tharealmb** [comment] 2017-12-10 12:13
I also had issues with Windows with the latest xampp version (which has php 7.1.1). I installed the version with 5.6 from here https://www.apachefriends.org/download.html for windows. Did the install again and worked fine. 

With 7.1.1 I had issues with install. When install finally worked, retrieve didn't work. When it finally did, it stopped retrieving after a few 100 spots. After installing the version with 5.6 it was all fixed. Maybe something to add in the install guide on Spotweb for Windows? Xampp is recommended, but not stated that 5.6 php version is best I think.

**Comment by mesa57** [comment] 2017-12-10 22:07
Downloaded latest version of xampp under windows 10 creator.
I cannot reproduce you're issue(s) (php 7.1.11)
So I am closing this issue as not being a spotweb issue.

**Closed by mesa57** 2017-12-10 22:07 UTC
