### ISSUE TITLE
Preview on Overview Page

### ISSUE THREAD

**Issue by hhekker** [spotweb/spotweb#64] opened 2015-05-12 10:08 UTC
With the last update the preview on the overview page is not available anymore.

Please advise how to solve this issue.

**Comment by Sweepr** [comment] 2015-05-12 14:29
This has never been in Master, but in Media only.

Please make sure to use the correct branch.

**Comment by hhekker** [comment] 2015-05-12 14:51
How do I put this issue in the correct branch. The branch Media you are talking about?

**Comment by Sweepr** [comment] 2015-05-12 14:57
Yes, which ZIP did you download?

https://github.com/spotweb/spotweb/archive/media.zip
Or this one?
https://github.com/spotweb/spotweb/archive/master.zip

**Comment by hhekker** [comment] 2015-05-12 15:14
I am running Spotweb Version 20150506-1 on my Synology DS213+ distributed via Package Source http://packages.mdevries.org/.

Martijn85 stated on http://www.synology-forum.nl/spotweb/spotweb-geen-afbeeldingen-in-overview/ the developer probably removed this function and to make an issue at Github.

**Comment by Sweepr** [comment] 2015-05-12 15:26
Ok, i see.

Well the problem is that we don't know which branch they are using to create the package for synology.

As far as i know the image preview has never been in Master and is not removed from Media branch.
So mdevries must be maintaining his own branch, this has nothing to do with us.

**Comment by Sweepr** [comment] 2015-05-12 15:36
You could try this, not sure if it will work


In the spotweb root folder find file:

/templates/we1rdo/spots.inc.php

Open this in a code-editor like notepad++

Find line 100 add this in between:
Old:

<a onMouseOver="toggleImageSize()" onMouseOut="toggleImageSize()" class="postimage" "<a target="_blank" href='<?php echo $spot['website'];?>'>
</a>

New

<a onMouseOver="toggleImageSize()" onMouseOut="toggleImageSize()" class="postimage" "<a target="_blank" href='<?php echo $spot['website'];?>'>
<img class="spotinfoimage" src="<?php echo $tplHelper->makeImageUrl($spot, 260, 260); ?>" alt="<?php echo $spot['title'];?>">
</a>

**Comment by hhekker** [comment] 2015-05-12 19:51
Below line 100 of /templates/we1rdo/spots.inc.php, No onMouseOver.

![image](https://cloud.githubusercontent.com/assets/12409386/7596707/085940a2-f8f0-11e4-905c-9d1e1ea0318d.png)

Did a search in spots.inc.php and no onMouseOver at all!

**Comment by hhekker** [comment] 2015-05-12 20:30
@Sweepr I had contact with Martijn85, he is using the Master branch. He told me the preview was in before, in the Master branch.

**Comment by Sweepr** [comment] 2015-05-12 20:46
Ok, could you figure out which version of spotweb this is? after that it's still a question which parts have been broken out of the source and added if any.

You could try to install GIT on synology and do a git clone of the master or media branch, which your prefer, there the onMouseOver and preview image still exist

**Comment by Sweepr** [comment] 2015-05-12 21:01
Oh i'm sorry for my typo.. the file should be spotsinfo.inc.php

**Comment by Sweepr** [comment] 2015-05-12 21:09
I'm tired ;-)

Try putting this in line 123 at /templates/we1rdo/spots.inc.php

http://pastebin.com/BANwZTSi

**Comment by Sweepr** [comment] 2015-05-12 21:27
@hhekker 

Note: 

This repository is a backup of the original Spotweb sourcecode, the original was removed/deleted somewhere in the beginning of 2014, it might well be that the imagepreview was inplemented back then before the time of the deletion, with the source we now have i can say that to my knowledge there no image preview in the master branch at this time.

**Comment by hhekker** [comment] 2015-05-13 14:47
@Sweepr I put http://pastebin.com/BANwZTSi in line 115 at /templates/we1rdo/spots.inc.php. The preview on the overview page is available again. You are great, thank you.

Is it OK for you to communicate this with Martijn85 and publish it as solution at http://www.synology-forum.nl/spotweb/spotweb-geen-afbeeldingen-in-overview/?

Are you going to implement the preview in the Master branch?

**Comment by Sweepr** [comment] 2015-05-13 14:50
No problem!,

I'll create a commit for this then, as many seem to like it.

You point others to this issue for the fix.

**Comment by Sweepr** [comment] 2015-05-13 14:57
Updated spots.inc.php

Added the image preview to spotsoverview:

https://github.com/spotweb/spotweb/commit/85545a899dd39ca329d8dda71aaa9ede64b9c2de

**Comment by Sweepr** [comment] 2015-05-13 15:03
For the masterbranch, if you manually update, please also edit/change this file:

https://github.com/spotweb/spotweb/blob/master/templates/we1rdo/js/scripts.js

**Comment by hhekker** [comment] 2015-05-13 15:47
I will point others to this issue for the fix.

Thank you for your help.

**Comment by Sweepr** [comment] 2015-05-13 16:09
Allright then, please let me know if you encounter any issue's along the way, if everything keeps running fine i can close the issue.

**Comment by Sweepr** [comment] 2015-05-15 11:57
Since i have not heard back since last time i'm asuming everything i working as intended and i'll close this.

**Closed by Sweepr** 2015-05-15 11:57 UTC

**Comment by hhekker** [comment] 2015-05-15 12:14
The preview is working well. Thank you for the support. The issue can be closed.

**Comment by Sweepr** [comment] 2015-05-15 12:16
Thank you for the update!
