### ISSUE TITLE
Retrieve spots resulting into error "You have an error in your SQL syntax"

### ISSUE THREAD

**Issue by hunter-nl** [spotweb/spotweb#645] opened 2021-01-17 10:04 UTC
**Describe the bug/issue**
 - Run retrieve.php, it fetch spots. After some time it stopped with an error.
 - Running again, it resulting directly into the same error.
 - Error:
 ```
Last retrieve at Thu 01 Jan 1970 01:00:00 AM CET
Retrieving new Spots from server news.sunnyusenet.com...
Appr. Message count: 	3415810
First message number:	68872
Last message number:	3484682
Current article number:	2749408

Retrieving 2749408 till 2754409 (parsed: 118, in DB: 4883, signed: 1, invalid: 115, rtntn.skip: 0, mod: 2, full: 0, total: 5001)

SpotWeb v0.68.32.33 on PHP v8.0.1 crashed

Fatal error occured retrieving reports:
  42000: 1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 1



#0 /var/www/spotweb/lib/dbeng/dbeng_pdo.php(86): dbeng_pdo->exec()
#1 /var/www/spotweb/lib/dao/Base/Dao_Base_Comment.php(289): dbeng_pdo->modify()
#2 /var/www/spotweb/lib/services/Retriever/Services_Retriever_Spots.php(636): Dao_Base_Comment->removeComments()
#3 /var/www/spotweb/lib/services/Retriever/Services_Retriever_Base.php(238): Services_Retriever_Spots->process()
#4 /var/www/spotweb/lib/services/Retriever/Services_Retriever_Base.php(339): Services_Retriever_Base->loopTillEnd()
#5 /var/www/spotweb/retrieve.php(142): Services_Retriever_Base->perform()
#6 {main}

Finished retrieving spots.
```

**To Reproduce**
1. Fresh new install spotweb and walked through setup configuration wizard.
2. Run /usr/bin/php retrieve.php
2. Resulting into an error and will not continue.

**Expected behavior**
 - Retrieve all spots.

**Versions**
 - Spotweb Version [e.g. 1.4.8] v0.68.32.33
 - Which branch:  Develop (Master is not working with PHP8)
 - OS: CentOS 8.3
 - PHP version 8.0.1
 - MariaDB 10.3.27
 - Nginx 1.14.1

**Additional context**
Debug output:
```
[2021-01-17 10:51:39] SpotWeb.INFO: foreach-loop, start. msgId= 5001
[2021-01-17 10:51:39] SpotWeb.INFO: foreach-loop, done. msgId= 5001
[2021-01-17 10:51:39] SpotWeb.DEBUG: added Spots, spotDbList=a:1:{i:0;a:21:{s:6:"header";s:112:"17a05b03c04d57z02.3945682.10.1454150151.1.NL.dbnxUqH7Mq8GmUdoj6uR3R2Yg08d-ppGZtdjwSK977Te4hTQ4PV-pkpPZ-snwNQjHL7";s:16:"selfsignedpubkey";s:64:"s0r4YpDXOaUwZYFvIQz4zWHfdhJCsycbp3t498VCn7iQuHQh4OPN2ixaf2OtSsoz";s:14:"user-signature";s:64:"XqKVyJWgcWLXtOz1iTpb90DCsIWVMjE4aBqfhyKBLtc5f1zm3VXaK32EUyTLKyCW";s:8:"verified";i:1;s:8:"filesize";s:7:"3945682";s:9:"messageid";s:30:"RdYbwJccYpkA5KsVgyjbm@spot.net";s:5:"stamp";i:1454150072;s:6:"poster";s:6:"Duster";s:8:"category";d:0;s:5:"keyid";i:7;s:7:"subcata";s:3:"a5|";s:7:"subcatb";s:3:"b3|";s:7:"subcatc";s:4:"c10|";s:7:"subcatd";s:4:"d57|";s:7:"subcatz";s:3:"z2|";s:9:"wassigned";b:1;s:9:"spotterid";s:6:"wlMwQQ";s:5:"title";s:33:"The Complete Works of SHAKESPEARE";s:3:"tag";s:0:"";s:10:"headersign";s:67:"dbnxUqH7Mq8GmUdoj6uR3R2Yg08d-ppGZtdjwSK977Te4hTQ4PV-pkpPZ-snwNQjHL7";s:8:"user-key";a:2:{s:6:"modulo";s:64:"s0r4YpDXOaUwZYFvIQz4zWHfdhJCsycbp3t498VCn7iQuHQh4OPN2ixaf2OtSsoz";s:8:"exponent";s:4:"AQAB";}}}
[2021-01-17 10:51:39] SpotWeb.DEBUG: added Spots, fullSpotDbList=a:0:{}
[2021-01-17 10:51:39] SpotWeb.DEBUG: Services_Nntp_Engine->quit()
[2021-01-17 10:51:39] SpotWeb.DEBUG: Services_Nntp_Engine->quit()
```

**Comment by Sweepr** [comment] 2021-01-17 11:03
@hunter-nl I must inform you that nowhere on the Wiki is written that Spotweb works on PHP8, so i have no idea were you got the idea to run it on PHP 8.0.1 at all and expect everything to work just fine, as you already mentioned in the issue description: (Master is not working with PHP8)

But nonetheless i will have a quick check what may be the issue.

Can you show me your settings:

![image](https://user-images.githubusercontent.com/2857865/104838555-f0fa5b80-58bb-11eb-80b6-9303d22a06e8.png)

**Comment by hunter-nl** [comment] 2021-01-17 11:08
I saw already some fixes for PHP8 in develop branch. So I gave it a try. It looks good, except the error I experienced now. But this looks to me not related to PHP8.
The settings are:
![image](https://user-images.githubusercontent.com/5203309/104838634-81d13700-58bc-11eb-806b-e0da941034d4.png)

**Comment by Sweepr** [comment] 2021-01-17 11:12
@hunter-nl 

If you disable "Retrieve reports", does retrieve run ok?

I'm running develop on MariaDB 10.3.27 and PHP 8.0.1 too, but for me it works fine.

**Comment by hunter-nl** [comment] 2021-01-17 11:16
Keep the same issue with disabled "Retrieve reports". I also disabled "Retrieve comments". But then I still keep the same error.

**Comment by Sweepr** [comment] 2021-01-17 11:19
Funny, because the error reads: "Fatal error occured retrieving reports:" with reports disabled it should skip.

Did you try to truncate table "reportsxover" and run again?

**Comment by hunter-nl** [comment] 2021-01-17 11:22
> Did you try to truncate table "reportsxover" and run again?
I did it just now and tried again. Still same error.

**Comment by Sweepr** [comment] 2021-01-17 11:24
Please post the exact error you see here.

**Comment by hunter-nl** [comment] 2021-01-17 11:27
```
# php retrieve.php --debug
Last retrieve at Thu 01 Jan 1970 01:00:00 AM CET
Retrieving new Spots from server news.sunnyusenet.com...
Appr. Message count: 	3415874
First message number:	68872
Last message number:	3484746
Current article number:	2749408

Retrieving 2749408 till 2754409 (parsed: 118, in DB: 4883, signed: 1, invalid: 115, rtntn.skip: 0, mod: 2, full: 0, total: 5001)

SpotWeb v0.68.32.33 on PHP v8.0.1 crashed

Fatal error occured retrieving reports:
  42000: 1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 1



#0 /var/www/spotweb/lib/dbeng/dbeng_pdo.php(86): dbeng_pdo->exec()
#1 /var/www/spotweb/lib/dao/Base/Dao_Base_Comment.php(289): dbeng_pdo->modify()
#2 /var/www/spotweb/lib/services/Retriever/Services_Retriever_Spots.php(636): Dao_Base_Comment->removeComments()
#3 /var/www/spotweb/lib/services/Retriever/Services_Retriever_Base.php(238): Services_Retriever_Spots->process()
#4 /var/www/spotweb/lib/services/Retriever/Services_Retriever_Base.php(339): Services_Retriever_Base->loopTillEnd()
#5 /var/www/spotweb/retrieve.php(142): Services_Retriever_Base->perform()
#6 {main}

Finished retrieving spots.
```
Debug log:
```
[2021-01-17 12:21:43] SpotWeb.INFO: foreach-loop, start. msgId= 4999
[2021-01-17 12:21:43] SpotWeb.INFO: foreach-loop, done. msgId= 4999
[2021-01-17 12:21:43] SpotWeb.INFO: foreach-loop, start. msgId= 5000
[2021-01-17 12:21:43] SpotWeb.INFO: foreach-loop, done. msgId= 5000
[2021-01-17 12:21:43] SpotWeb.INFO: foreach-loop, start. msgId= 5001
[2021-01-17 12:21:43] SpotWeb.INFO: foreach-loop, done. msgId= 5001
[2021-01-17 12:21:43] SpotWeb.DEBUG: added Spots, spotDbList=a:1:{i:0;a:21:{s:6:"header";s:112:"17a05b03c04d57z02.3945682.10.1454150151.1.NL.dbnxUqH7Mq8GmUdoj6uR3R2Yg08d-ppGZtdjwSK977Te4hTQ4PV-pkpPZ-snwNQjHL7";s:16:"selfsignedpubkey";s:64:"s0r4YpDXOaUwZYFvIQz4zWHfdhJCsycbp3t498VCn7iQuHQh4OPN2ixaf2OtSsoz";s:14:"user-signature";s:64:"XqKVyJWgcWLXtOz1iTpb90DCsIWVMjE4aBqfhyKBLtc5f1zm3VXaK32EUyTLKyCW";s:8:"verified";i:1;s:8:"filesize";s:7:"3945682";s:9:"messageid";s:30:"RdYbwJccYpkA5KsVgyjbm@spot.net";s:5:"stamp";i:1454150072;s:6:"poster";s:6:"Duster";s:8:"category";d:0;s:5:"keyid";i:7;s:7:"subcata";s:3:"a5|";s:7:"subcatb";s:3:"b3|";s:7:"subcatc";s:4:"c10|";s:7:"subcatd";s:4:"d57|";s:7:"subcatz";s:3:"z2|";s:9:"wassigned";b:1;s:9:"spotterid";s:6:"wlMwQQ";s:5:"title";s:33:"The Complete Works of SHAKESPEARE";s:3:"tag";s:0:"";s:10:"headersign";s:67:"dbnxUqH7Mq8GmUdoj6uR3R2Yg08d-ppGZtdjwSK977Te4hTQ4PV-pkpPZ-snwNQjHL7";s:8:"user-key";a:2:{s:6:"modulo";s:64:"s0r4YpDXOaUwZYFvIQz4zWHfdhJCsycbp3t498VCn7iQuHQh4OPN2ixaf2OtSsoz";s:8:"exponent";s:4:"AQAB";}}}
[2021-01-17 12:21:43] SpotWeb.DEBUG: added Spots, fullSpotDbList=a:0:{}
[2021-01-17 12:21:43] SpotWeb.DEBUG: Services_Nntp_Engine->quit()
[2021-01-17 12:21:43] SpotWeb.DEBUG: Services_Nntp_Engine->quit()
```

**Comment by Sweepr** [comment] 2021-01-17 11:29
To rule out some kind of database error/corruption could you do a reset of your database by running this command:

You will be able to reset the DB, using the command

`php upgrade-db.php --reset-db` , and confirm with yes.

Then run `retrieve.php` again.

**Comment by hunter-nl** [comment] 2021-01-17 11:50
It took some time to get to the same spot. Resulting into same error.
```
Retrieving 2729404 till 2734405 (parsed: 5001, in DB: 0, signed: 4969, invalid: 32, rtntn.skip: 0, mod: 0, full: 0, total: 5001) in 1.68 seconds
Retrieving 2734405 till 2739406 (parsed: 5001, in DB: 0, signed: 3847, invalid: 1154, rtntn.skip: 0, mod: 0, full: 0, total: 5001) in 1.52 seconds
Retrieving 2739406 till 2744407 (parsed: 5001, in DB: 0, signed: 4982, invalid: 19, rtntn.skip: 0, mod: 0, full: 0, total: 5001) in 2.17 seconds
Retrieving 2744407 till 2749408 (parsed: 5001, in DB: 0, signed: 4986, invalid: 15, rtntn.skip: 0, mod: 0, full: 0, total: 5001) in 1.78 seconds
Retrieving 2749408 till 2754409 (parsed: 5001, in DB: 0, signed: 4884, invalid: 115, rtntn.skip: 0, mod: 2, full: 0, total: 5001)

SpotWeb v0.68.32.33 on PHP v8.0.1 crashed

Fatal error occured retrieving reports:
  42000: 1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 1



#0 /var/www/spotweb/lib/dbeng/dbeng_pdo.php(86): dbeng_pdo->exec()
#1 /var/www/spotweb/lib/dao/Base/Dao_Base_Comment.php(289): dbeng_pdo->modify()
#2 /var/www/spotweb/lib/services/Retriever/Services_Retriever_Spots.php(636): Dao_Base_Comment->removeComments()
#3 /var/www/spotweb/lib/services/Retriever/Services_Retriever_Base.php(238): Services_Retriever_Spots->process()
#4 /var/www/spotweb/lib/services/Retriever/Services_Retriever_Base.php(339): Services_Retriever_Base->loopTillEnd()
#5 /var/www/spotweb/retrieve.php(142): Services_Retriever_Base->perform()
#6 {main}

Finished retrieving spots.
```

**Comment by Sweepr** [comment] 2021-01-17 11:56
Could you show me the outcome of: `SELECT @@SQL_MODE, @@GLOBAL.SQL_MODE;` from your SQL CLI?

I have this: 
![image](https://user-images.githubusercontent.com/2857865/104839754-7a615c00-58c3-11eb-9b71-6307973b55a3.png)

**Comment by hunter-nl** [comment] 2021-01-17 11:59
I have the same output as you.

**Comment by Sweepr** [comment] 2021-01-17 12:15
The MariaDB documentation reads: 

> **Syntax errors**
> 
> If there are more open parentheses than closed parentheses, the error usually looks like this:
> 
> ```
> ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that
> corresponds to your MariaDB server version for the right syntax to use near '' a
> t line 1
> ```
> 
> Note the empty string.
> 
> If there are more closed parentheses than open parentheses, the error usually looks like this:
> 
> ```
> ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that
> corresponds to your MariaDB server version for the right syntax to use near ')'
> at line 1
> ```
> 
> Note the quoted closed parenthesis.

Source: https://mariadb.com/kb/en/parentheses/

Where the last matches the error you are seeing.

Strange thing here is that i am using exactly the same source as you are, means the Develop branch, there is not difference unless something on your system is wrong, i would suggest pulling a new instance of the source and see if it replicates.

**Comment by Sweepr** [comment] 2021-01-17 12:23
According the error produced by MariaDB it finds that somewhere in the code there is 1x `(` too much, or 1x `) ` too less causing the error.

Could be a file mismatch between the develop source on github and your system.

**Comment by hunter-nl** [comment] 2021-01-17 12:28
I've added extra debug just before /var/www/spotweb/lib/dbeng/dbeng_pdo.php(86): dbeng_pdo->exec(). Just before it executes the SQL statement, I've added a printf($s).
The SQL statement trying to execute:
```
DELETE FROM spots, spotsfull, reportsxover, spotstatelist, reportsposted USING spots
							LEFT JOIN spotsfull ON spots.messageid=spotsfull.messageid
                            LEFT JOIN reportsxover ON spots.messageid=reportsxover.nntpref
							LEFT JOIN spotstatelist ON spots.messageid=spotstatelist.messageid
							LEFT JOIN reportsposted ON spots.messageid=reportsposted.inreplyto
							WHERE spots.messageid  IN ('RdYbwJccYpkA5KsVgyjbm@spot.net')DELETE FROM commentsfull WHERE messageid IN ()
```
Where is the extra ``` DELETE FROM commentsfull WHERE messageid IN () ``` (scroll to the right in the SQL statement) coming from???

**Comment by hunter-nl** [comment] 2021-01-17 12:32
> Could be a file mismatch between the develop source on github and your system.

I've just checked, but it the same as in GitHub develop branch (except the previously mentioned temporary added debug output code to show the SQL statement).

**Comment by Sweepr** [comment] 2021-01-17 12:52
> 
> 
> I've added extra debug just before /var/www/spotweb/lib/dbeng/dbeng_pdo.php(86): dbeng_pdo->exec(). Just before it executes the SQL statement, I've added a printf($s).
> The SQL statement trying to execute:
> 
> ```
> DELETE FROM spots, spotsfull, reportsxover, spotstatelist, reportsposted USING spots
> 							LEFT JOIN spotsfull ON spots.messageid=spotsfull.messageid
>                             LEFT JOIN reportsxover ON spots.messageid=reportsxover.nntpref
> 							LEFT JOIN spotstatelist ON spots.messageid=spotstatelist.messageid
> 							LEFT JOIN reportsposted ON spots.messageid=reportsposted.inreplyto
> 							WHERE spots.messageid  IN ('RdYbwJccYpkA5KsVgyjbm@spot.net')DELETE FROM commentsfull WHERE messageid IN ()
> ```
> 
> Where is the extra `DELETE FROM commentsfull WHERE messageid IN ()` (scroll to the right in the SQL statement) coming from???

https://github.com/spotweb/spotweb/blob/703307834abb585cb987fb6c04777620aa09d61f/lib/dao/Base/Dao_Base_Comment.php#L289

**Comment by Sweepr** [comment] 2021-01-17 12:57
https://github.com/spotweb/spotweb/blob/703307834abb585cb987fb6c04777620aa09d61f/lib/services/Retriever/Services_Retriever_Spots.php#L636

**Comment by hunter-nl** [comment] 2021-01-17 12:58
> $this->_conn->modify('DELETE FROM commentsfull WHERE messageid IN ('.$msgIdList.')');

So when $msgIdList is empty, it results into an error.

**Comment by Sweepr** [comment] 2021-01-17 13:03
> 
> 
> > $this->_conn->modify('DELETE FROM commentsfull WHERE messageid IN ('.$msgIdList.')');
> 
> So when $msgIdList is empty, it results into an error.

Yeah, but https://github.com/spotweb/spotweb/blob/703307834abb585cb987fb6c04777620aa09d61f/lib/dao/Base/Dao_Base_Comment.php#L288 it only executes when not false.

**Comment by hunter-nl** [comment] 2021-01-17 13:21
> > > $this->_conn->modify('DELETE FROM commentsfull WHERE messageid IN ('.$msgIdList.')');
> > 
> > 
> > So when $msgIdList is empty, it results into an error.
> 
> Yeah, but
> 
> https://github.com/spotweb/spotweb/blob/703307834abb585cb987fb6c04777620aa09d61f/lib/dao/Base/Dao_Base_Comment.php#L288
> 
> it only executes when not false.

But empty string is true.
So the SQL statement will be:
```
DELETE FROM commentsfull WHERE messageid IN ()
```
That's invalid SQL statement.
It should be at least quoted:
```
DELETE FROM commentsfull WHERE messageid IN ('')
```
Or even better, it is not needed to execute the SQL statement, because there's never a match with messageid in an empty string.

To fix this, change
https://github.com/spotweb/spotweb/blob/703307834abb585cb987fb6c04777620aa09d61f/lib/dao/Base/Dao_Base_Comment.php#L288
into 
```
if (isset($msgIdList) && $msgIdList !== '') {
```

**Comment by Sweepr** [comment] 2021-01-17 13:41
In which cases can it be empty? i have never come across this issue before so where is it coming from and why?

**Comment by Sweepr** [comment] 2021-01-17 13:50
@mesa57 

Any clue what may be the cause of this issue before we try to make a fix for something else that's broken?

**Comment by mesa57** [comment] 2021-01-17 13:57
The array can be empty because there are no comments for a spot which has been moderated.
That also depends on you're USP of course if messages are present or not.
It seems tp me that in this special case it is appearing.
My best guess is that the result of constructing the array of message-id's to be deleted is not false due to some different behaviour of php 8.0.1 (or maria db ?).
De code could be checked on that and maybe improved.

**Comment by Sweepr** [comment] 2021-01-17 14:03
@mesa57 

Would this section not catch this and return ?

```
        if (count($commentMsgIdList) == 0) {
            return;
        } // if
```

**Comment by hunter-nl** [comment] 2021-01-17 14:19
@Sweepr 
> Would this section not catch this and return ?
> 
> ```
>         if (count($commentMsgIdList) == 0) {
>             return;
>         } // if
> ```

Not if $commentMsgIdList is not an array. When it is an empty array, it is correct.
Better is
```
if (!is_array($commentMsgIdList) || count($commentMsgIdList) == 0) {
  return;
}
```

**Comment by Sweepr** [comment] 2021-01-17 15:00
That would probably fix it, but i still like to know why it happens, i am thinking that there is something weird on news.sunnyusenet.com's side.

Is there any change you could test a different USP?, i am curious if that makes a difference.

Anyway i will create a PR for this in dev branch.

**Comment by mesa57** [comment] 2021-01-17 15:16
I am not sure if null is the same as false:

> Note: If no parameter is supplied, then the parentheses must be omitted and null will be returned.

**Comment by hunter-nl** [comment] 2021-01-17 15:18
> I am not sure if null is the same as false:
> 
> > Note: If no parameter is supplied, then the parentheses must be omitted and null will be returned.

``` if (isset($msgIdList) && $msgIdList !== '') { ```
It will catch null, not set, false and empty string.

**Comment by hunter-nl** [comment] 2021-01-17 15:25
@Sweepr 
No I do not have a different USP available.
I also wants to know why it happens :-)

So I searched further:
https://github.com/spotweb/spotweb/blob/86b6b8492938a3e22ae9023cf40eaf7fe06c421b/lib/services/Retriever/Services_Retriever_Spots.php#L672-L692
The line ``` $tmpArray = $this->_spotDao->getDisposedSpots($moderationList); ``` can resulting into $tmpArray=False. But the rest of the function is expecting it as an array.

But even further, the next question is why the SQL select statement results into return value False of the function arrayQuerry.
https://github.com/spotweb/spotweb/blob/86b6b8492938a3e22ae9023cf40eaf7fe06c421b/lib/dao/Base/Dao_Base_Spot.php#L357-L363

**Comment by muis** [comment] 2021-01-17 15:28
@Sweepr Your fix still doesnt fully prevent the error, because the arrayKeyToInForComments function which follows the check, can result in an empty array, since it excludes messageid's from spots which are disposed by the owner. So I would suggest to include the fix @hunter-nl suggested, as it takes places after arrayKeyToInForComments instead of before.

Also there are other functions (like markCommentsModerated) which need the same fix.

**Comment by Sweepr** [comment] 2021-01-17 15:32
> @Sweepr Your fix still doesnt fully prevent the error, because the arrayKeyToInForComments function which follows the check, can result in an empty array, since it excludes messageid's from spots which are disposed by the owner. So I would suggest to include the fix @hunter-nl suggested, as it takes places after arrayKeyToInForComments instead of before.
> 
> Also there are other functions (like markCommentsModerated) which need the same fix.

True, i was just looking at the exact same thing.

**Comment by hunter-nl** [comment] 2021-01-17 15:46
@Sweepr 
> Also there are other functions (like markCommentsModerated) which need the same fix.

Everywhere the functions "arrayKeyToIn", "arrayKeyToInForComments" and "arrayValToIn" are used, should be fixed.

Secondly, in SQL statements where ```... IN (somevariable)``` is used. Should be checked for empty variable. It may not result into ```... IN ()```

**Comment by Sweepr** [comment] 2021-01-17 16:02
@hunter-nl 

If this fix works for your i'll merge into develop.

https://github.com/spotweb/spotweb/pull/647

Let me know, then we can look at other fixes but one at a time ;-)

**Comment by hunter-nl** [comment] 2021-01-17 16:16
> @hunter-nl
> 
> If this fix works for you i will merge into develop.
> 
> #647
> 
> Let me know, then we can look at other fixes but one at a time ;-)

Yes this fix works for me. retrieve job just finished with all the spots/comments.

**Comment by Sweepr** [comment] 2021-01-17 16:34
@hunter-nl 

I'm closing this as the main reason is resolved.
You are always welcome to create PR's if you find anything that needs fixing.

**Closed by Sweepr** 2021-01-17 16:34 UTC
Labels: Develop branch, Help wanted, Not reproducable
