### ISSUE TITLE
Retrieve PHP is broken

### ISSUE THREAD

**Issue by Moonl1ghter** [spotweb/spotweb#368] opened 2018-05-03 21:30 UTC
Spotweb did not update for over a day, normally I have a cron running that updates it every 5 minutes. So I ran retrieve.php manually, dit not work had to use the force options but then the following error popped up:

```
retriever.php is already running, pass '--force' to ignore this warning.
host@host:~$ php /var/www/spotweb/retrieve.php --force
Removing Spot information which is beyond retention period,, done
Last retrieve at Wed 02 May 2018 06:30:13 PM CEST
Retrieving new Spots from server random.newsserver...
Appr. Message count:    2139154
First message number:   1008861
Last message number:    3148015
Current article number: 3147724

Retrieving 3147724 till 3148016 (parsed: 291, in DB: 1, signed: 286, invalid: 0, rtntn.skip: 0, mod: 5, full: 286, total: 292)

SpotWeb v0.68.29.32 on PHP v5.6.36-1+ubuntu16.04.1+deb.sury.org+1 crashed

Fatal error occured retrieving reports:
  HY000: 1366: Incorrect string value: '\xF0\x9F\x93\x80 L...' for column 'title' at row 1




#0 /var/www/spotweb/lib/dao/Base/Dao_Base_Spot.php(423): dbeng_pdo->batchInsert(Array, 'INSERT INTO spo...', Array, Array)
#1 /var/www/spotweb/lib/services/Retriever/Services_Retriever_Spots.php(612): Dao_Base_Spot->addSpots(Array, Array)
#2 /var/www/spotweb/lib/services/Retriever/Services_Retriever_Base.php(227): Services_Retriever_Spots->process(Array, '3147724', 3148016, 1525382798.1501)
#3 /var/www/spotweb/lib/services/Retriever/Services_Retriever_Base.php(319): Services_Retriever_Base->loopTillEnd('3147724', '2500')
#4 /var/www/spotweb/retrieve.php(145): Services_Retriever_Base->perform()
#5 {main}

Finished retrieving spots.
```

**Comment by mesa57** [comment] 2018-05-04 09:29
I do not think it is the report table. More likely, the problem is in the reports from usenet. They are more then often invalid.
Running retrieve again, most of time the invalid report message is skipped.
Retrieve --force is only allowed when you are sure no other retrieve is running as@sweeper already said.
I am not in favor of removing the --force option as I use that very often during testing.

**Comment by Sweepr** [comment] 2018-05-04 09:40
Alright. Then we leave the --force option like is, but like moonl1ghter said 

"Spotweb did not update for over a day, normally I have a cron running that updates it every 5 minutes"

For 24 hours, Every 5 mins, thats 288 retrieve's surely after a fews runs this issue would be resolved by itself ?

**Comment by Moonl1ghter** [comment] 2018-05-04 16:58
@mesa57  I figured as much, truncated the reports from the database, still no luck. Can't even run retrieve.php because it says that retrieve is already running. (While I'm pretty sure it is not) So yeah, will probably wipe the whole database and sync again.

**Comment by mesa57** [comment] 2018-05-04 17:06
@Moonl1ghter The check if retrieve is running is just a check against the database. Retrieve registers on start the timestamp is started. If you kill retrieve and start it again, it says already running because the new start is within the timespan defined for the check.
Could you tell which provider you use ?

**Comment by Moonl1ghter** [comment] 2018-05-04 17:07
@mesa57 I use a TweakNews block (only retrieving the spot headers, so not much bandwith used) But i have another provider I can check with. Will do.

**Comment by mesa57** [comment] 2018-05-04 17:16
I think I still have a 10gb block account from Tweaknews. If that still works I can test.

**Comment by mesa57** [comment] 2018-05-04 18:57
And please put retrieve full spots off unless you have a heavy visited public server.

**Comment by hjung7** [comment] 2018-05-04 19:18
I have exactly same error message with free xsusenet account.

**Comment by mesa57** [comment] 2018-05-04 19:28
Please test again without full spots retrieve.

**Comment by Stifler6996** [comment] 2018-05-05 01:44
Guys, this problem is with an emoji in the title, and a collation mismatch on the database.

Fatal error occured retrieving reports:
  HY000: 1366: Incorrect string value: '\xF0\x9F\x93\x80 L...' for column 'title' at row 20

First part of the fix is to change the db column "title" to utf8mb4. Google - there are many methods to do so, and you could also just change the whole db.

But I believe that you also need to change the connection to the db for this to be fixed completely.

This will convert tables and columns:
```mysql
SET foreign_key_checks = 0;
-- set your table name here
SET @MY_SCHEMA = "spotweb"; //Database name here

-- tables
SELECT DISTINCT
    CONCAT("ALTER TABLE ", TABLE_NAME," CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;") as queries
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA=@MY_SCHEMA
  AND TABLE_TYPE="BASE TABLE"

UNION

-- table columns

SELECT DISTINCT
    CONCAT("ALTER TABLE ", C.TABLE_NAME, " CHANGE ", C.COLUMN_NAME, " ", C.COLUMN_NAME, " ", C.COLUMN_TYPE, " CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;") as queries
FROM INFORMATION_SCHEMA.COLUMNS as C
    LEFT JOIN INFORMATION_SCHEMA.TABLES as T
        ON C.TABLE_NAME = T.TABLE_NAME
WHERE C.COLLATION_NAME is not null
    AND C.TABLE_SCHEMA=@MY_SCHEMA
    AND T.TABLE_TYPE="BASE TABLE"

UNION

-- views
SELECT DISTINCT
    CONCAT("CREATE OR REPLACE VIEW ", V.TABLE_NAME, " AS ", V.VIEW_DEFINITION, ";") as queries
FROM INFORMATION_SCHEMA.VIEWS as V
    LEFT JOIN INFORMATION_SCHEMA.TABLES as T
        ON V.TABLE_NAME = T.TABLE_NAME
WHERE V.TABLE_SCHEMA=@MY_SCHEMA
    AND T.TABLE_TYPE="VIEW";
	
SET foreign_key_checks = 1;```

**Comment by Stifler6996** [comment] 2018-05-05 01:55
Google suggests that the connection to the mysql db needs "SET NAMES utf8mb4" as well to handle the  4 byte emojis.

**Comment by mesa57** [comment] 2018-05-05 07:00
@Stifler : emoijs are not allowed in the title according to the spotnet protocol.

**Comment by Stifler6996** [comment] 2018-05-05 07:16
@mesa57 Whilst that may be so, someone has done just that, and Spotweb is not handling it. This is the actual error needing resolve. 

Also, do we know exactly where the emoji has been used? The error: "Fatal error occured retrieving reports:  HY000: 1366: Incorrect string value: '\xF0\x9F\x93\x80"
suggests to me that it is in a "title" column for "reports". Given there are spelling errors in the error itself, it could just be poor wording choice, or the emoji might be somewhere else, not in the spot itself.

Note: \xF0\x9F\x93\x80 is the emoji DVD symbol....

**Comment by mesa57** [comment] 2018-05-05 07:29
I don't get that error while doing a retrieve without 'full spots'. That means that the title as in the subject of the spot is correct, only the xml is messed with. You then should get an error on opening the specific spot.
The error does not occur during retrieving of reports (message is wrong).

**Comment by mesa57** [comment] 2018-05-05 12:40
At least found the spot : 
<Spotnet><Posting><Key>7</Key><Created>1525278721</Created><Poster>Elvis</Poster><Tag>Adult</Tag><Title>&#128192; Latin Stepdaughters</Title><Description>Latin Stepdaughters[br][br]Vindbaar via: [br]- a.b.ijsklontje[br]- a.b.kleverig[br]- a.b.xxx[br][br]Voor screenshots van de film kan je altijd even kijken op:[br]http://spotnet.byethost7.com/latin-stepdaughters.html[br]                                    [br]Elvis</Description><Website>http://spotnet.byethost7.com/latin-stepdaughters.html</Website><Image Width='430' Height='600'><Segment>1ZEBpBE97C4spfpWgQ06Y@spot.net</Segment></Image><Size>1484493404</Size><Category>01<Sub>01a00</Sub><Sub>01d75</Sub><Sub>01c00</Sub><Sub>01d23</Sub><Sub>01z03</Sub></Category><NZB><Segment>wGCUb7EjeikpufpWgS1Ia@spot.net</Segment></NZB></Posting></Spotnet>

**Comment by Stifler6996** [comment] 2018-05-05 13:14
good start @mesa57 ! I tested what you said and disabled full spots. Sure enough, the retrieve finished happily.

Since then I was able to find the spot, so checking it shows "?? Latin Stepdaughters" as the title.

The "??" are obviously the 4b emoji
``` <Title>📀 Latin Stepdaughters</Title> ```

First time I opened it, it did error out ('something wrong - return to main page')  and on a second attempt it did open.

I know you say that spotnab protocol doesnt accept emoji, but it might just be simpler to mitigate this by using what is now probably the defacto standard for collation.

I'd propose what I said earlier, modify db to be utf8mb4 and change the charset for PDO.

At least spotweb wont crash if people dont follow protocol, and no harm/foul if spot cannot be searched or fails (since it was against protocol).

It also brings the db to a more common current standard.

**Comment by mesa57** [comment] 2018-05-05 13:54
Conversion of an excisting db to utf8mb4 takes much to long. I am not going to introduce that because of 1 spot.

**Comment by Stifler6996** [comment] 2018-05-05 14:36
yeah, it takes me almost a whole 24 hours to build a brand new spotweb server with all options ticked. That is way too long...... How long does it take to convert a db?... weird argument you have there.

How about giving people the option.

For those who have unlimited BW and CPU cycles, give them the newer, better, defacto standard of today's DB's which doesn't care what language you speak.

or

regex it: https://www.regular-expressions.info/unicode8bit.html

**Comment by mesa57** [comment] 2018-05-05 14:59
During DB conversion it lost connection to my dbserver due to timeout.
I am not going to try different server settings for this.
Meanwhile I found a regex to solve the problem, but I have to debug the exception to find the exact line of code. But full spots retrieve takens 1400 sec / 1000 spots and my fullspots test db is more then a year old.

**Comment by mesa57** [comment] 2018-05-05 17:43
What versions of php / mysql are you using ?
I get no error in php 5.6 with mysql 5.6 ? (Just a spot with a blank title)

**Comment by mesa57** [comment] 2018-05-05 19:02
Develop branche is updated with a quickfix, please verify.

**Comment by Moonl1ghter** [comment] 2018-05-05 19:37
Thanks for all the responses, had a busy few days so no responses for me, will test your commit monday morning or tomorrow.

What exaxtly is the difference between full spots and header retrieving anyway. Never figured it out haha.

**Comment by mesa57** [comment] 2018-05-05 19:44
Headers means that only subject and category / poster is stored.
Full spots means that the complete spot is read and stored in the database.
For spots overview, headers are enough. When you open a spot, the full spot is retrieved (either from usenet or database).

**Comment by Moonl1ghter** [comment] 2018-05-08 11:28
Your fix seems to work just fine. No problems at all. Must be said that I installed spotweb fresh, with a new db and used only headers for spots and reports.

**Comment by mesa57** [comment] 2018-05-08 13:53
Ok, thank you for the feedback 😄

**Closed** 2018-05-10 12:16 UTC
Labels: Deployed
