### ISSUE TITLE
Spotweb overview page is slow to load after reinstall

### ISSUE THREAD

**Issue by Rouzax** [spotweb/spotweb#114] opened 2015-12-29 12:50 UTC
I can't figure out why my spotweb index overview is so slow to load while this used to be really fast. Somehow after a new install of Spotweb with a fresh DB it is slow.
```
Specs:
Windows 2012R2
IIS 8.5
PHP 5.6.16
MySQL 5.6.28

```
Spotweb Master: ef965705cb21e520c67cc04270b698ced0ab350a

Total Spotweb Database size is 3 GB

Running on:
```
OS Name	Microsoft Windows Server 2012 R2 Standard
Version	6.3.9600 Build 9600
System Model	Virtual Machine
System Type	x64-based PC
Processor	Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, 2600 Mhz, 4 Core(s), 4 Logical Processor(s)
Installed Physical Memory (RAM)	16,0 GB
Total Physical Memory	16,0 GB
```
Because it is virtual, additional memory or CPU's are no problem if more are needed.

It appears the big hangup is the slow select statement which takes around 30 seconds.
```
# Time: 151229 13:38:58
# User@Host: root[root] @ localhost [::1]  Id:    38
# Query_time: 32.684651  Lock_time: 0.000000 Rows_sent: 26  Rows_examined: 6463381
SET timestamp=1451392738;
SELECT s.id AS id,
												s.messageid AS messageid,
												s.category AS category,
												s.poster AS poster,
												l.download as downloadstamp, 
												l.watch as watchstamp,
												l.seen AS seenstamp,
												s.subcata AS subcata,
												s.subcatb AS subcatb,
												s.subcatc AS subcatc,
												s.subcatd AS subcatd,
												s.subcatz AS subcatz,
												s.title AS title,
												s.tag AS tag,
												s.stamp AS stamp,
												s.moderated AS moderated,
												s.filesize AS filesize,
												s.spotrating AS rating,
												s.commentcount AS commentcount,
												s.reportcount AS reportcount,
												s.spotterid AS spotterid,
 												s.editstamp AS editstamp,
 												s.editor AS editor,
												f.verified AS verified,
												COALESCE(bl.idtype, wl.idtype, gwl.idtype) AS idtype
												
									 FROM spots AS s  LEFT JOIN spotstatelist AS l on ((s.messageid = l.messageid) AND (l.ouruserid = 3)) 
									 LEFT JOIN spotsfull AS f ON (s.messageid = f.messageid) 
									 LEFT JOIN spotteridblacklist as bl ON ((bl.spotterid = s.spotterid) AND ((bl.ouruserid = 3) OR (bl.ouruserid = -1)) AND (bl.idtype = 1))
									 LEFT JOIN spotteridblacklist as wl on ((wl.spotterid = s.spotterid) AND ((wl.ouruserid = 3) AND (wl.idtype = 2)))
									 LEFT JOIN spotteridblacklist as gwl on ((gwl.spotterid = s.spotterid) AND ((gwl.ouruserid = -1) AND (gwl.idtype = 2)))  WHERE (bl.spotterid IS NULL)  AND (NOT ((s.Category = 0) AND (s.subcatz = 'z3|')))
									 ORDER BY s.reversestamp ASC LIMIT 26 OFFSET 25;
```

[Stack Trace.xlsx](https://github.com/spotweb/spotweb/files/73940/Stack.Trace.xlsx)

![image](https://cloud.githubusercontent.com/assets/4103090/12034783/e4315434-ae35-11e5-83e2-ddb5a64fd4b8.png)

![image](https://cloud.githubusercontent.com/assets/4103090/12034762/a5682b56-ae35-11e5-9ed6-2be89aca992b.png)

![image](https://cloud.githubusercontent.com/assets/4103090/12034769/b892d35c-ae35-11e5-836b-9b746e049b0e.png)

**Comment by Rouzax** [comment] 2015-12-29 13:47
Somehow after rerunning retrieve.php and upgrade-db.php it runs smooth again :confused: 
![image](https://cloud.githubusercontent.com/assets/4103090/12035241/fa9f0478-ae3a-11e5-92fa-4ae0511287f5.png)
![image](https://cloud.githubusercontent.com/assets/4103090/12035249/106b3c68-ae3b-11e5-813b-859e02f43095.png)

**Comment by Rouzax** [comment] 2015-12-29 14:01
And it is slow again with the statement taking 30 seconds :angry: 
![image](https://cloud.githubusercontent.com/assets/4103090/12035408/feee53a6-ae3c-11e5-80f8-b7dc804a10e5.png)

**Comment by mesa57** [comment] 2015-12-29 14:44
Try using ANALYZE TABLE spots to update key dsitributions.

**Comment by Sweepr** [comment] 2015-12-29 14:45
Could you see if you have table locks?

Maybe you could monitor using mysqladmin proc -i 5 and log to file to see what is going on on the background while this happens.

My guess the spots table is having table locks.

**Comment by mesa57** [comment] 2015-12-29 14:46
Hmmz, table locks do not let MySql to do a table scan instead of using spot_index_3 for sorting on reversestamp.

**Comment by Sweepr** [comment] 2015-12-29 14:51
Since the spots table is the only table using MyIsam a table lock may be the reason why it's slow one time and the other time it's not.

Problem is that inserting data into that table results in a table lock and in the meantime no other sql query can perform any action because the whole table is locked.

Depending what is happening on the background.

Try setting this in my.cnf

[mysqld]
concurrent_insert = ALWAYS

or

[mysqld]
concurrent_insert = 2

Adding new rows to a MyISAM table bypasses table locking only in this circumstance. You will have to experiment with adding rows to the table while updating fulltext indexed columns in another row of the table.

**Comment by Sweepr** [comment] 2015-12-29 14:54
The MyISAM storage engine supports concurrent inserts. This feature allows SELECT statements to be executed during INSERT operations, reducing contention.

Whether concurrent inserts can be used or not depends on the value of the concurrent_insert server system variable:

    NEVER (0) disables concurrent inserts.
    AUTO (1) allows concurrent inserts only when the target table has no free blocks (no data in the middle of the table has been deleted after the last OPTIMIZE TABLE). This is the default.
    ALWAYS (2) always enables concurrent inserts.

**Comment by Rouzax** [comment] 2015-12-29 15:02
@mesa57 
I've done Analyse several times already and it does not seem to make any difference

@Sweepr 
I've also tested with the retrieve scheduled task disabled and that does not make any difference so my conclusion would be that `concurrent_insert = 2` would not help. Right?

**Comment by Sweepr** [comment] 2015-12-29 15:09
@Rouzax, that's correct.. 

For my understanding:
You still experience the same issue without any INSERTS taking place now and there is only one user which is you and only SELECT queries at this time?

**Comment by Sweepr** [comment] 2015-12-29 15:11
Be sure to restart the SQL server in order for the value to become active.

**Comment by Rouzax** [comment] 2015-12-29 15:12
Yes I'm am the only user and have also experienced it while the retrieve schedule was disabled and after a DB restart so there could be no sessions remaining.

Here is the output of the mysqladmin proc -i 5
[MySQL.txt](https://github.com/spotweb/spotweb/files/74042/MySQL.txt)

**Comment by mesa57** [comment] 2015-12-29 15:12
If you look at the query there is : ORDER BY s.reversestamp ASC LIMIT 26 OFFSET 25;
In the slow situation, mysql did a table scan over the spots table.
In the fast situation it did a index scan on idx_spots_3 which is the index on reversestamp.

So why is Mysql's query optimizer failing to do its job ?

**Comment by Rouzax** [comment] 2015-12-29 15:14
Just ran a retrieve.php manually and no it it fast again :confused: 
```
C:\inetpub\wwwroot\spotweb>php retrieve.php
Last retrieve at 12/29/15 16:05:51
Retrieving new Spots from server news.cheapnews.eu...
Appr. Message count:    2201152
First message number:   5698531
Last message number:    7899683
Current article number: 7899680

Retrieving 7899680 till 7899684 (parsed: 2, in DB: 1, signed: 2, invalid: 0, rtn
tn.skip: 0, mod: 0, full: 2, total: 3) in 0.16 seconds
Processed a total of 3 spots
Finished retrieving spots.

Calculating how many spots are new, done.
Last retrieve at 12/29/15 16:12:36
Retrieving new comments from server news.cheapnews.eu...
Appr. Message count:    14122316
First message number:   2406383
Last message number:    16528699
Current article number: 16528545

Retrieving 16528545 till 16528700, found 155 comments in 0.35 seconds
Processed a total of 155 comments
Finished retrieving comments.

Last retrieve at 12/29/15 16:12:37
Retrieving new reports from server news.cheapnews.eu...
Appr. Message count:    115976
First message number:   1
Last message number:    115977
Current article number: 115975

Retrieving 115975 till 115978, found 3 reports in 0.02 seconds
Processed a total of 3 reports
Finished retrieving reports.

Blacklist not modified, no need to update
Whitelist not modified, no need to update
Expiring debuglog entries, if any, done.
Starting to create statistics
Finished creating statistics


C:\inetpub\wwwroot\spotweb>
```

**Comment by Sweepr** [comment] 2015-12-29 15:19
Maybe you could log slow_query_log for a while by adding the following to your my.cnf file:

slow-query-log=1
slow-query-log-file=/var/log/mysql-slow.log

And again a SQL restart is needed, see if this yields any bottleneck queries.

**Comment by Rouzax** [comment] 2015-12-29 15:24
@Sweepr 
I already have that and that is where I found the query

After running retrieve.php a few times manually it is slow again, with queries filling up the slow log
```
# Time: 151229 16:23:55
# User@Host: root[root] @ localhost [::1]  Id:    68
# Query_time: 25.030925  Lock_time: 0.000000 Rows_sent: 51  Rows_examined: 6463783
SET timestamp=1451402635;
SELECT s.id AS id,
												s.messageid AS messageid,
												s.category AS category,
												s.poster AS poster,
												l.download as downloadstamp, 
												l.watch as watchstamp,
												l.seen AS seenstamp,
												s.subcata AS subcata,
												s.subcatb AS subcatb,
												s.subcatc AS subcatc,
												s.subcatd AS subcatd,
												s.subcatz AS subcatz,
												s.title AS title,
												s.tag AS tag,
												s.stamp AS stamp,
												s.moderated AS moderated,
												s.filesize AS filesize,
												s.spotrating AS rating,
												s.commentcount AS commentcount,
												s.reportcount AS reportcount,
												s.spotterid AS spotterid,
 												s.editstamp AS editstamp,
 												s.editor AS editor,
												f.verified AS verified,
												COALESCE(bl.idtype, wl.idtype, gwl.idtype) AS idtype
												
									 FROM spots AS s  LEFT JOIN spotstatelist AS l on ((s.messageid = l.messageid) AND (l.ouruserid = 3)) 
									 LEFT JOIN spotsfull AS f ON (s.messageid = f.messageid) 
									 LEFT JOIN spotteridblacklist as bl ON ((bl.spotterid = s.spotterid) AND ((bl.ouruserid = 3) OR (bl.ouruserid = -1)) AND (bl.idtype = 1))
									 LEFT JOIN spotteridblacklist as wl on ((wl.spotterid = s.spotterid) AND ((wl.ouruserid = 3) AND (wl.idtype = 2)))
									 LEFT JOIN spotteridblacklist as gwl on ((gwl.spotterid = s.spotterid) AND ((gwl.ouruserid = -1) AND (gwl.idtype = 2)))  WHERE (bl.spotterid IS NULL)  AND (NOT ((s.Category = 0) AND (s.subcatz = 'z3|')))
									 ORDER BY s.reversestamp ASC LIMIT 51 OFFSET 150;
```

**Comment by mesa57** [comment] 2015-12-29 15:26
It is a long shot, but try repairing the indices on the spots table by issueing a repair table command.

**Comment by Rouzax** [comment] 2015-12-29 15:27
Running that query in MySQL will also take 24,5 seconds
51 row(s) returned - 24.516 sec / 0.000 sec

**Comment by Rouzax** [comment] 2015-12-29 15:32
`16:29:37	repair table spots	1 row(s) returned	95.953 sec / 0.000 sec`
Still slow at the moment also after a restart of MySQL.

**Comment by mesa57** [comment] 2015-12-29 15:44
Tried exact query here, returns in 0.15 secs. And uses idx_spots_3 as per explain.
There must be something wrong with you're database.

**Comment by Rouzax** [comment] 2015-12-29 15:50
Already tried with several reinstalls of Spotweb with a new database so far it hasn't helped.
Will try with a complete removal of MySQL 5.6 and reinstall it.

**Comment by mesa57** [comment] 2015-12-29 15:58
To test you could change you're test query and force the index to be used by changing the FROM line into : 
FROM spots  AS s  force index for order by (idx_spots_3)

**Comment by Rouzax** [comment] 2015-12-29 16:13
* So just reinstalled MySQL 5.6.28 completely
* Created an empty spotweb database
* did the install.php
* with a completely empty DB it is fast :smile: 

Should I do a manual retrieve to get all the spots or should I do an upgrade-db.php first?

**Comment by Sweepr** [comment] 2015-12-29 16:19
upgrade-db won't be neseccary since it's a fresh install and nothing changed.

You could start retrieving

**Comment by Rouzax** [comment] 2015-12-29 16:21
Retrieving
```
C:\inetpub\wwwroot\spotweb>php -v
PHP 5.6.16 (cli) (built: Nov 25 2015 18:52:33)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies

C:\inetpub\wwwroot\spotweb>php retrieve.php
Last retrieve at 01/01/70 01:00:00
Retrieving new Spots from server news.cheapnews.eu...
Appr. Message count:    2201192
First message number:   5698531
Last message number:    7899723
Current article number: 5698531

Retrieving 5698531 till 5703532 (parsed: 5001, in DB: 0, signed: 0, invalid: 156
7, rtntn.skip: 0, mod: 0, full: 0, total: 5001) in 2.44 seconds
Retrieving 5703532 till 5708533 (parsed: 5001, in DB: 0, signed: 0, invalid: 5,
rtntn.skip: 0, mod: 0, full: 0, total: 5001)
```
With the default settings 
![image](https://cloud.githubusercontent.com/assets/4103090/12037602/96c6d9e2-ae50-11e5-860b-1e0e3836340e.png)

**Comment by mesa57** [comment] 2015-12-29 18:13
Interesting. One of you're query's reported about 1.185.000 rows in the spot table, while cheapnews returns only aprox. 4.400.000 headers.

**Comment by Rouzax** [comment] 2015-12-29 18:26
I think it might be upgrade-db.php, I didn't run it yet and now I also have a mobile template I previously didn't see. Will do some testing and let you know.

**Comment by mesa57** [comment] 2015-12-29 18:53
Correction, it reports 2201152. Half of those are prob. invalid spots.

**Comment by Rouzax** [comment] 2015-12-29 21:18
Hmm, after the retrieve completed, I lost the mobile template again. 
For now the index seems to be fast,  try to test some more tomorrow.

**Comment by Rouzax** [comment] 2015-12-30 10:43
Stil fast, I should try to run upgrade-db.php but to be honest I glad it is working like it should :smile:

**Comment by Sweepr** [comment] 2015-12-30 10:46
It's really weird, if this is true i'm wondering what it is that upgrade-db.php is doing to the DB to make it slow.

**Comment by mesa57** [comment] 2015-12-30 10:48
It is not proven (yet) that upgrade-db was the root cause. Maybe we'll never know.

**Comment by Sweepr** [comment] 2015-12-30 10:53
No, not unless further testing can be performed, maybe Rouzax can create another instance under the same circumstances to see if this can be replicated.

**Comment by Rouzax** [comment] 2015-12-31 09:57
So I created a second instance of Spotweb to test.
* Created an empty Spotweb install.
* With no spots it is fast obviously
* With no spots I still have the Mobile web page.
![image](https://cloud.githubusercontent.com/assets/4103090/12063310/d6bd9056-afac-11e5-8665-616811a297ac.png)
* now starting the retrieve.php manually, when it is finished I will run a upgrade-db.php and report back.
```
C:\inetpub\wwwroot>git clone https://github.com/spotweb/spotweb.git c:\inetpub\w
wwroot\test
Cloning into 'c:\inetpub\wwwroot\test'...
remote: Counting objects: 30744, done.
remote: Total 30744 (delta 0), reused 0 (delta 0), pack-reused 30744
Receiving objects: 100% (30744/30744), 15.29 MiB | 5.29 MiB/s, done.
Resolving deltas: 100% (16670/16670), done.
Checking connectivity... done.

C:\inetpub\wwwroot>cd test

C:\inetpub\wwwroot\test>php -v
PHP 5.6.16 (cli) (built: Nov 25 2015 18:52:33)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies

C:\inetpub\wwwroot\test>php retrieve.php
Last retrieve at 01/01/70 01:00:00
Retrieving new Spots from server news.cheapnews.eu...
Appr. Message count:    2203316
First message number:   5698531
Last message number:    7901847
Current article number: 5698531

Retrieving 5698531 till 5703532 (parsed: 5001, in DB: 0, signed: 0, invalid: 156
7, rtntn.skip: 0, mod: 0, full: 0, total: 5001) in 2.41 seconds
Retrieving 5703532 till 5708533 (parsed: 5001, in DB: 0, signed: 0, invalid: 5,
rtntn.skip: 0, mod: 0, full: 0, total: 5001) in 3.52 seconds
Retrieving 5708533 till 5713534
```

**Comment by Rouzax** [comment] 2015-12-31 10:20
Somewhere while retrieving the spots I loose the mobile template
![image](https://cloud.githubusercontent.com/assets/4103090/12063503/3572cf8c-afb0-11e5-9149-6089d7ad2141.png)
and get an error message on my mobile while loading
![image](https://cloud.githubusercontent.com/assets/4103090/12063511/4ecd282e-afb0-11e5-8cc4-3c2234f7d162.png)
Then it redirects to the default desktop page.
![image](https://cloud.githubusercontent.com/assets/4103090/12063518/6659448c-afb0-11e5-8697-2c32887c9335.png)

**Comment by mesa57** [comment] 2015-12-31 10:38
Looks to me like a separate bug.

**Comment by Rouzax** [comment] 2015-12-31 10:39
@mesa57 I think so but I'm trying to describe to process as much a possible :smile:

**Comment by Rouzax** [comment] 2015-12-31 12:09
After the initial retrieve everything is still fast, will try to do a manual retrieve several times and see how it keeps responding. Afterwards I will start the upgrade-db.php to see if there are effects.

**Comment by Rouzax** [comment] 2015-12-31 12:20
I can't recreate the slow performance with the test instance. It looks like the fresh install of MySQL 5.6 did the trick.
Should I create a separate issue for the loss of the mobile template?

**Comment by dsadsdadsadsadsds** [comment] 2016-02-06 09:54
Next time it would / might be interesting to check if the sorting / working memory of MySQL is enough -- it neds this memory to sort the indexes properly.

For larger installations i would always suggest PostgreSQL

**Comment by Rouzax** [comment] 2016-02-06 10:08
@dsadsdadsadsadsds: Where can I check that?

**Comment by dsadsdadsadsadsds** [comment] 2016-02-06 10:40
I'm no expert on MySQL but as your query statistics show that a temp table was created on disk, it might be not enough. Just use PostgreSQL though :laughing:

**Comment by mesa57** [comment] 2016-03-21 21:16
Closing issue.

**Comment by jbogers** [comment] 2016-04-25 10:11
Please reopen as the issue is still present.
@mesa57 , the 'FORCE INDEX' fix you provided resolves the issue, indicating that the current database layout 'confuses' the MySQL optimizer. I hope the index forcing can be added to the standard query for MySQL in this case.

**Comment by mesa57** [comment] 2016-04-25 10:58
Reopend as enhancement request.

**Comment by mesa57** [comment] 2016-04-25 14:38
@Rouzax Which graphical query analyzer did you use ?

**Comment by Rouzax** [comment] 2016-04-25 15:08
The default Oracle Workbench https://www.mysql.com/products/workbench/

**Comment by mesa57** [comment] 2016-04-25 19:03
Ok, thx. Must be sleeping, did not see the option.

**Comment by MrLurch81** [comment] 2016-05-01 15:19
For me this was fixed by adding the index on the left join of spotstatelist:
`LEFT JOIN spotstatelist AS l force index(idx_spotstatelist_1)`
After that, opening the webpage is instant. (Synology)

**Comment by mesa57** [comment] 2016-05-01 18:31
spotstatelist is the table where is tracked what spots you opened, downloaded etc.
If you deselect all those options and empty the table, spotweb won't use it.
However, it seems to me, that you're database needs an analyze.

**Comment by MrLurch81** [comment] 2016-05-01 20:43
Just performed an ANALYZE of all tables to be sure.
Indeed there is a relation to the spotstatelist, as you can see it currently contains 5 records for the user account.
This is the EXPLAIN of the original query:
![image](https://cloud.githubusercontent.com/assets/1702832/14944053/297fb714-0fe9-11e6-9834-da8f96580691.png)

When I either:
- keep the original query but change the user account to a non-existing user (ouruserid that does not have records in spotstatelist)

OR
- use the current user, but add the `force index(idx_spotstatelist_1)` to the query

The EXPLAIN changes to:
![image](https://cloud.githubusercontent.com/assets/1702832/14944076/ad5a4810-0fe9-11e6-9c2e-003f6022c624.png)

This dramatically decreases the number of rows involved in the query of table 's' (spots) and results in instantaneous responses.
This corresponds to the EXPLAINs as reported by @Rouzax in the opening post.

Update: by inserting only 1 row for another (anonymous/admin) user into spotstatelist, the MySQL optimizer is triggered to use the index idx_spotstatelist_1 by itself, even when using the default Spotweb query. So, the `force index(idx_spotstatelist_1)` only seems to be needed to 'help' the optimizer when running a one-user system with spotstate logging enabled?

**Comment by mesa57** [comment] 2016-05-02 17:50
As spotstatelist only contains 5 rows, it never can be the bottleneck. A tablescan is not expensive.
However, in you're last explain I see that suddenly also idx_spots_3 is used on the main spots table.
That delivers an enormous performance enhancement.

**Comment by MrLurch81** [comment] 2016-05-02 22:57
Yes, although it might not seem like a bottleneck if you only look at the limited number of records currently in `spotstatelist`, the consequence of performing a full table scan (type = 'ALL') on `spotstatelist`, is that it also prevents the use of indexes of the `spots` table. This leads to the use of a temporary table (`using temporary`) and an additional pass for the filesort (`using filesort`) on the spots table, both of which are expensive due to the size of that table (nearly 1,3 million records).

Apparently, if we can trigger the use of the index `idx_spotstatelist_1` (either by adding an extra record for another user into `spotstatelist`, or by explicitly using `force index`), the optimizer notices that it is better off using `idx_spotstatelist_1`, which then also enables it to use `idx_spots_3` on `spots`.
Unfortunately, I can't explain why adding the extra record for another user to `spotstatelist` makes the optimizer suddenly realize that it should use the `idx_spotstatelist_1`. :-( Perhaps there is some minimum number of records before the optimizer can really optimize the execution plan.

**Comment by mesa57** [comment] 2016-05-03 07:13
Anyway, the query shown is not specific for MySql so adding 'force index' is not an option as that would not work in Postgreslq or SQLite.
A solution should be independent of the DB type used.

**Comment by mesa57** [comment] 2016-05-05 14:53
Not only spotstatelist, but also spotsfull (both left joined) can pose a problem. A force index only helps when sorting is on reversestamp and you know that it is always like that (which isn't).
I've tried to get the left joins with spotstatelist and spotsfull out of the main query to give the optimizer less confusion. The resulting query looks like this : 


```
select 	x.*, 
	                        f.verified ,
	                        l.download as downloadstamp, 
	                        l.watch as watchstamp,
	                        l.seen AS seenstamp
                            from 
                            (SELECT s.id AS id,
								    s.messageid AS messageid,
								    s.category AS category,
								    s.poster AS poster,
								    s.subcata AS subcata,
								    s.subcatb AS subcatb,
								    s.subcatc AS subcatc,
								    s.subcatd AS subcatd,
								    s.subcatz AS subcatz,
								    s.title AS title,
								    s.tag AS tag,
								    s.stamp AS stamp,
								    s.moderated AS moderated,
								    s.filesize AS filesize,
								    s.spotrating AS rating,
								    s.commentcount AS commentcount,
								    s.reportcount AS reportcount,
								    s.spotterid AS spotterid,
 								    s.editstamp AS editstamp,
 								    s.editor AS editor,
								    COALESCE(bl.idtype, wl.idtype, gwl.idtype) AS idtype
								    
								    FROM spots AS s LEFT JOIN spotteridblacklist as bl ON ((bl.spotterid = s.spotterid) AND ((bl.ouruserid = 1) OR (bl.ouruserid = -1)) AND (bl.idtype = 1))
								    LEFT JOIN spotteridblacklist as wl on ((wl.spotterid = s.spotterid) AND ((wl.ouruserid = 1) AND (wl.idtype = 2)))
								    LEFT JOIN spotteridblacklist as gwl on ((gwl.spotterid = s.spotterid) AND ((gwl.ouruserid = -1) AND (gwl.idtype = 2)))  WHERE (bl.spotterid IS NULL) 
								    ORDER BY s.reversestamp ASC LIMIT 26 OFFSET 0
                            ) as x
                            LEFT JOIN spotsfull AS f ON (f.messageid = x.messageid) 
							LEFT JOIN spotstatelist AS l on ((x.messageid = l.messageid) AND (l.ouruserid = 3))
```

The code in dao base spot would become : 

```
		/*
		 * Run the query with a limit always increased by one. this allows us to 
		 * check whether any more results are available
		 */
        $query = "select 	x.*, 
	                        f.verified ,
	                        l.download as downloadstamp, 
	                        l.watch as watchstamp,
	                        l.seen AS seenstamp
                            from 
                            (SELECT s.id AS id,
								    s.messageid AS messageid,
								    s.category AS category,
								    s.poster AS poster,
								    s.subcata AS subcata,
								    s.subcatb AS subcatb,
								    s.subcatc AS subcatc,
								    s.subcatd AS subcatd,
								    s.subcatz AS subcatz,
								    s.title AS title,
								    s.tag AS tag,
								    s.stamp AS stamp,
								    s.moderated AS moderated,
								    s.filesize AS filesize,
								    s.spotrating AS rating,
								    s.commentcount AS commentcount,
								    s.reportcount AS reportcount,
								    s.spotterid AS spotterid,
 								    s.editstamp AS editstamp,
 								    s.editor AS editor,
								    COALESCE(bl.idtype, wl.idtype, gwl.idtype) AS idtype
								    " . $extendedFieldList . "
								    FROM spots AS s " . 
								    $additionalTableList . 
								    $additionalJoinList . 
							       "LEFT JOIN spotteridblacklist as bl ON ((bl.spotterid = s.spotterid) AND ((bl.ouruserid = " . $this->_conn->safe( (int) $ourUserId) . ") OR (bl.ouruserid = -1)) AND (bl.idtype = 1))
								    LEFT JOIN spotteridblacklist as wl on ((wl.spotterid = s.spotterid) AND ((wl.ouruserid = " . $this->_conn->safe( (int) $ourUserId) . ") AND (wl.idtype = 2)))
								    LEFT JOIN spotteridblacklist as gwl on ((gwl.spotterid = s.spotterid) AND ((gwl.ouruserid = -1) AND (gwl.idtype = 2))) " .
								    $criteriaFilter . "
								    ORDER BY " . $sortList . " LIMIT " . (int) ($limit + 1) ." OFFSET " . (int) $offset ."
                            ) as x
                            LEFT JOIN spotsfull AS f ON (f.messageid = x.messageid) 
							LEFT JOIN spotstatelist AS l on ((x.messageid = l.messageid) AND (l.ouruserid = " . $this->_conn->safe( (int) $ourUserId) . "))" ;

 	$tmpResult = $this->_conn->arrayQuery($query);

```

**Comment by mesa57** [comment] 2016-05-05 19:58
Btw. don't use this query in you're production spotweb. There are some issues with constructing fts query's (old errors) which popup then (duplicate field names in subquery).

**Comment by mesa57** [comment] 2016-05-06 09:05
Ok, I have commited some changes to my spotweb fork to solve this issue.
It includes the recrafted query, and also the changes needed in mysql fts query construction.
You are all invited to test unless you make use of postgresql or SQLite. Those haven't been tested (yet)

**Comment by mesa57** [comment] 2016-05-06 19:54
Grmbl. PostgreSQL is even worse. A normal query on a spot database size 200.000 takes 1 min 45s.
Has somebody ever used PostgreSQL ???
B.t.w. PostgreSQL was much faster in loading the database with spots and comments ...

**Comment by mesa57** [comment] 2016-05-07 11:20
Last commit includes changes for PostgreSQL. 
All should work fine now for MySQL, SQLite and PostgreSQL. :smile:

**Comment by mesa57** [comment] 2016-05-11 18:20
Is there anyone who is willing to test?

**Comment by Rouzax** [comment] 2016-05-12 09:48
@mesa57, I don't have any performance issue currently.

**Comment by mesa57** [comment] 2016-05-12 09:53
Yes, I understand. But it would be nice if you would test the new code.

**Comment by MrLurch81** [comment] 2016-05-12 09:59
I can probably give it a go tomorrow (Syno + MySQL/MariaDB), after removing the previous workaround (extra entry in spotstatelist). Will let you know...

**Comment by mesa57** [comment] 2016-05-12 14:18
Thanks !

**Comment by MrLurch81** [comment] 2016-05-13 11:56
Test performed on Syno (DSM6), MySQL/MariaDB:

1. Removed the workaround of extra entry in spotstatelist: the performance was terrible again (repo spotweb/spotweb).
2. Switched to your fork, performance still bad (as expected).
3. Checkout e02356af478e93931a08f8cc57237a229dd7dab4, performance is excellent! 
4. Switched back to spotweb/spotweb, performance is bad again.

So, for me, your commit solves the issue. Thanks!

**Comment by mesa57** [comment] 2016-05-13 12:32
Thanks for testing :smile:

**Comment by MrLurch81** [comment] 2016-05-16 12:42
After working for some days with e02356af478e93931a08f8cc57237a229dd7dab4, I noticed that opening a few of the Quick Links result in SQL errors:
```
"New": SpotWeb v0.67.28.31 on PHP v5.6.20 crashed 42S22: 1054: Unknown column 'l.seen' in 'where clause'
"Watchlist": ... Unknown column 'l.watch' in 'where clause'
"Downloaded": ... Unknown column 'l.download' in 'where clause'
```
This seems to be caused by your first commit: 42072e3a63d46a36664a14a51fc1952c6beffd45

**Comment by mesa57** [comment] 2016-05-16 12:47
Thanks for reporting. Can you give me an example of a non working quicklink ?

**Comment by MrLurch81** [comment] 2016-05-16 13:09
These are the MySQL statements fired when clicking the default "Downloaded" quicklink (sessionid replaced by 'yyy'): [mysql.zip](https://github.com/spotweb/spotweb/files/266126/mysql.zip)

When I run the last statement manually in MySQL Workbench, it gives the same error: `Error Code: 1054. Unknown column 'l.download' in 'where clause'`

**Comment by mesa57** [comment] 2016-05-16 14:12
This breaks the whole principle of getting the left joins out of the main query (which in multiple cases causes the performance problem).
I am afraid I have to revert this change and leave the problem as unsolveable.

**Comment by derkens** [comment] 2016-05-20 07:20
ok, first off, this may sound ridiculous. I've lost my database due to harddrive failure.
So I've retreived a new database. After the retreive everything in spotweb was slow. Index load took forever, and infinite scroll took a long time to load.
I've created a second user with the same rights, logged out, logged in as the second user, and all was quick to load.
I have not made any tests, and half the posts above I don't understand. This may not be related at all, just wanted to leave it here....

**Comment by mesa57** [comment] 2016-05-20 08:38
The problem is known and specially occurs on low filled database.
The MySQL query optimizer and also the PostGreSQL optimize fail when a huge table is left left joined with empty or almost empty tables. SQLite appears not to have this problem,

**Comment by mesa57** [comment] 2016-05-20 18:33
New commit on mesa57/spotweb-master
This time I created different query's for MySQL, PostgreSQL and SQLite as there is no solution which fits them all. 
@MrLurch81 : the quick links should also work :smile:

**Comment by MrLurch81** [comment] 2016-05-22 11:29
MySQL/MariaDB on Syno DSM 6:

1. Reverted workaround (extra entries in `spotstatelist`) to make system slow again on origin/master.
2. Checkout to 7fe9d47b1bd882591552948fa0872a6333ac1e94
3. Opening Spotweb gives error: `SpotWeb v0.67.28.31 on PHP v5.6.20 crashed 42000: 1176: Key 'messageid_UNIQUE' doesn't exist in table 'f'`
4. Replaced `messageid_UNIQUE` by `idx_spotsfull_1` in `\lib\dao\Mysql\Dao_Mysql_Spot.php:163`
5. Everything seems to work fine and fast now (including the quick links)!

**Comment by mesa57** [comment] 2016-05-22 12:25
Ok, thanks, I will do a correction on dao_mysql_spot this afternoon.

**Comment by mesa57** [comment] 2016-05-22 13:00
Correction done. Somehow the index had a different name in my test environment.

**Closed** 2016-07-26 18:05 UTC
Labels: Deployed, enhancement

**Comment by Rouzax** [comment] 2017-02-27 10:59
@mesa57 
I've just restored my spotweb database on a new machine and it seems that it is now again slow.

**Comment by Rouzax** [comment] 2017-02-27 11:02
@mesa57 Never mind, it was because my NZBGet server also changed which I hadn't updated yet in the settings.

**Comment by Rouzax** [comment] 2017-03-03 14:18
@mesa57 
Sorry I do have a few slow queries again, not as slow as before.
When I scroll through the spots the loading will sometimes take more than 5 seconds.

Query in question
```
C:\Program Files\MySQL\MySQL Server 5.7\bin\mysqld.exe, Version: 5.7.17-log (MySQL Community Server (GPL)). started with:
TCP Port: 3306, Named Pipe: (null)
Time                 Id Command    Argument
# Time: 2017-03-03T14:06:38.521327Z
# User@Host: root[root] @ localhost [::1]  Id:    33
# Query_time: 6.234425  Lock_time: 0.000000 Rows_sent: 101  Rows_examined: 301665
use spotweb;
SET timestamp=1488549998;
SELECT s.id AS id,
												s.messageid AS messageid,
												s.category AS category,
												s.poster AS poster,
												l.download as downloadstamp, 
												l.watch as watchstamp,
												l.seen AS seenstamp,
												s.subcata AS subcata,
												s.subcatb AS subcatb,
												s.subcatc AS subcatc,
												s.subcatd AS subcatd,
												s.subcatz AS subcatz,
												s.title AS title,
												s.tag AS tag,
												s.stamp AS stamp,
												s.moderated AS moderated,
												s.filesize AS filesize,
												s.spotrating AS rating,
												s.commentcount AS commentcount,
												s.reportcount AS reportcount,
												s.spotterid AS spotterid,
 												s.editstamp AS editstamp,
 												s.editor AS editor,
												f.verified AS verified,
												COALESCE(bl.idtype, wl.idtype, gwl.idtype) AS idtype
												
									 FROM spots AS s  LEFT JOIN spotstatelist AS l FORCE INDEX FOR JOIN (idx_spotstatelist_1) ON ((s.messageid = l.messageid) AND (l.ouruserid = 3)) 
									 LEFT JOIN spotsfull AS f FORCE INDEX FOR JOIN (idx_spotsfull_1) ON (s.messageid = f.messageid)  
									 LEFT JOIN spotteridblacklist as bl FORCE INDEX FOR JOIN (idx_spotteridblacklist_1) ON ((bl.spotterid = s.spotterid) AND ((bl.ouruserid = 3) OR (bl.ouruserid = -1)) AND (bl.idtype = 1))
									 LEFT JOIN spotteridblacklist AS wl FORCE INDEX FOR JOIN (idx_spotteridblacklist_1) ON ((wl.spotterid = s.spotterid) AND ((wl.ouruserid = 3) AND (wl.idtype = 2)))
									 LEFT JOIN spotteridblacklist AS gwl FORCE INDEX FOR JOIN (idx_spotteridblacklist_1) ON ((gwl.spotterid = s.spotterid) AND ((gwl.ouruserid = -1) AND (gwl.idtype = 2))) 
  WHERE (bl.spotterid IS NULL)  AND (((s.category = 0) AND (s.subcatz = 'z0|') AND ( ((s.subcata = 'a9|') )  AND  ((s.subcatc LIKE '%c11|%') ) ) ))  AND (NOT ((s.Category = 0) AND (s.subcatz = 'z3|')))
									 ORDER BY s.reversestamp ASC LIMIT 101 OFFSET 800;
```
![image](https://cloud.githubusercontent.com/assets/4103090/23554084/e4a6683c-0023-11e7-868a-eb7e571f7518.png)
![image](https://cloud.githubusercontent.com/assets/4103090/23554253/933f456c-0024-11e7-8029-408f09277a54.png)

**Comment by mesa57** [comment] 2017-03-03 15:52
Nothing wrong with this. The selection on english language (C11) included in the query takes a long time.

**Comment by Rouzax** [comment] 2017-03-03 16:13
aah thanks, than no worries 😃
