### ISSUE TITLE
new retrieve resets filter counts?

### ISSUE THREAD

**Issue by Mickroz** [spotweb/spotweb#307] opened 2017-05-06 06:57 UTC
I think a new retrieve resets the filter counts, i got a notification that a filter has 1 spot at 6:00, but after the retrieve at 8:00 ( i looked at 8:15 or something) there is no new count for that filter, the spot is there though.
Also its says 23 new, but only shows 8, and if i add up all the filter counts, 8 is the correct number.
If i count back trough the latest spots till 23 as if thats the number of new spots since my last visit, the time is off also.
Weird problem.

**Comment by mesa57** [comment] 2017-05-06 07:23
Nothing should have been changed in that respect.

**Comment by Mickroz** [comment] 2017-05-06 08:01
ok, blegh since i had to install a new spotweb, i am coming across all sort of weird problems.

**Comment by Mickroz** [comment] 2017-05-06 17:53
here i don't even have filter counts, but i have new posts, even when clicking New.
![spotweb](https://cloud.githubusercontent.com/assets/994362/25774729/9ba71420-3295-11e7-87e2-1d3f49d7e229.png)

**Comment by mesa57** [comment] 2017-05-06 17:58
Filtercounts are on user level (logged on user). As they are only added over time, I guess errors can creep in.
What is used for the count / new buttpn I don't know.

**Comment by Mickroz** [comment] 2017-05-06 18:35
i think i found my problem, i got alot of cache problems in my error_log because of wrong user, so i changed that, and hopefully it will fix this too as it uses the cache as far as i can tell, those files are a mess :P

**Comment by mesa57** [comment] 2017-05-07 12:01
Ok, the new count on filters is reset when you visit spotweb with a new session which is newer more then 15 mins. then the previous one. If initiated earlier, the new count will not be reset.

**Comment by Mickroz** [comment] 2017-05-07 12:44
I got a retrieve every 2 hours, I will visit my spotweb and then mark as read anyway, but the count after a night seems low, have to check a few days and see if I got any cache problems.

**Comment by mesa57** [comment] 2017-05-07 18:45
Imho has nothing to do with the (file) cache.

**Comment by mesa57** [comment] 2017-05-08 16:14
If you have strange results you could reset the filter counts cache by emptying the filtercounts table.
On the next retrieve the table will be build again. Of course then ALL spots are marked as new for you.

**Comment by Mickroz** [comment] 2017-05-08 20:45
Maybe I will, can't seem to find what is the problem, it "looks" like someone is visiting my spotweb on my account, but I changed my password, so that "shouldn't" be a problem.

**Comment by Mickroz** [comment] 2017-05-10 06:41
found the culprit, after deselecting "Automatic mark spots as read after each visit?" it works again like before.

**Comment by mesa57** [comment] 2017-05-10 13:52
Ok, nice 😄

**Comment by Mickroz** [comment] 2017-05-10 13:54
only the strange part is, that it sees a retrieve as a visit, so thats should be fixed then.

**Comment by mesa57** [comment] 2017-05-10 14:08
No, that is as designed. But it could be an optional enhancement. However, I am not in favor of adding more options (basicly saying : use the product as-is, or don't use it).

**Comment by Mickroz** [comment] 2017-05-10 14:17
Ok, then the design is flawed, as a retrieve made by the php cli on my server shouldn't even count towards a visit, since this isn't even done by me or my ip address.

**Comment by Cafun** [comment] 2017-05-10 16:15
I agree with Mickroz, a retrieve made by php cli should not mark it as a visit.

**Comment by mesa57** [comment] 2017-05-10 17:03
Retrieve does not count that as a visit. A visit is recorded at user level. Retrieve updates only the high water mark to the first spot retrieved. For a user then the new spots mark is then calculated from the last visited mark - the retrieve mark. If retrieve wouldn't set the mark the nr. of new spots would only grow. 
The retrieve water mark is also for all users and not specific for one.

**Comment by Mickroz** [comment] 2017-05-10 17:23
if i wouldn't log in for 14 hours, i should have 14 hours of spots marked as new, even if i do a retrieve every 2 hours on the cli and they should be marked read after i press "mark everything as read", this is the case now, but if i enable the "Automatic mark spots as read after each visit?" i expect to have the same result but i don't have to press the "mark everything as read" when im done visiting, but this is not the case, it marks only the posts that are new since the last retrieve, all posts before that are marked as read, even though i haven't logged in for 14 hours.
So either this has to be fixed in spotweb master, or my spotweb is bugged somehow, or i don't understand how this option should suppose to work and is wrongly named.

**Comment by mesa57** [comment] 2017-05-10 17:30
Wrongly named I agree. It should be  "Automatic mark spots as read at each visit which is later then 15 minutes ago"

**Comment by Mickroz** [comment] 2017-05-10 17:50
Yeah, i had a bad sql backup, so i completely setup spotweb from scratch again, i guess i didn't had this option tagged before, and tagged it with the new install.
but still, if i don't visit spotweb for 14 hours, i should see new spots for the past 14 hours, and not the new spots since the last retrieve, which in my case is 2 hours, regardless of that option.

**Comment by Mickroz** [comment] 2017-05-11 06:18
after 12 hours only the spots from the last retrieve are marked as new, everything before that is marked as read.
So if i am the only one experiencing this, i guess my settings are wack, i will deactivate this option and let it be.

**Comment by Cafun** [comment] 2017-05-14 07:39
I looked into this again and it seems like it's working as expected in my setup. So it will only mark them as read when I visited the site itself.

**Comment by mesa57** [comment] 2017-05-14 09:24
Even I cannot detect any anomalies on my test system. 
Maybe  @Mickroz can describe the steps to reproduce his issue.

**Comment by Mickroz** [comment] 2017-05-14 09:42
It works on my setup, just not on my account, there are some settings different between the accounts, but nothing that affects marking posts as read.
The only thing different is that I use the api for couchpotato, but that only runs at 6:00 every day.
I cannot reproduce it on other accounts, I will get back with my settings when im at home.

**Comment by Mickroz** [comment] 2017-05-14 14:49
these preferences are not ticked:

- Track what you're watching
- Automatic mark spots as read after each visit?
- Shall we keep track of a watchlist?
- Show a checkbox next to each spot for multiplex NZB file download?

these are turned on on the other account.

**Comment by mesa57** [comment] 2017-05-14 17:25
Only Automatic mark spots as read after each visit has influence. 
If not checked, it should keep the last read mark untoched until you click the 'mark all spots as read' button (in my system it does).
Btw. have you tried to empty the filtercounts table ? Or on a multiuser system delete the rows for you're userid ?

**Comment by Mickroz** [comment] 2017-05-14 17:39
And thats how its working now.
I have emptied the filtercount table, checked the setting and saved, now have to wait 2,5 hours to see if what happens.
btw is the visit session ip based? or else i can check with another account how many new spots there are after half an hour or so.

**Comment by mesa57** [comment] 2017-05-14 17:43
The visit is session based, the session is registered in the sessions table and the key is stored in a cookie. 
If the cookie is not present, spotweb will create a new session in the sessions table.

**Comment by Mickroz** [comment] 2017-05-14 17:45
Ok, then visiting with a different browser and account shouldn't be a problem.

**Comment by Mickroz** [comment] 2017-05-14 20:23
Has no effect, first pull was 32, second 52, but on my account it only showed 52, and i was expecting 84.

**Comment by mesa57** [comment] 2017-05-14 20:51
If "Automatic mark spots as read " is off, then it indeed should be 84
New spots are marked bold, are those also 52 ones ? Or if you click the new filter, are only 52 spots shown ?

**Comment by Mickroz** [comment] 2017-05-14 21:02
No "Automatic mark spots as read " is ticked.
I checked with a different account on another browser to check the counts.
The new are marked bold, and the new link only shows 52.

**Comment by mesa57** [comment] 2017-05-14 22:14
Hmmz, same problem. The account does not mather it seems.

**Comment by Mickroz** [comment] 2017-05-15 06:39
No the account does matter, this is what i did:
account #1 "Automatic mark spots as read" is on.
account #2 "Automatic mark spots as read" is on.
logged in on Chrome with #1 account, marked all as read.
logged in on Firefox with #2 account, marked all as read.
logged in on Opera with admin account, the count was 32, marked all as read.
logged in on Opera with admin account after 2 hours, the count was 52.
logged in on Chrome with #1 account after 2 hours, the count was 52, expecting 84.
logged in on Firefox with #2 account after 2 hours, the count was 84.

**Comment by mesa57** [comment] 2017-05-15 13:40
You're confusing me. You test with 3 accounts, 2 of them with "Automatic mark spots as read" on.
And then the admin account : setting unknown

The setting "Automatic mark spots as read" on can cause strange results, because it depends on stored sessions and cookies. 
I thought you had a problem with "Automatic mark spots as read" off

**Comment by Mickroz** [comment] 2017-05-15 14:10
Because the admin account setting are irrelevant and was only used to check the new spots values.
I have a problem when its on, and im the only account who has the problem with when its on.
When its on, it seems to mark my new spots as read, when my server does a new retrieve every time, even if I do not visit my spotweb server, but my friends new spots do not get marked as read.

So me and my friend have the setting both turned on.
We log in at 11:00 and mark all new spots as read with the button.
my server does a retrieve at 12:00 and retrieves 32 new spots.
At 14:00 it does a retrieve of 52 new spots.
If I log in at 14:30 I expect to have 84 new spots, but instead I only have 52 new spots.
If my friend logs in at 14:30, he has that 84 new spots, and not the 52 I got.
So something is resetting my new spots count while retrieving, but not the other accounts.(checked another friends account as well)
I have no problem if I turn the setting off.

**Comment by mesa57** [comment] 2017-05-15 20:11
Question : how do you know the number of new spots which are retrieved (I believe the nr. is wrong) ?

**Comment by Mickroz** [comment] 2017-05-15 20:28
In the New filter link label and counting them on de landing page.

**Comment by mesa57** [comment] 2017-05-16 07:58
That should be correct. It executes a query which takes a timestamp from filtercounts(you're user) first row to be used as watermark for you're spots. But that timestamp is updated to the last retrieve watermark in filtercounts(user -1) if you're last visit was more then 15 mins. ago.

**Comment by Mickroz** [comment] 2017-05-17 13:31
well, i don't know anymore, i think i will do a new install again, and just begin from scratch again, i think there are more problems then this, also for the admin account the retrieve button isn't showing, so i guess there are some more problems after my broken backup.

**Comment by mesa57** [comment] 2017-05-17 14:42
I am trying to understand the algoritme which is used, but it is very complex.

**Closed** 2017-08-08 19:46 UTC
