### ISSUE TITLE
Spot filesize >2GB problem with 32bit PHP 5.6 (and maybe others)

### ISSUE THREAD

**Issue by mbirth** [spotweb/spotweb#100] opened 2015-11-03 12:19 UTC
I have Spotweb running on a Raspberry Pi 2 (32bit) and since the migration from my 64bit Atom, I noticed that all spots larger than 2GB are always listed as 2GB only. So even a 8GB spot would show up as "2 GB" in the spots list or details.

Today I looked into that. I first checked the database and it already contained PHP_INT_MAX (2<sup>31</sup> = 2,147,483,648 = 2 GB) instead of the real value, although the database field was BIGINT. I traced the problem back to the [Dao_Base_Spot.php::addSpots()](https://github.com/spotweb/spotweb/blob/master/lib/dao/Base/Dao_Base_Spot.php#L429) method and the PDO batch insert.

It seems that `PDO::PARAM_INT` can't handle BIGINTs. [This comment on the PHP page](http://php.net/manual/en/mysqli-stmt.bind-param.php#89544) suggests using `PDO::PARAM_STR` instead.

After making the change, I now see spots with larger sizes than 2GB again.

**Comment by Sweepr** [comment] 2015-11-03 17:40
I need to test this and see what consequences this has for other OS running different kind of PHP versions and 32 or 64bit env.

Untill now i leave this open for now., thanks for your time and effort!

**Comment by mesa57** [comment] 2016-04-03 09:28
Tested on a win32 environment with php 5.6.16, mysql 5.6, pdo_mysql : 5.0.11-dev
Problem is not reproducable. I am going to mark this issue the same, and if not commented on, close it.

**Comment by mbirth** [comment] 2016-08-08 11:18
I just found this report of mine again and I think it has to do with me running Spotweb with SQLite instead of MySQL. So this probably only occurs when using SQLite as a database backend.

**Comment by mesa57** [comment] 2016-08-08 19:52
There iis a bugfix since php 5.4 (#63916) to make this work for 64 bit versions of php.
Code:
```
+#if LONG_MAX > 2147483647
		+ if (SQLITE_OK == sqlite3_bind_int64(S->stmt, param->paramno + 1, Z_LVAL_P(param->parameter))) {
		+ return 1;
		+ }
		+#else
		if (SQLITE_OK == sqlite3_bind_int(S->stmt, param->paramno + 1, Z_LVAL_P(param->parameter))) {
		return 1;
		}
		+#endif
```

**Comment by mesa57** [comment] 2016-08-08 20:05
Een oplossing voor jou zou kunnen zijn door regel 420 van dao_base_spot.php
te vervangen door :
```
                                        PDO::PARAM_STR, PDO::PARAM_STR),
```

**Comment by mbirth** [comment] 2016-08-08 23:09
I didn't have this problem on my 64bit Atom (x86_64) system, but after moving the installation to my 32bit Raspberry Pi 2 (armhf). And there, handling the BIGINT as a string (by changing `PDO::PARAM_INT` to `PDO::PARAM_STR` in `Dao_Base_Spot.php`) as per [the mentioned comment](http://php.net/manual/en/mysqli-stmt.bind-param.php#89544) made sure the full number ended up in the database.

**Comment by mesa57** [comment] 2016-08-09 07:27
Yes, that could be a solution, but it leads to (some) performance degradation.
In you're case that prob. does not matter, but this cannot be a generic change for all configurations.

**Comment by mbirth** [comment] 2016-08-09 08:45
As far as I understand, SQLite doesn't care about the format when storing data, so handing over numbers as strings doesn't matter *for SQLite* and shouldn't impact performance.

However, this would be a specific case just for SQLite and should be moved out of the `Dao_Base_Spot.php`.

**Comment by mesa57** [comment] 2016-08-09 09:14
I agree. I challenge you to create a (tested) pull request for this :smile:

**Comment by dsadsdadsadsadsds** [comment] 2016-12-27 12:56
This should be an easy fix, be sure not to insert strings for PostgreSQL though as PostgreSQL is very strict about correct types.

**Closed** 2017-03-12 19:31 UTC
Labels: bug
