### ISSUE TITLE
"Unknown MySQL server host" connecting from Raspberry PI to remote MySQL server on Synology.

### ISSUE THREAD

**Issue by Harryhar** [spotweb/spotweb#618] opened 2020-10-08 10:40 UTC
Hello,

I am trying to setup spotweb on a Raspberry Pi 3b. It used to work but I retrieved the latest version.

When I try to install spotweb i keeps giving me a "Unknown MySQL server host" error. No matter what IP I use. It's not possible to finish the install.php.

When I choose SQLite as a database I get to enter my news server credentials, but when I try to create the system I get a screen filled with a whole lot of messages, ending with an error saying : HY000: 1: no such module: ~~TFS5.~~ FTS5

Am I missing something?

**Comment by Sweepr** [comment] 2020-10-08 10:45
Are you sure it's TFS5? , not FTS5?

For the last have a look here:

https://stackoverflow.com/questions/37565423/sqlite-no-such-module-fts5-error-with-system-data-sqlite-dll-1-0-101-0

**Comment by Harryhar** [comment] 2020-10-08 11:06
Yes, typo, I mean FTS5.

The link looks it shows the same problem, but I don't know how to apply the given fix. Do I need to alter the source? Or do I need to install a package?

**Comment by Sweepr** [comment] 2020-10-08 11:17
Seems like there an extension module named "fts5" missing.

Look here starting from section 2.

https://www.sqlite.org/fts5.html

2. Compiling and Using FTS5
2.1. Building FTS5 as part of SQLite
As of version 3.9.0 (2015-10-14), FTS5 is included as part of the SQLite amalgamation. If using one of the two autoconf build system, FTS5 is enabled by specifying the "--enable-fts5" option when running the configure script. (FTS5 is currently disabled by default for the source-tree configure script and enabled by default for the amalgamation configure script, but these defaults might change in the future.)

Or, if sqlite3.c is compiled using some other build system, by arranging for the SQLITE_ENABLE_FTS5 pre-processor symbol to be defined.

**Comment by Sweepr** [comment] 2020-10-08 11:44
How di you install MySQL on Raspberry Pi 3b ? Which version is it and is the service running?

E.g. can you connect to it using CLI?

**Comment by Harryhar** [comment] 2020-10-08 18:26
The MySQL is running on a seprate machine, a Synology. From the CLI form the Raspberry Pi I can connect to the MySQL database, no problem at all. i even have the MySQL running on this Raspberry Pi, and also that is reachable via the CLI.

The install.php seems to have problems connecting to the synology and the localhost. My guess is that the installer is broken. Just try it for yourself.

**Comment by mesa57** [comment] 2020-10-08 18:29
MySQL and FTS5 ? Never heard of that one before ....

**Comment by Harryhar** [comment] 2020-10-08 18:30
No, these are 2 seperate problems. FTS5 is when you choose for SQLite.

**Comment by mesa57** [comment] 2020-10-08 18:32
Please stick to one problem at a time

**Comment by Sweepr** [comment] 2020-10-08 18:35
Do you get any error when connecting to Mysql using install.php?

Let me get this straight.

1. Raspberry with a
spotweb, and a remote Mysql DB on a Synology.

Both the Rasp and Synology have their own IP so connecting to localhost from the Rasp to the SQL can never work.

**Comment by Harryhar** [comment] 2020-10-08 19:45
You are right. Let's stick to 1 problem.

Synology running mysql.
I want to install spotweb on a raspberry pi.

This setup doesn't seem to work anymore.

The install.php keeps giving me errors when I choose the synology as mysql server, with the correct port and root password.

Connecting to the mysql server from the raspberry Pi's CLI works.

Please try it so you can see for yourself.

**Comment by Sweepr** [comment] 2020-10-08 19:50
@Harryhar.

Which branch do you use?

**Comment by mesa57** [comment] 2020-10-08 20:10
Mysql has no server. It is just a library of modules which are used to read/write a database. No server involved.
So lets concentrate on you're MySQL problem.

**Comment by Sweepr** [comment] 2020-10-09 05:16
> You are right. Let's stick to 1 problem.
> 
> Synology running mysql.
> I want to install spotweb on a raspberry pi.
> 
> This setup doesn't seem to work anymore.
> 
> The install.php keeps giving me errors when I choose the synology as mysql server, with the correct port and root password.
> 
> Connecting to the mysql server from the raspberry Pi's CLI works.
> 
> **Please try it so you can see for yourself.**

Since i don't own a Raspberry PI, it's not possible replicate/reproduce your exact setup here, so for us it's impossible to debug this issue without more information. 

For that reason i would kindly like to ask you to fill in the form:

**Describe the bug/issue**
 - A clear and concise description of what the bug is.

**Have you searched the internet or Github for an answer?**
 - Please search google if similar issue has been reported and fixed before.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
 - A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Spotweb Version [e.g. 1.4.8]
 - Which branch  (Master/Develop)
 -  PHP version
 -  Device information (ReadyNAS/Synology/FreeNAS)

**Smartphone if applicable (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Spotweb Version [e.g. 1.4.8]
 - Which branch  (Master/Develop)
-  PHP version
-  Device information (ReadyNAS/Synology/FreeNAS)

**Additional context**
Provide any other information about the bug or issue that can further help debugging here.

**Comment by mesa57** [comment] 2020-10-09 09:20
@Sweepr A raspberry normally contains a Debian installation. You could execute a test from Debian to Synology MySQL.

**Comment by Sweepr** [comment] 2020-10-09 09:25
> @Sweepr A raspberry normally contains a Debian installation. You could execute a test from Debian to Synology MySQL.

@mesa57 That's an option, but then i would have to re-create the exact condiotions like @Harryhar 
Maybe this issue is related to this fix: 617 , therefor would like to ask @Harryhar if he is running Master or Develop branch.

https://github.com/spotweb/spotweb/pull/617

**Comment by Harryhar** [comment] 2020-10-09 09:38
I am using the develop branch.

I figured out that connection to my Synology with mysql from the CLI works when I use the port value (3306). If I don't supply a portnumber the connection also works.

When I create my own test.php file and try to connect via pdo all works well as long as I don't use the port value. The moment the port value is used I get the same connection problems.

I altered the dbeng_pdo_mysql.php file to look if the entered port is empty, and then simply connect without the port info.

`                 if ($port == "") {
                     $db_conn = 'host='.$host;
                 } else {
                     $db_conn = 'host='.$host.':'.$port;
                 }
`

For now this seems to work for my case.

**Comment by Sweepr** [comment] 2020-10-09 09:46
@harryhar. Can you check if this fix is in your installation?

https://github.com/spotweb/spotweb/pull/617

**Comment by mesa57** [comment] 2020-10-09 09:56
Port should have a default value of 3306

**Comment by Harryhar** [comment] 2020-10-09 11:03
@Sweepr, that does not fix my problem.

**Comment by Sweepr** [comment] 2020-10-09 11:22
You write here: `"When I create my own test.php file and try to connect via pdo all works well as long as I don't use the port value. The moment the port value is used I get the same connection problems."`

This tells me the problem is not related to Spotweb but something with your setup.

It's simply not possible to connect to a **remote** SQL server without specifying an IP address and port number (3306) in which to connect to, only way possible to connect to SQL server without a port number is via sockets using localhost/127.0.0.1.

The way you describe is like sending a letter to an adress without writing a housenumber on the card, the postman cannot delivber the letter because it does not know which house it should deliver to.

Please double check your setup.

**Comment by Harryhar** [comment] 2020-10-09 13:46
I understand what you say, but for MySQL 3306 is the default port, so maybe it connects to this port when it is not entered in the connectionstring. I connect internally with my Synology, the Pi and Synology are on the same network.

I will try to figure out why connection via PHP won't work like it supposed to do.

**Comment by mesa57** [comment] 2020-10-10 09:34
There is some ambiguity about the port in dsn mysql.
In the php manual the syntax {host};port={port} is mentioned. However also syntax {host}:{port} seems to work.
Last one is used by spotweb to be compatible with users which already used that syntax,

**Comment by Sweepr** [comment] 2020-10-17 09:13
By means of trying to reproduce this i setup a Debian VM 

![image](https://user-images.githubusercontent.com/2857865/96333102-47ab8b80-1068-11eb-8403-a9b92e5b3f6a.png)

![image](https://user-images.githubusercontent.com/2857865/96333112-53974d80-1068-11eb-8fef-88519c1f5f3b.png)

Tried installing Spotweb on a remote database using SQL server MariaDB 5:

![image](https://user-images.githubusercontent.com/2857865/96333147-8c372700-1068-11eb-8b17-e76a1ac4f78f.png)
 
Without port:

![image](https://user-images.githubusercontent.com/2857865/96332612-6bb99d80-1065-11eb-9ffb-0bbab08048c4.png)

When adding port "3306" to the installation, the installation continued.

All seems to work as intented, i will close this for now.

Feel free to re-open if any further assistance is needed.

**Closed by Sweepr** 2020-10-17 09:13 UTC
Labels: Help wanted, Not reproducable
