### ISSUE TITLE
Undefined index: performredirect in /var/www/html/lib/page/SpotPage_login.php on line 42

### ISSUE THREAD

**Issue by aroundmyroom** [spotweb/spotweb#725] opened 2021-11-28 14:48 UTC
when new user wants to login with latest git pull I get this error

Undefined index: performredirect in /var/www/html/lib/page/SpotPage_login.php on line 42
and than cannot login

When there was already a login, no issue

**Comment by Sweepr** [comment] 2021-11-28 15:22
@aroundmyroom  I am unable to reproduce this on my workspace., are you using open/shared/public?

@mesa57 Are you able to reproduce this issue?

**Comment by aroundmyroom** [comment] 2021-11-28 16:17
yes very 
wierd, disable this

//        if (preg_match('/[<>]/i', $this->_params['data']['performredirect'])) {
//            $result->addError(_('Script is not allowed'));
//        }


no issue and  I can login

error.log gave this

[php7:notice] [pid 33225] [client 10.1.1.161:10892] PHP Notice:  Undefined index: performredirect in /var/www/html/lib/page/SpotPage_login.php on line 42, referer:

git pull gave no indication that something was missing

**Comment by Sweepr** [comment] 2021-12-04 10:32
@aroundmyroom 

Are you still experiencing this issue?

If so could you change file `/lib/page/SpotPage_login.php`: from line 41

https://github.com/spotweb/spotweb/blob/9af0ade0f618675206dcf1f744dbb3c1eae70e5a/lib/page/SpotPage_login.php#L41

This:

```
        // Check redirect for chevrons, deny if found.
        if (preg_match('/[<>]/i', $this->_params['data']['performredirect'])) {
            $result->addError(_('Script is not allowed'));
        }
```

Into:

```
	// Before using $this->_params['data']['performredirect'] check if it is set.  
	if (isset($this->_params['data']['performredirect'])) {    
		// Check redirect for chevrons, deny if found.     
		if (preg_match('/[<>]/i', $this->_params['data']['performredirect'])) {			
		$result->addError(_('Script is not allowed'));
		}
	}  
```

**Comment by aroundmyroom** [comment] 2021-12-05 20:54
@Sweepr yup that change solves the issue

**Comment by Sweepr** [comment] 2021-12-07 16:53
Fixed in: https://github.com/spotweb/spotweb/commit/2391e459a4aa2884ab9b1349b714894ef0a2d0a8

**Closed by Sweepr** 2021-12-07 16:54 UTC
Labels: Not reproducable
