### ISSUE TITLE
Error when running bin/upgrade_db.php twice

### ISSUE THREAD

**Issue by klara31** [spotweb/spotweb#418] opened 2019-07-04 06:52 UTC
running on commit c3ba08814ef879ce77d84473986b305c6a8d29da on ubuntu 18.04

When I create an empty database spotweb and run bin/upgrade_db.php, the command finishes without errors. When running this command again without changing anything in the mean time, the following error is thrown:
```
# php bin/upgrade-db.php 
Updating schema..(pdo_mysql)
	Validating spots(messageid)
	Validating spots(poster)
	Validating spots(title)
	Validating spots(tag)
	Validating spots(category)
	Validating spots(subcata)
	Validating spots(subcatb)
	Validating spots(subcatc)
	Validating spots(subcatd)
	Validating spots(subcatz)
	Validating spots(stamp)
	Validating spots(reversestamp)
	Validating spots(filesize)
	Validating spots(moderated)
	Validating spots(commentcount)
	Validating spots(spotrating)
	Validating spots(reportcount)
	Validating spots(spotterid)
	Validating spots(editstamp)
	Validating spots(editor)
	Validating spotsfull(messageid)
	Validating spotsfull(verified)
	Validating spotsfull(usersignature)
	Validating spotsfull(userkey)
	Validating spotsfull(xmlsignature)
	Validating spotsfull(fullxml)
	Validating usenetstate(infotype)
	Validating usenetstate(curarticlenr)
	Validating usenetstate(curmessageid)
	Validating usenetstate(lastretrieved)
	Validating usenetstate(nowrunning)
	Validating commentsxover(messageid)
	Validating commentsxover(nntpref)
	Validating commentsxover(spotrating)
	Validating commentsxover(moderated)
	Validating commentsxover(stamp)
	Validating reportsxover(messageid)
	Validating reportsxover(fromhdr)
	Validating reportsxover(keyword)
	Validating reportsxover(nntpref)
	Validating spotstatelist(messageid)
	Validating spotstatelist(ouruserid)
	Validating spotstatelist(download)
	Validating spotstatelist(watch)
	Validating spotstatelist(seen)
	Validating commentsfull(messageid)
	Validating commentsfull(fromhdr)
	Validating commentsfull(stamp)
	Validating commentsfull(usersignature)
	Validating commentsfull(userkey)
	Validating commentsfull(spotterid)
	Validating commentsfull(hashcash)
	Validating commentsfull(body)
	Validating commentsfull(verified)
	Validating commentsfull(avatar)
	Validating settings(name)
	Validating settings(value)
	Validating settings(serialized)
	Validating commentsposted(ouruserid)
	Validating commentsposted(messageid)
	Validating commentsposted(inreplyto)
	Validating commentsposted(randompart)
	Validating commentsposted(rating)
	Validating commentsposted(body)
	Validating commentsposted(stamp)
	Validating spotsposted(messageid)
	Validating spotsposted(ouruserid)
	Validating spotsposted(stamp)
	Validating spotsposted(title)
	Validating spotsposted(tag)
	Validating spotsposted(category)
	Validating spotsposted(subcats)
	Validating spotsposted(filesize)
	Validating spotsposted(fullxml)
	Validating reportsposted(ouruserid)
	Validating reportsposted(messageid)
	Validating reportsposted(inreplyto)
	Validating reportsposted(randompart)
	Validating reportsposted(body)
	Validating reportsposted(stamp)
	Validating usersettings(userid)
	Validating usersettings(privatekey)
	Validating usersettings(publickey)
	Validating usersettings(avatar)
	Validating usersettings(otherprefs)
	Validating users(username)
	Validating users(firstname)
	Validating users(passhash)
	Validating users(lastname)
	Validating users(mail)
	Validating users(apikey)
	Validating users(lastlogin)
	Validating users(lastvisit)
	Validating users(lastread)
	Validating users(lastapiusage)
	Validating users(deleted)
	Validating sessions(sessionid)
	Validating sessions(userid)
	Validating sessions(hitcount)
	Validating sessions(lasthit)
	Validating sessions(ipaddr)
	Validating sessions(devicetype)
	Validating securitygroups(name)
	Validating grouppermissions(groupid)
	Validating grouppermissions(permissionid)
	Validating grouppermissions(objectid)
	Validating grouppermissions(deny)
	Validating usergroups(userid)
	Validating usergroups(groupid)
	Validating usergroups(prio)
	Validating notifications(userid)
	Validating notifications(stamp)
	Validating notifications(objectid)
	Validating notifications(type)
	Validating notifications(title)
	Validating notifications(body)
	Validating notifications(sent)
	Validating filters(userid)
	Validating filters(filtertype)
	Validating filters(title)
	Validating filters(icon)
	Validating filters(torder)
	Validating filters(tparent)
	Validating filters(tree)
	Validating filters(valuelist)
	Validating filters(sorton)
	Validating filters(sortorder)
	Validating filters(enablenotify)
	Validating filtercounts(userid)
	Validating filtercounts(filterhash)
	Validating filtercounts(currentspotcount)
	Validating filtercounts(lastvisitspotcount)
	Validating filtercounts(lastupdate)
	Validating spotteridblacklist(spotterid)
	Validating spotteridblacklist(ouruserid)
	Validating spotteridblacklist(idtype)
	Validating spotteridblacklist(origin)
	Validating spotteridblacklist(doubled)
	Validating cache(resourceid)
	Validating cache(cachetype)
	Validating cache(stamp)
	Validating cache(metadata)
	Validating cache(ttl)
	Validating moderatedringbuffer(messageid)
	Validating permaudit(stamp)
	Validating permaudit(userid)
	Validating permaudit(permissionid)
	Validating permaudit(objectid)
	Validating permaudit(result)
	Validating permaudit(ipaddr)
	Validating index idx_spots_1
PHP Notice:  Undefined index: column_name in /var/www/spotweb/lib/dbstruct/SpotStruct_abs.php on line 227
		Dropping index idx_spots_1
		Adding index idx_spots_1
	Validating index idx_spots_2
PHP Notice:  Undefined index: column_name in /var/www/spotweb/lib/dbstruct/SpotStruct_abs.php on line 227
		Dropping index idx_spots_2
		Adding index idx_spots_2
	Validating index idx_spots_3
PHP Notice:  Undefined index: column_name in /var/www/spotweb/lib/dbstruct/SpotStruct_abs.php on line 227
		Dropping index idx_spots_3
		Adding index idx_spots_3
	Validating index idx_spots_4
PHP Notice:  Undefined index: column_name in /var/www/spotweb/lib/dbstruct/SpotStruct_abs.php on line 227
		Dropping index idx_spots_4
		Adding index idx_spots_4
	Validating index idx_spots_5
PHP Notice:  Undefined index: column_name in /var/www/spotweb/lib/dbstruct/SpotStruct_abs.php on line 227
		Dropping index idx_spots_5
		Adding index idx_spots_5
	Validating FTS idx_fts_spots
PHP Notice:  Undefined index: column_name in /var/www/spotweb/lib/dbstruct/SpotStruct_abs.php on line 266
PHP Notice:  Undefined index: column_name in /var/www/spotweb/lib/dbstruct/SpotStruct_mysql.php on line 109
		Adding FTS idx_fts_spots
PHP Notice:  Undefined index: column_name in /var/www/spotweb/lib/dbstruct/SpotStruct_mysql.php on line 122
PHP Notice:  Undefined index: column_name in /var/www/spotweb/lib/dbstruct/SpotStruct_mysql.php on line 122
PHP Notice:  Undefined index: column_name in /var/www/spotweb/lib/dbstruct/SpotStruct_mysql.php on line 122
	Validating index idx_usenetstate_1
PHP Notice:  Undefined index: column_name in /var/www/spotweb/lib/dbstruct/SpotStruct_abs.php on line 227
		Dropping index idx_usenetstate_1
		Adding index idx_usenetstate_1
	Validating index idx_spotsfull_1
PHP Notice:  Undefined index: column_name in /var/www/spotweb/lib/dbstruct/SpotStruct_abs.php on line 227
		Dropping index idx_spotsfull_1
		Adding index idx_spotsfull_1
	Validating index idx_commentsfull_1
PHP Notice:  Undefined index: column_name in /var/www/spotweb/lib/dbstruct/SpotStruct_abs.php on line 227
		Dropping index idx_commentsfull_1


SpotWeb crashed

Database schema or settings upgrade failed:
   HY000: 1553: Cannot drop index 'idx_commentsfull_1': needed in a foreign key constraint


#0 /var/www/spotweb/lib/dbstruct/SpotStruct_mysql.php(162): dbeng_pdo->rawExec('DROP INDEX idx_...')
#1 /var/www/spotweb/lib/dbstruct/SpotStruct_abs.php(125): SpotStruct_mysql->dropIndex('idx_commentsful...', 'commentsfull')
#2 /var/www/spotweb/lib/dbstruct/SpotStruct_abs.php(711): SpotStruct_abs->validateIndex('idx_commentsful...', 'UNIQUE', 'commentsfull', Array)
#3 /var/www/spotweb/lib/services/Upgrade/Services_Upgrade_Base.php(42): SpotStruct_abs->updateSchema()
#4 /var/www/spotweb/bin/upgrade-db.php(34): Services_Upgrade_Base->database()
#5 {main}
```

**Comment by mesa57** [comment] 2019-08-27 16:06
You do not need to run upgrade-db on a new created spotweb database.
Closing this issue, please reopen if needed.

**Closed by mesa57** 2019-08-27 16:06 UTC

**Comment by klara31** [comment] 2019-08-27 18:48
If I switch from master branch to dev, upgrade_db.php has to run and then the same error occurs

**Comment by mesa57** [comment] 2019-08-27 19:59
I cannot reproduce this error, neither with mysql 5.7 nor with mariadb 10.4
Running php 7.1

**Comment by mesa57** [comment] 2019-08-27 20:05
Please try to execute next query with you're spotweb db user and post the result :
```
SELECT 
											column_name, 
											non_unique, 
											lower(index_type) as index_type
										FROM information_schema.STATISTICS 
										WHERE TABLE_SCHEMA = DATABASE() 
										  AND table_name = "spots"
										  AND index_name = "idx_spots_1"
										ORDER BY seq_in_index
```

**Comment by klara31** [comment] 2019-08-27 21:14
Query gives the following response:
```
mysql> select column_name, non_unique, lower(index_type) as index_type
    -> FROM information_schema.STATISTICS 
    -> WHERE TABLE_SCHEMA = DATABASE() 
    -> AND table_name = "spots"
    -> AND index_name = "idx_spots_1"
    -> ORDER BY seq_in_index;
+-------------+------------+------------+
| COLUMN_NAME | NON_UNIQUE | index_type |
+-------------+------------+------------+
| messageid   |          0 | btree      |
+-------------+------------+------------+
1 row in set (0.01 sec)
````
I am running Percona MySQL version 8.0.16-7-1.stretch on a Debian 9 database server and Spotweb on a standard Ubuntu 19.04 host with PHP 7.2

**Comment by klara31** [comment] 2019-08-27 21:29
With the commits of the past few days on master branch, I am getting the same problem. Had to roll back to aa123a41101568e08fd9d18e0d23b112588b9b8f get spotweb running again.

With the updates, the browser throws the following message:
````
Spotweb contains updated global settings settings. Please run 'bin/upgrade-db.php' from a console window
````

**Comment by mesa57** [comment] 2019-08-28 10:05
Last message is normal.  The output of the query looks also fine. 
I think it must be in some user rights.

**Comment by klara31** [comment] 2019-08-28 11:02
I'm not a complete greeny when it comes to databases, and do not think that the problem is linked to user rights. The spotweb user has ALL PRIVILEGES granted on the database. 

When dropping the database and starting with a empty new database, the script runs OK. When surfing to the spotweb site, the following error is thrown:
````
Notice: Undefined index: xsrfsecret in /var/www/spotweb/lib/services/Settings/Services_Settings_Container.php on line 62

Notice: Undefined index: settingsversion in /var/www/spotweb/lib/services/Settings/Services_Settings_Container.php on line 62
Spotweb contains updated global settings settings. Please run 'bin/upgrade-db.php' from a console window
````
when I run the upgrade_db.php script, I'm back to the error as described in the first post. 

I'm sorry, but it really looks like a software issue to me... If you need me to do some additional testing, please let me know as I am happy to help!

**Comment by Sweepr** [comment] 2019-08-28 11:19
Does this help?

https://github.com/jgeusebroek/docker-spotweb/issues/2

**Comment by klara31** [comment] 2019-08-28 11:27
No, it does not. I have to run upgrade_db.php twice. At the second run, I'm back to the original issue

**Comment by Sweepr** [comment] 2019-08-28 11:57
Yesterday we released 1.40, pushed the latest changes from dev -> master and reverted some breaking commits, did you try that version yet?

**Comment by Sweepr** [comment] 2019-08-28 12:03
Not sure what happend but all the "Notice: Undefined index: xsrfsecret" etc error's tell me there could be missing entries in your database..

Can you check your DB if for example "xsrfsecret" in table settings?

**Comment by klara31** [comment] 2019-08-28 12:28
> Yesterday we released 1.40, pushed the latest changes from dev -> master and reverted some breaking commits, did you try that version yet?

I upgraded master from commit aa123a41101568e08fd9d18e0d23b112588b9b8f to the latest version, which requires running upgrade_db.php. Every time I have to run upgrade_db.php, the error occurs!

> Can you check your DB if for example "xsrfsecret" in table settings exists?

After running upgrade_db.php on an empty database, there is no table "xsrfsecret"

**Comment by klara31** [comment] 2019-08-28 12:32
> Yesterday we released 1.40, pushed the latest changes from dev -> master and reverted some breaking commits, did you try that version yet?

When I upgrade from commit aa123a41101568e08fd9d18e0d23b112588b9b8f, running upgrade_db.php is required. Every time I have to run this script (after the initial run), I am getting this error!

> Can you check your DB if for example "xsrfsecret" in table settings exists?

"xsrfsecret" does not exist

**Comment by Sweepr** [comment] 2019-08-28 12:55
That's akward, missing entries means your database is corrupted.

I would trash the entire DB, create a fresh one, and 
fetch the latest master, and install from there.

**Comment by klara31** [comment] 2019-08-28 13:49
> I would trash the entire DB, create a fresh one, and fetch the latest master (or Dev) and install from there.

That is exactly what I did!

**Comment by Sweepr** [comment] 2019-08-28 14:35
Did a new install on a newly create database of the master branch:

Using: git clone https://github.com/spotweb/spotweb.git
Completed the install, then from the commandline:

php upgrade-db.php
Updating schema..(pdo_mysql)
        Validating spots(messageid)
        Validating spots(poster)
        Validating spots(title)
        Validating spots(tag)
        Validating spots(category)
        Validating spots(subcata)
        Validating spots(subcatb)
        Validating spots(subcatc)
        Validating spots(subcatd)
        Validating spots(subcatz)
        Validating spots(stamp)
        Validating spots(reversestamp)
        Validating spots(filesize)
        Validating spots(moderated)
        Validating spots(commentcount)
        Validating spots(spotrating)
        Validating spots(reportcount)
        Validating spots(spotterid)
        Validating spots(editstamp)
        Validating spots(editor)
        Validating spotsfull(messageid)
        Validating spotsfull(verified)
        Validating spotsfull(usersignature)
        Validating spotsfull(userkey)
        Validating spotsfull(xmlsignature)
        Validating spotsfull(fullxml)
        Validating usenetstate(infotype)
        Validating usenetstate(curarticlenr)
        Validating usenetstate(curmessageid)
        Validating usenetstate(lastretrieved)
        Validating usenetstate(nowrunning)
        Validating commentsxover(messageid)
        Validating commentsxover(nntpref)
        Validating commentsxover(spotrating)
        Validating commentsxover(moderated)
        Validating commentsxover(stamp)
        Validating reportsxover(messageid)
        Validating reportsxover(fromhdr)
        Validating reportsxover(keyword)
        Validating reportsxover(nntpref)
        Validating spotstatelist(messageid)
        Validating spotstatelist(ouruserid)
        Validating spotstatelist(download)
        Validating spotstatelist(watch)
        Validating spotstatelist(seen)
        Validating commentsfull(messageid)
        Validating commentsfull(fromhdr)
        Validating commentsfull(stamp)
        Validating commentsfull(usersignature)
        Validating commentsfull(userkey)
        Validating commentsfull(spotterid)
        Validating commentsfull(hashcash)
        Validating commentsfull(body)
        Validating commentsfull(verified)
        Validating commentsfull(avatar)
        Validating settings(name)
        Validating settings(value)
        Validating settings(serialized)
        Validating commentsposted(ouruserid)
        Validating commentsposted(messageid)
        Validating commentsposted(inreplyto)
        Validating commentsposted(randompart)
        Validating commentsposted(rating)
        Validating commentsposted(body)
        Validating commentsposted(stamp)
        Validating spotsposted(messageid)
        Validating spotsposted(ouruserid)
        Validating spotsposted(stamp)
        Validating spotsposted(title)
        Validating spotsposted(tag)
        Validating spotsposted(category)
        Validating spotsposted(subcats)
        Validating spotsposted(filesize)
        Validating spotsposted(fullxml)
        Validating reportsposted(ouruserid)
        Validating reportsposted(messageid)
        Validating reportsposted(inreplyto)
        Validating reportsposted(randompart)
        Validating reportsposted(body)
        Validating reportsposted(stamp)
        Validating usersettings(userid)
        Validating usersettings(privatekey)
        Validating usersettings(publickey)
        Validating usersettings(avatar)
        Validating usersettings(otherprefs)
        Validating users(username)
        Validating users(firstname)
        Validating users(passhash)
        Validating users(lastname)
        Validating users(mail)
        Validating users(apikey)
        Validating users(lastlogin)
        Validating users(lastvisit)
        Validating users(lastread)
        Validating users(lastapiusage)
        Validating users(deleted)
        Validating sessions(sessionid)
        Validating sessions(userid)
        Validating sessions(hitcount)
        Validating sessions(lasthit)
        Validating sessions(ipaddr)
        Validating sessions(devicetype)
        Validating securitygroups(name)
        Validating grouppermissions(groupid)
        Validating grouppermissions(permissionid)
        Validating grouppermissions(objectid)
        Validating grouppermissions(deny)
        Validating usergroups(userid)
        Validating usergroups(groupid)
        Validating usergroups(prio)
        Validating notifications(userid)
        Validating notifications(stamp)
        Validating notifications(objectid)
        Validating notifications(type)
        Validating notifications(title)
        Validating notifications(body)
        Validating notifications(sent)
        Validating filters(userid)
        Validating filters(filtertype)
        Validating filters(title)
        Validating filters(icon)
        Validating filters(torder)
        Validating filters(tparent)
        Validating filters(tree)
        Validating filters(valuelist)
        Validating filters(sorton)
        Validating filters(sortorder)
        Validating filters(enablenotify)
        Validating filtercounts(userid)
        Validating filtercounts(filterhash)
        Validating filtercounts(currentspotcount)
        Validating filtercounts(lastvisitspotcount)
        Validating filtercounts(lastupdate)
        Validating spotteridblacklist(spotterid)
        Validating spotteridblacklist(ouruserid)
        Validating spotteridblacklist(idtype)
        Validating spotteridblacklist(origin)
        Validating spotteridblacklist(doubled)
        Validating cache(resourceid)
        Validating cache(cachetype)
        Validating cache(stamp)
        Validating cache(metadata)
        Validating cache(ttl)
        Validating moderatedringbuffer(messageid)
        Validating permaudit(stamp)
        Validating permaudit(userid)
        Validating permaudit(permissionid)
        Validating permaudit(objectid)
        Validating permaudit(result)
        Validating permaudit(ipaddr)
        Validating index idx_spots_1
        Validating index idx_spots_2
        Validating index idx_spots_3
        Validating index idx_spots_4
        Validating index idx_spots_5
        Validating FTS idx_fts_spots
        Validating index idx_usenetstate_1
        Validating index idx_spotsfull_1
        Validating index idx_commentsfull_1
        Validating index idx_commentsxover_1
        Validating index idx_commentsxover_2
        Validating index idx_reportsxover_1
        Validating index idx_reportsxover_2
        Validating index idx_reportsposted_1
        Validating index idx_reportsposted_2
        Validating index idx_reportspostedrel_1
        Validating index idx_commentsposted_1
        Validating index idx_commentspostedrel_1
        Validating index idx_spotsposted_1
        Validating index idx_spotspostedrel_1
        Validating index idx_settings_1
        Validating index idx_usersettings_1
        Validating index idx_users_1
        Validating index idx_users_2
        Validating index idx_users_3
        Validating index idx_users_4
        Validating index idx_sessions_1
        Validating index idx_sessions_2
        Validating index idx_sessions_3
        Validating index idx_sessionsrel_1
        Validating index idx_spotstatelist_1
        Validating index idx_spotstatelistrel_1
        Validating index idx_securitygroups_1
        Validating index idx_grouppermissions_1
        Validating index idx_usergroups_1
        Validating index idx_usergroupsrel_1
        Validating index idx_notifications_1
        Validating index idx_notifications_2
        Validating index idx_filters_1
        Validating index idx_filtercounts_1
        Validating index idx_spotteridblacklist_1
        Validating index idx_spotteridblacklist_2
        Validating index idx_cache_1
        Validating index idx_cache_2
        Validating index idx_moderatedringbuffer_1
Schema update done
Updating settings
Settings update done
Updating users
Users' update done
Performing basic analysis of database tables
Basic database optimalisation done

And again:

php upgrade-db.php
Updating schema..(pdo_mysql)
        Validating spots(messageid)
        Validating spots(poster)
        Validating spots(title)
        Validating spots(tag)
        Validating spots(category)
        Validating spots(subcata)
        Validating spots(subcatb)
        Validating spots(subcatc)
        Validating spots(subcatd)
        Validating spots(subcatz)
        Validating spots(stamp)
        Validating spots(reversestamp)
        Validating spots(filesize)
        Validating spots(moderated)
        Validating spots(commentcount)
        Validating spots(spotrating)
        Validating spots(reportcount)
        Validating spots(spotterid)
        Validating spots(editstamp)
        Validating spots(editor)
        Validating spotsfull(messageid)
        Validating spotsfull(verified)
        Validating spotsfull(usersignature)
        Validating spotsfull(userkey)
        Validating spotsfull(xmlsignature)
        Validating spotsfull(fullxml)
        Validating usenetstate(infotype)
        Validating usenetstate(curarticlenr)
        Validating usenetstate(curmessageid)
        Validating usenetstate(lastretrieved)
        Validating usenetstate(nowrunning)
        Validating commentsxover(messageid)
        Validating commentsxover(nntpref)
        Validating commentsxover(spotrating)
        Validating commentsxover(moderated)
        Validating commentsxover(stamp)
        Validating reportsxover(messageid)
        Validating reportsxover(fromhdr)
        Validating reportsxover(keyword)
        Validating reportsxover(nntpref)
        Validating spotstatelist(messageid)
        Validating spotstatelist(ouruserid)
        Validating spotstatelist(download)
        Validating spotstatelist(watch)
        Validating spotstatelist(seen)
        Validating commentsfull(messageid)
        Validating commentsfull(fromhdr)
        Validating commentsfull(stamp)
        Validating commentsfull(usersignature)
        Validating commentsfull(userkey)
        Validating commentsfull(spotterid)
        Validating commentsfull(hashcash)
        Validating commentsfull(body)
        Validating commentsfull(verified)
        Validating commentsfull(avatar)
        Validating settings(name)
        Validating settings(value)
        Validating settings(serialized)
        Validating commentsposted(ouruserid)
        Validating commentsposted(messageid)
        Validating commentsposted(inreplyto)
        Validating commentsposted(randompart)
        Validating commentsposted(rating)
        Validating commentsposted(body)
        Validating commentsposted(stamp)
        Validating spotsposted(messageid)
        Validating spotsposted(ouruserid)
        Validating spotsposted(stamp)
        Validating spotsposted(title)
        Validating spotsposted(tag)
        Validating spotsposted(category)
        Validating spotsposted(subcats)
        Validating spotsposted(filesize)
        Validating spotsposted(fullxml)
        Validating reportsposted(ouruserid)
        Validating reportsposted(messageid)
        Validating reportsposted(inreplyto)
        Validating reportsposted(randompart)
        Validating reportsposted(body)
        Validating reportsposted(stamp)
        Validating usersettings(userid)
        Validating usersettings(privatekey)
        Validating usersettings(publickey)
        Validating usersettings(avatar)
        Validating usersettings(otherprefs)
        Validating users(username)
        Validating users(firstname)
        Validating users(passhash)
        Validating users(lastname)
        Validating users(mail)
        Validating users(apikey)
        Validating users(lastlogin)
        Validating users(lastvisit)
        Validating users(lastread)
        Validating users(lastapiusage)
        Validating users(deleted)
        Validating sessions(sessionid)
        Validating sessions(userid)
        Validating sessions(hitcount)
        Validating sessions(lasthit)
        Validating sessions(ipaddr)
        Validating sessions(devicetype)
        Validating securitygroups(name)
        Validating grouppermissions(groupid)
        Validating grouppermissions(permissionid)
        Validating grouppermissions(objectid)
        Validating grouppermissions(deny)
        Validating usergroups(userid)
        Validating usergroups(groupid)
        Validating usergroups(prio)
        Validating notifications(userid)
        Validating notifications(stamp)
        Validating notifications(objectid)
        Validating notifications(type)
        Validating notifications(title)
        Validating notifications(body)
        Validating notifications(sent)
        Validating filters(userid)
        Validating filters(filtertype)
        Validating filters(title)
        Validating filters(icon)
        Validating filters(torder)
        Validating filters(tparent)
        Validating filters(tree)
        Validating filters(valuelist)
        Validating filters(sorton)
        Validating filters(sortorder)
        Validating filters(enablenotify)
        Validating filtercounts(userid)
        Validating filtercounts(filterhash)
        Validating filtercounts(currentspotcount)
        Validating filtercounts(lastvisitspotcount)
        Validating filtercounts(lastupdate)
        Validating spotteridblacklist(spotterid)
        Validating spotteridblacklist(ouruserid)
        Validating spotteridblacklist(idtype)
        Validating spotteridblacklist(origin)
        Validating spotteridblacklist(doubled)
        Validating cache(resourceid)
        Validating cache(cachetype)
        Validating cache(stamp)
        Validating cache(metadata)
        Validating cache(ttl)
        Validating moderatedringbuffer(messageid)
        Validating permaudit(stamp)
        Validating permaudit(userid)
        Validating permaudit(permissionid)
        Validating permaudit(objectid)
        Validating permaudit(result)
        Validating permaudit(ipaddr)
        Validating index idx_spots_1
        Validating index idx_spots_2
        Validating index idx_spots_3
        Validating index idx_spots_4
        Validating index idx_spots_5
        Validating FTS idx_fts_spots
        Validating index idx_usenetstate_1
        Validating index idx_spotsfull_1
        Validating index idx_commentsfull_1
        Validating index idx_commentsxover_1
        Validating index idx_commentsxover_2
        Validating index idx_reportsxover_1
        Validating index idx_reportsxover_2
        Validating index idx_reportsposted_1
        Validating index idx_reportsposted_2
        Validating index idx_reportspostedrel_1
        Validating index idx_commentsposted_1
        Validating index idx_commentspostedrel_1
        Validating index idx_spotsposted_1
        Validating index idx_spotspostedrel_1
        Validating index idx_settings_1
        Validating index idx_usersettings_1
        Validating index idx_users_1
        Validating index idx_users_2
        Validating index idx_users_3
        Validating index idx_users_4
        Validating index idx_sessions_1
        Validating index idx_sessions_2
        Validating index idx_sessions_3
        Validating index idx_sessionsrel_1
        Validating index idx_spotstatelist_1
        Validating index idx_spotstatelistrel_1
        Validating index idx_securitygroups_1
        Validating index idx_grouppermissions_1
        Validating index idx_usergroups_1
        Validating index idx_usergroupsrel_1
        Validating index idx_notifications_1
        Validating index idx_notifications_2
        Validating index idx_filters_1
        Validating index idx_filtercounts_1
        Validating index idx_spotteridblacklist_1
        Validating index idx_spotteridblacklist_2
        Validating index idx_cache_1
        Validating index idx_cache_2
        Validating index idx_moderatedringbuffer_1
Schema update done
Updating settings
Settings update done
Updating users
Users' update done
Performing basic analysis of database tables
Basic database optimalisation done

I'm not able to reproduce this error, can you write exactly step by step how reproduce this?

**Comment by klara31** [comment] 2019-08-28 15:37
I am doing _exactly_ what you are doing, except that at the second run, I am getting the error as in the first post.

Which PHP/MySQL version are you using? I am on PHP7.2 and Percona Server 8.0.16-7-1.stretch.

**Comment by mesa57** [comment] 2019-08-28 17:41
That database is not supported by windows and therefor not tested.
Use at own risk.

**Comment by klara31** [comment] 2019-08-28 20:53
I am not running on Windows, I am running Linux!

**Comment by Sweepr** [comment] 2019-08-29 04:45
I'm running,

PHP 7.3.3 (cli) (built: Mar  6 2019 21:53:23) ( ZTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.3, Copyright (c) 1998-2018 Zend Technologies

MariaDB 
Server version: 10.1.38-MariaDB mariadb.org binary distribution

And my VM:

PHP 7.2.21 (cli) (built: Aug 20 2019 17:36:36) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Xdebug v2.6.1, Copyright (c) 2002-2018, by Derick Rethans

MariaDB
Server version: 10.2.26-MariaDB MariaDB Server

Both run fine.

**Comment by klara31** [comment] 2019-08-29 06:32
So most likely, the issue is MySQL 8. I will docker up a MySQL 5.7 server to test and let you know what the result is.

Anticipating to that, what's the roadmap regarding MySQL 8?

**Comment by klara31** [comment] 2019-08-29 07:48
I can confirm that the issue is MySQL 8: the issue does not occur on MySQL 5.7. 

What's the roadmap on MySQL 8?

**Comment by Sweepr** [comment] 2019-08-29 08:45
Mesa57, probably means "That database is not supported by windows and therefor not tested.
Use at own risk."

And that's it's crucial we have the   needed information about your environment.

**Comment by Sweepr** [comment] 2019-09-01 14:57
Fixed in:

d106060
e42a183
